#!/usr/bin/env python3
"""Compare stage/replay/texture paths generated by the original game logic.
Usage: differential_stage_paths.py entities.json [rebuilt.exe]
Selection providers and sprintf are controlled leaves. Country/code tables,
branch selection and every generated path execute in the real images.
"""
import itertools,json,re,sys
from pathlib import Path
from unicorn.x86_const import UC_X86_REG_EAX,UC_X86_REG_EIP,UC_X86_REG_ESP
from differential_menu_list import Drawing,ROOT,HEAP,STACK,STOP


class Paths(Drawing):
    def __init__(self,path,entities=None):
        super().__init__(path,entities)
        self.callbacks={self.addr(0x405620):(0,self.sprintf)}
        for a in [0x405d00,0x405d80,0x406910,0x406930,0x406940,0x406950,0x40ed20,0x4aa700]:
            self.callbacks[self.addr(a)]=(0,lambda a=a:self.provider(a))

    def string(self,address):
        result=bytearray()
        while len(result)<1024:
            c=self.read(address+len(result),1)
            if c==b'\0':return bytes(result)
            result+=c
        raise AssertionError('unterminated path')

    def provider(self,address):
        mode,country,stage,low=self.selection
        values={0x405d00:low,0x405d80:mode,0x406910:country,0x406930:stage,
                0x406940:country,0x406950:stage,0x40ed20:HEAP+0x1000,0x4aa700:HEAP+0x2000}
        self.u.reg_write(UC_X86_REG_EAX,values[address])

    def sprintf(self):
        dest,fmt=self.args(2)
        text=self.string(fmt).decode('ascii')
        specs=list(re.finditer(r'%(?:\.([0-9]+))?([sd])',text))
        args=self.args(2+len(specs))[2:]
        for spec,value in reversed(list(zip(specs,args))):
            rendered=self.string(value).decode('ascii') if spec[2]=='s' else str(value).zfill(int(spec[1] or 0))
            text=text[:spec.start()]+rendered+text[spec.end():]
        self.u.mem_write(dest,text.encode('ascii')+b'\0')
        self.u.reg_write(UC_X86_REG_EAX,len(text))

    def run(self,selection):
        self.selection=selection
        self.u.mem_write(self.base,bytes(self.memory))
        self.u.mem_write(HEAP,bytes(0x10000));self.u.mem_write(STACK,bytes(0x10000))
        self.u.mem_write(HEAP+0x1000,b'C:\\CMR2\\GAME\\Tracks\0')
        self.u.mem_write(HEAP+0x2000,b'C:\\CMR2\0')
        sp=STACK+0xff00;self.put(sp,'<I',STOP);self.u.reg_write(UC_X86_REG_ESP,sp)
        self.u.emu_start(self.addr(0x41f560),STOP,count=100000)
        assert self.u.reg_read(UC_X86_REG_EIP)==STOP
        return [self.string(self.addr(a)) for a in [0x53823c,0x538340,0x538130,0x53874c,0x538444,0x538548]]

    def load_texture_path(self, selection, arcade):
        self.run(selection)
        self.texture_path = None
        self.arcade = arcade
        for address,nargs in [(0x49c0a0,2),(0x4a9d70,2),(0x411280,0),
                              (0x407e50,0),(0x406410,1),(0x41f500,0),
                              (0x4074f0,0),(0x4069a0,0),(0x4b23c0,4)]:
            self.callbacks[self.addr(address)]=(nargs*4,
                lambda a=address,n=nargs:self.loader_provider(a,n))
        sp=STACK+0xff00;self.put(sp,'<I',STOP);self.u.reg_write(UC_X86_REG_ESP,sp)
        self.u.emu_start(self.addr(0x41f930),STOP,count=100000)
        assert self.u.reg_read(UC_X86_REG_EIP)==STOP and self.texture_path is not None
        return self.texture_path

    def loader_provider(self,address,nargs):
        if address==0x4b23c0:
            self.texture_path=self.string(self.args(4)[0])
            # Boundary: the loading-screen texture call has received its name.
            self.put(self.u.reg_read(UC_X86_REG_ESP),'<I',STOP)
        self.u.reg_write(UC_X86_REG_EAX,self.arcade if address==0x407e50 else 0)


def main():
    e=json.loads(Path(sys.argv[1]).read_text());a=Paths(ROOT/'cmr2bin/CMR2.exe');b=Paths(Path(sys.argv[2]) if len(sys.argv)>2 else ROOT/'build/CMR2.exe',e)
    selections=list(itertools.product([0,1,2,3,8],range(8),range(11),range(2)))
    selections += [(5,i//3,i%3,low) for i,low in itertools.product(range(8),range(2))]
    for selection in selections:
        aa,bb=a.run(selection),b.run(selection)
        if aa!=bb:
            print('FAIL stage paths',selection,aa,bb);return 1
    for selection,arcade in itertools.product(selections,[0,1]):
        aa,bb=a.load_texture_path(selection,arcade),b.load_texture_path(selection,arcade)
        if aa!=bb:
            print('FAIL loading texture',selection,arcade,aa,bb);return 1
    print(f'{len(selections)*3} stage path cases: all six stage/replay/texture names identical, including Finland stage 1')
    return 0


if __name__=='__main__':sys.exit(main())
