#ifndef _FRONTENDMENUS_H
#define _FRONTENDMENUS_H

#include "Menu.h"

extern Menu g_menu0x0081b158;
extern Menu g_menu0x0081b338;
extern Menu g_menu0x0081b518;
extern Menu g_menu0x0081be78;
extern Menu g_menu0x0081bab8;
extern Menu g_menu0x0081bc98;
extern Menu g_menu0x0081c058;
extern Menu g_menu0x0081c418;
extern Menu g_menu0x0081c5f8;
extern Menu g_menu0x0081c7d8;
extern Menu g_menu0x0081cb98;
extern Menu g_menu0x0081cd78;
extern Menu g_menu0x0081cf58;
extern Menu g_menu0x0081d138;
extern Menu g_menu0x0081d318;
extern Menu g_menu0x0081d4f8;
extern Menu g_menu0x0081d6d8;
extern Menu g_menu0x0081d8b8;
extern Menu g_menu0x0081dc78;
extern Menu g_menu0x0081de58;
extern Menu g_menu0x0081e218;
extern Menu g_menu0x0081e3f8;
extern Menu g_menu0x0081e5d8;
extern Menu g_menu0x0081e998;
extern Menu g_menu0x0081eb78;
extern Menu g_menu0x0081ed58;
extern Menu g_menu0x0081ef38;
extern Menu g_menu0x0081f118;
extern Menu g_menu0x0081f2f8;
extern Menu g_menu0x0081f4d8;
extern Menu g_menu0x0081f6b8;
extern Menu g_menu0x0081fa78;
extern Menu g_menu0x0081fc58;
extern Menu g_menu0x0081fe38;
extern Menu g_menu0x00820018;
extern Menu g_menu0x008201f8;
extern Menu g_menu0x008203d8;
extern Menu g_menu0x008205b8;
extern Menu g_menu0x00820798;
extern Menu g_menu0x00820978;
extern Menu g_menu0x00820b58;
extern Menu g_menu0x00820d38;
extern Menu g_menu0x008210f8;
extern Menu g_menu0x008212d8;
extern Menu g_menu0x008214b8;
extern Menu g_menu0x00821878;
extern Menu g_menu0x00821c38;
extern Menu g_menu0x00821e18;
extern Menu g_menu0x008221d8;
extern Menu g_menu0x008223b8;
extern Menu g_menu0x00822598;
extern Menu g_menu0x00822958;
extern Menu g_menu0x00822d18;
extern Menu g_menu0x00822ef8;
extern Menu g_menu0x008230d8;
extern Menu g_menu0x008232b8;
extern Menu g_menu0x00823498;
extern Menu g_menu0x00823678;
extern Menu g_menu0x00823858;
extern Menu g_menu0x00823a38;
extern Menu g_menu0x00823c18;
extern Menu g_menu0x00823df8;
extern Menu g_menu0x00823fd8;
extern Menu g_menu0x008241b8;
extern Menu g_menu0x00824498;
extern Menu g_menu0x00824678;
extern Menu g_menu0x00824858;
extern Menu g_menu0x00824a38;
extern Menu g_menu0x00824c18;
extern Menu g_menu0x00824df8;
extern Menu g_menu0x00824fd8;
extern Menu g_menu0x008251b8;
extern Menu g_menu0x00826140;
extern Menu g_menu0x00826420;
extern Menu g_menu0x00826600;
extern Menu g_menu0x008269c0;
extern Menu g_menu0x008276e0;
extern Menu g_menu0x008267e0;
extern Menu g_menu0x00826ba0;
extern Menu g_menu0x00826d80;
extern Menu g_menu0x00826f60;
extern Menu g_menu0x00827140;
extern Menu g_menu0x00827320;
extern Menu g_menu0x00827500;
extern Menu g_menu0x008278c0;
extern Menu g_menu0x00827aa0;
extern Menu g_menu0x00827c80;
extern Menu g_menu0x00827e60;
extern Menu g_menu0x00828040;
extern Menu g_menu0x00828220;
extern Menu g_menu0x00828500;
extern Menu g_menu0x008286e0;
extern Menu g_menu0x008288c0;
extern Menu g_menu0x00828aa0;
extern Menu g_menu0x00828c80;
extern Menu g_menu0x00828e60;
extern Menu g_menu0x00829140;

void FrontendMenu_BuildNetworkWaitingRoom(void);
void FrontendMenu_BuildRallyProfileDetails(void);
void FrontendMenu_BuildProfileActions(void);
void FrontendMenu_BuildProfileSettings(void);
void FrontendMenu_BuildProfileRecordsSummary(void);
void FrontendMenu_BuildRallyModes(void);
void FrontendMenu_BuildSingleRallyModes(void);
void FrontendMenu_BuildSingleRallySelection(void);
void FrontendMenu_BuildRallyStartTransition(void);
void FrontendMenu_BuildNetworkConnection(void);
void FrontendMenu_BuildNetworkSessionBrowser(void);
void FrontendMenu_BuildNetworkSessionDetails(void);
void FrontendMenu_BuildNetworkSessionSetup(void);
void FrontendMenu_BuildNetworkStageTimes(void);
void FrontendMenu_BuildGameOptions(void);
void FrontendMenu_BuildGraphicsOptions(void);
void FrontendMenu_BuildAdvancedGraphicsOptions(void);
void FrontendMenu_BuildRenderDeviceOptions(void);
void FrontendMenu_BuildDisplayMode(void);
void FrontendMenu_BuildSoundOptions(void);
void FrontendMenu_BuildRecords(void);
void FrontendMenu_BuildProfileRecords(void);
void FrontendMenu_BuildStageRecords(void);
void FrontendMenu_BuildBestStageTimes(void);
void FrontendMenu_BuildTransmissionRecords(void);
void FrontendMenu_BuildChampionshipRecords(void);
void FrontendMenu_BuildProfileStageRecords(void);
void FrontendMenu_BuildProfileTransmissionRecords(void);
void FrontendMenu_BuildProfileChampionshipRecords(void);
void FrontendMenu_BuildCredits(void);
void FrontendMenu_BuildQuitConfirmation(void);
void FrontendMenu_BuildSingleRallyCarClass(int unused);
void FrontendMenu_BuildChampionshipCarClass(int unused);
void FrontendMenu_BuildTimeTrialCarClass(int unused);
void FrontendMenu_BuildMultiplayerCarClass(void);
void FrontendMenu_BuildMultiplayerStageSelection(void);
void FrontendMenu_BuildProfileNameEntry(void);
void FrontendMenu_BuildProfileRenameEntry(void);
void FrontendMenu_BuildProfileDateEntry(void);
void FrontendMenu_BuildCarSetup(void);
void FrontendMenu_BuildPaletteSelection(void);
void FrontendMenu_BuildPaletteConfirmation(void);
void FrontendMenu_BuildRallySelection(void);
void FrontendMenu_BuildRallyStageSelection(void);
void FrontendMenu_BuildAlternateRallyStageSelection(void);
void FrontendMenu_BuildQuitTransition(void);
Menu *FrontendMenu_GetInitialMenu(BYTE param1);
void FrontendMenu_BuildNetworkPlayerSetup(void);
void FrontendMenu_BuildNetworkCarSetup(void);
void FrontendMenu_BuildNetworkRallySetup(void);
void FrontendMenu_BuildNetworkStageSetup(void);
void FrontendMenu_BuildNetworkExtendedStageSetup(void);
void FrontendMenu_BuildNetworkNameEntry(void);
void FrontendMenu_BuildNetworkLeaderboard(void);
void FrontendMenu_BuildArcadeCarClass(int unused);
void FrontendMenu_BuildChampionshipRouteSelection(void);
void FrontendMenu_BuildChampionshipEntry(void);
void FrontendMenu_BuildAlternateChampionshipRouteSelection(void);
void FrontendMenu_BuildAlternateChampionshipEntry(void);
void FrontendMenu_BuildArcadeChampionshipRouteSelection(void);
void FrontendMenu_BuildArcadeChampionshipEntry(void);
void FrontendMenu_BuildArcadeChampionshipTransmission(void);
void FrontendMenu_BuildArcadeRallySelection(void);
void FrontendMenu_BuildArcadeChampionshipRallySelection(void);

void FrontendDraw_DrawProfileMenu(Menu *pMenu);
void FrontendMenu_DrawProfileActions(Menu *pMenu);
void FrontendMenu_DrawProfileSettings(Menu *pMenu);
void FrontendMenu_DrawProfileRecordsSummary(Menu *pMenu);
void FrontendMenu_DrawCarClass(Menu *pMenu);
void FrontendMenu_DrawMultiplayerCarClass(Menu *pMenu);
void FrontendMenu_DrawMultiplayerStageSelection(Menu *pMenu);
void FrontendMenu_DrawProfileNameEntry(Menu *pMenu);
void FrontendMenu_DrawProfileRenameEntry(Menu *pMenu);
void FrontendMenu_DrawProfileDateEntry(Menu *pMenu);
void FrontendMenu_DrawCarSetup(Menu *pMenu);
void FrontendMenu_DrawSavedStageSelection(Menu *pMenu);
void FrontendMenu_DrawPaletteSelection(Menu *pMenu);
void FrontendMenu_DrawChampionshipEntry(Menu *pMenu);
void FrontendMenu_DrawTimeAttackOptions(Menu *pMenu);
void FrontendMenu_DrawRallySelection(Menu *pMenu);
void FrontendMenu_DrawRallySummary(Menu *pMenu);
void FrontendMenu_DrawAlternateRallyStageSelection(Menu *pMenu);
void FrontendMenu_DrawArcadeChampionshipTransmission(Menu *pMenu);
void FrontendMenu_DrawArcadeRallySelection(Menu *pMenu);
void FrontendMenu_DrawNetworkConnection(Menu *pMenu);
void FrontendMenu_DrawNetworkSessionBrowser(Menu *pMenu);
void FrontendMenu_DrawNetworkSessionDetails(Menu *pMenu);
void FrontendMenu_DrawNetworkSessionSetup(Menu *pMenu);
void FrontendDraw_DrawStageTimes(int unused);
void FrontendMenu_DrawCredits(Menu *pMenu);
void FrontendMenu_DrawGameOptions(Menu *pMenu);
void FrontendMenu_DrawGraphicsOptions(Menu *pMenu);
void FrontendMenu_DrawAdvancedGraphicsOptions(Menu *pMenu);
void FrontendMenu_DrawRenderDeviceOptions(Menu *pMenu);
void FrontendMenu_DrawDisplayMode(Menu *pMenu);
void FrontendMenu_DrawRallyModes(Menu *pMenu);
void FrontendMenu_DrawSingleRallyModes(Menu *pMenu);
void FrontendMenu_DrawSingleRallySelection(Menu *pMenu);
void FrontendMenu_DrawSoundOptions(Menu *pMenu);
void FrontendMenu_DrawQuitConfirmation(Menu *pMenu);
void FrontendMenu_DrawNetworkWaitingRoom(Menu *pMenu);
void FrontendMenu_DrawRecordsRoot(Menu *pMenu);
void FrontendMenu_DrawStageRecords(Menu *pMenu);
void FrontendMenu_DrawProfileStageRecords(Menu *pMenu);
void FrontendMenu_DrawBestStageTimes(Menu *pMenu);
void FrontendMenu_DrawTransmissionRecords(Menu *pMenu);
void FrontendMenu_DrawProfileTransmissionRecords(Menu *pMenu);
void FrontendMenu_DrawChampionshipRecords(Menu *pMenu);
void FrontendMenu_DrawProfileChampionshipRecords(Menu *pMenu);
void FrontendMenu_DrawNetworkPlayerSetup(Menu *pMenu);
void FrontendMenu_DrawNetworkCarSetup(Menu *pMenu);
void FrontendMenu_DrawNetworkRallySetup(Menu *pMenu);
void FrontendMenu_DrawNetworkStageSetup(Menu *pMenu);
void FrontendMenu_DrawNetworkExtendedStageSetup(Menu *pMenu);
void FrontendMenu_DrawNetworkNameEntry(Menu *pMenu);
void FrontendMenu_DrawNetworkLeaderboard(Menu *pMenu);
void FrontendMenu_EnterNetworkConnection(Menu *pMenu, int param);
void FrontendMenu_EnterNetworkSessionBrowser(Menu *pMenu, char param);
void FrontendMenu_UpdateNetworkSessionBrowser(Menu *pMenu);
void FrontendNetwork_JoinSelectedSession(Menu *pMenu, int param);
void FrontendNetwork_CreateSelectedSession(Menu *pMenu, int param);
void FrontendNetwork_OpenConnectedLeaderboard(Menu *pMenu, int param);
void FrontendNetwork_LeaveConnectionPages(Menu *pMenu, char param);
void FrontendMenu_EnterNetworkSessionDetails(Menu *pMenu, char param);
void FrontendMenu_UpdateNetworkSessionDetails(Menu *pMenu);
void FrontendNetwork_ApplyHostSessionDetails(Menu *pMenu, int param);
void FrontendMenu_LeaveNetworkSessionDetails(Menu *pMenu, char param);
void FrontendMenu_EnterNetworkSessionSetup(Menu *pMenu, int param);
void FrontendNetwork_StartHostRace(Menu *pMenu, int param);
void FrontendMenu_UpdateNetworkSessionSetup(Menu *pMenu);
void FrontendMenu_LeaveNetworkSessionSetup(Menu *pMenu, char param);
void FrontendMenu_UpdateNetworkStageTimes(Menu *pMenu);
void FrontendMenu_EnterNetworkPlayerSetup(Menu *pMenu, int param);
void FrontendNetwork_ToggleStageOption(Menu *pMenu, int param);
void FrontendNetwork_ApplyPlayerRoleAndJoin(Menu *pMenu, int param);
void FrontendMenu_UpdateNetworkPlayerSetup(Menu *pMenu);
void FrontendMenu_EnterNetworkCarSetup(Menu *pMenu, int param);
void FrontendNetwork_ApplyRallyAndJoin(Menu *pMenu, int param);
void FrontendMenu_UpdateNetworkCarSetup(Menu *pMenu);
void FrontendMenu_EnterNetworkRallySetup(Menu *pMenu, int param);
void FrontendNetwork_ApplyTwoPlayerRally(Menu *pMenu, int param);
void FrontendMenu_UpdateNetworkRallySetup(Menu *pMenu);
void FrontendMenu_EnterNetworkStageSetup(Menu *pMenu, int param);
void FrontendNetwork_ApplySinglePlayerRally(Menu *pMenu, int param);
void FrontendMenu_EnterNetworkExtendedStageSetup(Menu *pMenu, char param);
void FrontendNetwork_PumpMenuMessages(Menu *pMenu);
void FrontendNetwork_ApplyChampionshipRally(Menu *pMenu, int param);
void FrontendMenu_EnterNetworkNameEntry(Menu *pMenu, int param);
void FrontendMenu_UpdateNetworkNameEntry(Menu *pMenu);
void FrontendNetwork_JoinNamedSession(Menu *pMenu, int param);
void FrontendMenu_EnterNetworkLeaderboard(Menu *pMenu, int param);
void FrontendLeaderboard_SelectEntry(Menu *pMenu, int param);
void FrontendLeaderboard_AddEntry(Menu *pMenu, int param);
void FrontendLeaderboard_RefreshSelection(Menu *pMenu, int param);
void FrontendMenu_UpdateNetworkLeaderboard(Menu *pMenu);
void FrontendMenu_EnterSingleRallySelection(Menu *pMenu, int param);
void FrontendMenu_UpdateSingleRallySelection(Menu *pMenu);
void FrontendMenu_UpdateRallyStartTransition(Menu *pMenu);
void FrontendMenu_UpdateQuitTransition(Menu *pMenu);
void FrontendMenu_EnterRallyModes(Menu *pMenu, int param);
void FrontendMenu_LeaveRallyModes(Menu *pMenu, int param);
void FrontendMenu_EnterCarClass(Menu *pMenu, int param);
void FrontendMenu_SelectCarClass(Menu *pMenu, int param);
void FrontendMenu_EnterMultiplayerCarClass(Menu *pMenu, int param);
void FrontendMenu_SelectMultiplayerClass(Menu *pMenu, int param);
void FrontendMenu_UpdateRallySelection(Menu *pMenu);
void FrontendMenu_EnableRallyStageRows(Menu *pMenu, int param);
void FrontendMenu_UpdateRallyStageSelection(Menu *pMenu);
void FrontendMenu_UpdateAlternateRallyStageSelection(Menu *pMenu);
void FrontendMenu_SelectRallyStage(Menu *pMenu, int param);
void FrontendMenu_SelectAlternateRallyStage(Menu *pMenu, MenuItem *pItem);
void FrontendMenu_EnterMultiplayerStageSelection(Menu *pMenu, int param);
void FrontendMenu_LeaveMultiplayerStageSelection(Menu *pMenu, int param);
void FrontendMenu_UpdateMultiplayerStageSelection(Menu *pMenu);
void FrontendProfile_ApplyStageSelectionAndAdvance(Menu *pMenu, int param);
void FrontendMenu_EnterProfileNameEntry(Menu *pMenu, char param);
void FrontendMenu_LeaveProfileNameEntry(int param1, char param2);
void FrontendMenu_LeaveProfileRenameEntry(Menu *pMenu, int param);
void FrontendMenu_UpdateProfileNameEntry(Menu *pMenu);
void FrontendProfile_PickNameCharacter(Menu *pMenu, int param);
void FrontendMenu_EnterProfileRenameEntry(Menu *pMenu, char param);
void FrontendMenu_UpdateProfileRenameEntry(Menu *pMenu);
void FrontendProfile_PickRenameCharacterOrCheat(Menu *pMenu, int param);
void FrontendProfile_ApplyDateEntry(Menu *pMenu, int param);
void FrontendMenu_UpdateProfileDateEntry(Menu *pMenu);
void FrontendProfile_FillColourPicker(Menu *pMenu, int param);
void FrontendScroller_InitRallyStageSelection(Menu *pMenu, int param);
void FrontendMenu_EnterPaletteSelection(Menu *pMenu, char param);
void FrontendMenu_EnterPaletteConfirmation(Menu *pMenu, int param);
void FrontendProfile_SelectPalette(Menu *pMenu, int param);
void FrontendProfile_OpenPaletteEditor(Menu *pMenu, int param);
void FrontendChampionship_ToggleAndAdvanceEntry(Menu *pMenu, int param);
void FrontendMenu_ClearOverlayMode(Menu *pMenu, int param);
void FrontendMenu_EnterCredits(Menu *pMenu, int param);
void FrontendMenu_EnterGraphicsOptions(Menu *pMenu, int param);
void FrontendMenu_EnterAdvancedGraphicsOptions(Menu *pMenu, int param);
void FrontendMenu_UpdateAdvancedGraphicsOptions(Menu *pMenu);
void FrontendMenu_ApplyAdvancedGraphicsOptions(Menu *pMenu, int param);
void FrontendMenu_ApplyGraphicsOptions(Menu *pMenu, int param);
void FrontendMenu_LeaveGraphicsOptions(Menu *pMenu, char param);
void FrontendMenu_EnterRenderDeviceOptions(Menu *pMenu, int param);
void FrontendMenu_ApplyRenderDeviceOptions(Menu *pMenu, int param);
void FrontendMenu_EnterDisplayMode(BYTE *p, int param2);
void FrontendMenu_UpdateDisplayMode(Menu *pMenu);
void FrontendMenu_ApplyDisplayMode(Menu *pMenu, int param);
void FrontendMenu_EnterSoundOptions(Menu *pMenu, int param);
void FrontendMenu_UpdateSoundOptions(BYTE *p);
void FrontendMenu_LeaveSoundOptions(Menu *pMenu, char param);
void FrontendMenu_EnterGameOptions(Menu *pMenu, char param);
void FrontendMenu_ApplyGameOptions(Menu *pMenu, int param);
void FrontendScroller_InitStageRecords(Menu *pMenu, int param);
void FrontendScroller_InitBestStageTimes(Menu *pMenu, int param);
void FrontendScroller_InitTransmissionRecords(Menu *pMenu, int param);
void FrontendMenu_EnterRallyStageSelection(Menu *pMenu, int param);
void FrontendMenu_EnterAlternateRallyStageSelection(Menu *pMenu, int param);
void FrontendMenu_EnterRallySelection(Menu *pMenu, int param);
void FrontendScroller_UpdateStageRecords(Menu *pMenu);
void FrontendScroller_UpdateBestStageTimes(Menu *pMenu);
void FrontendScroller_UpdateTransmissionRecords(Menu *pMenu);
void FrontendScroller_UpdateChampionshipEntry(Menu *pMenu);
void FrontendCar_ApplyPreviewSelection(Menu *pMenu, int param);
void FrontendRecords_ResetCarouselSelection(Menu *pMenu, int param);
void FrontendRecords_CycleTableMode(Menu *pMenu, int param);
void FrontendMenu_EnterProfileActions(Menu *pMenu, char param);
void FrontendScroller_UpdateMain(Menu *pMenu);
void FrontendMenu_EnterQuitConfirmation(Menu *pMenu, int param);
void FrontendMenu_CancelQuit(Menu *pMenu, int param);
void FrontendMenu_LeaveQuitConfirmation(Menu *pMenu, char param);
void FrontendMenu_EnterArcadeCarClass(Menu *pMenu, int param);
void FrontendMenu_InitRouteScroller(Menu *pMenu, int param);
void FrontendMenu_UpdateChampionshipEntry(Menu *pMenu, char param);
void FrontendChampionship_SelectRouteEntry(Menu *pMenu, int param);
void FrontendChampionship_ToggleRouteEntry(Menu *pMenu, int param);
void FrontendChampionship_UpdateAlternateRouteEntry(Menu *pMenu, int param);
void FrontendChampionship_ApplySharedRouteEntry(Menu *pMenu, int param);
void FrontendChampionship_UpdateArcadeRouteEntry(Menu *pMenu, int param);
void FrontendChampionship_ToggleArcadeRouteEntry(Menu *pMenu, int param);
void FrontendMenu_EnterArcadeChampionshipTransmission(Menu *pMenu, int param);
void FrontendMenu_UpdateArcadeChampionshipTransmission(Menu *pMenu);
void FrontendMenu_SelectArcadeChampionshipTransmission(Menu *pMenu, int param);
void FrontendScroller_InitArcadeRally(Menu *pMenu, int param);
void FrontendScroller_UpdateArcadeRally(Menu *pMenu);
void FrontendMenu_SelectArcadeRallyRow(int param_1, int unused);

extern int g_unk0x00819128;
unsigned int RallyData_GetSelectionBits10To11(void);
void RallyData_SetSelectionBits12To13(BYTE param1);
int Network_CloseSession(void);
BOOL Network_GetSessionStateFlag(void);
void Frontend_SetOverlayMode(int param1);
void GameInfo_SetConfiguredGameMode(BYTE param1);
void GameInfo_SetGameModeOptionBits20To22(BYTE param1);
void GameInfo_GetPlayerOptionNibbles(int *pOut1, int *pOut2);
int SavedGames_GetCount(void);
Menu *FrontendMenu_GetRallyStartTransition(void);
Menu *FrontendMenu_GetQuitTransition(void);
Menu *FrontendMenu_GetArcadeChampionshipTransmission(void);

// Horizontal menu whose items slide sideways when the cursor moves
struct MenuScroller {
    int offset;         // 0x0  current scroll position in pixels
    int startOffset;    // 0x4  position when the slide started
    int count;          // 0x8  number of items
    int widths[22];     // 0xc  text width of each item
    int spacing;        // 0x64 gap between items, 24 pixels at 640 wide
    int current;        // 0x68 cursor the scroller is sliding to, -1 = none
    int previous;       // 0x6c
    int startTime;      // 0x70
    Menu *pMenu;        // 0x74
};

extern MenuScroller g_menuScrollers[12];
#define g_menuScroller0x00819140 g_menuScrollers[0]
#define g_menuScroller0x008191b8 g_menuScrollers[1]
#define g_menuScroller0x00819230 g_menuScrollers[2]
#define g_menuScroller0x008192a8 g_menuScrollers[3]
#define g_menuScroller0x00819320 g_menuScrollers[4]
#define g_menuScroller0x00819398 g_menuScrollers[5]
#define g_menuScroller0x00819410 g_menuScrollers[6]
#define g_menuScroller0x00819488 g_menuScrollers[7]
#define g_menuScroller0x00819500 g_menuScrollers[8]
#define g_menuScroller0x00819578 g_menuScrollers[9]
#define g_menuScroller0x008195f0 g_menuScrollers[10]
#define g_menuScroller0x00819668 g_menuScrollers[11]
int GameInfo_GetSessionField397C(void);
void GameInfo_SetSessionField398C(int param1);
void RallyData_SetCountrySelectionBits(BYTE param1);
void RallyData_SetDriverPairingStateValues(int param1, int param2);
void Input_ClearCharacterQueue(void);
bool Input_PopQueuedCharacter(int *pOut);
void NetworkChat_ClearLog(void);
BYTE FrontendRecords_GetProfileMode(void);
int Frontend_GetOverlayMode(void);
int Profile_GetFileCount(void);
void FrontendScroller_GetSelectionAndTimestamp(int *pOut1, int *pOut2);
BYTE FrontendProfile_GetPlayersRemaining(void);
void FrontendMenu_ApplyGraphicsOptions(Menu *pMenu, int param);
MenuScroller *FrontendScroller_GetMainScroller(void);
MenuScroller *FrontendScroller_GetRouteEntryScroller(void);
MenuScroller *FrontendScroller_GetLanguageScroller(void);
MenuScroller *FrontendScroller_GetDifficultyScroller(void);
MenuScroller *FrontendScroller_GetRallySelectionScroller(void);
MenuScroller *FrontendScroller_GetStageRecordsScroller(void);
MenuScroller *FrontendScroller_GetBestStageTimesScroller(void);
MenuScroller *FrontendScroller_GetTransmissionRecordsScroller(void);
MenuScroller *FrontendScroller_GetDisplayDeviceScroller(void);
MenuScroller *FrontendScroller_GetAlternateStageScroller(void);
MenuScroller *FrontendScroller_GetArcadeRallyScroller(void);
int FrontendCredits_GetScrollOffset(void);
int FrontendProfile_GetCurrentPlayer(void);
void FrontendScroller_UpdateCursorSlide(MenuScroller *p);
int FrontendRecords_GetTableMode(void);
Menu *FrontendMenu_GetMultiplayerProfile(void);
Menu *FrontendMenu_GetMain(void);
Menu *FrontendMenu_GetNetworkSessionBrowser(void);
Menu *FrontendMenu_GetNetworkSessionSetup(void);
extern BYTE g_unk0x00818848;
int GameInfo_GetSessionField3984(void);
Menu *FrontendMenu_GetOptions(void);
Menu *FrontendMenu_GetLanguage(void);
Menu *FrontendMenu_GetSingleRallyDifficulty(void);
Menu *FrontendMenu_GetChampionshipDifficulty(void);
Menu *FrontendMenu_GetTimeTrialDifficulty(void);
Menu *FrontendMenu_GetMultiplayerDifficulty(void);
Menu *FrontendMenu_GetMultiplayerExtendedDifficulty(void);
Menu *FrontendMenu_GetRallySelection(void);
Menu *FrontendMenu_GetRallyStageSelection(void);
Menu *FrontendMenu_GetAlternateRallyStageSelection(void);
Menu *FrontendMenu_GetSingleRallyTransmission(void);
Menu *FrontendMenu_GetChampionshipTransmission(void);
Menu *FrontendMenu_GetTimeTrialTransmission(void);
Menu *FrontendMenu_GetMultiplayerStageSelection(void);
Menu *FrontendMenu_GetProfileNameEntry(void);
Menu *FrontendMenu_GetProfileRenameEntry(void);
Menu *FrontendMenu_GetProfileDateEntry(void);
Menu *FrontendMenu_GetCarSetup(void);
Menu *FrontendMenu_GetPaletteSelection(void);
Menu *FrontendMenu_GetMultiplayerRaceSettings(void);
Menu *FrontendMenu_GetPaletteConfirmation(void);
Menu *FrontendMenu_GetNetworkConnection(void);
Menu *FrontendMenu_GetNetworkSessionDetails(void);
Menu *FrontendMenu_GetRallyProfile(void);
Menu *FrontendMenu_GetProfileActions(void);
Menu *FrontendMenu_GetRallyModes(void);
Menu *FrontendMenu_GetNetworkPlayerSetup(void);
Menu *FrontendMenu_GetNetworkCarSetup(void);
Menu *FrontendMenu_GetNetworkRallySetup(void);
Menu *FrontendMenu_GetNetworkStageSetup(void);
Menu *FrontendMenu_GetNetworkExtendedStageSetup(void);
Menu *FrontendMenu_GetNetworkNameEntry(void);
Menu *FrontendMenu_GetNetworkStageTimes(void);
Menu *FrontendMenu_GetNetworkMessage(void);
Menu *FrontendMenu_GetArcade(void);
Menu *FrontendMenu_GetArcadeGameType(void);
Menu *FrontendMenu_GetArcadeCarClass(void);
Menu *FrontendMenu_GetChampionshipRouteSelection(void);
Menu *FrontendMenu_GetAlternateChampionshipRouteSelection(void);
Menu *FrontendMenu_GetArcadeChampionshipRouteSelection(void);
Menu *FrontendMenu_GetArcadeRallySelection(void);
Menu *FrontendMenu_GetArcadeChampionshipRallySelection(void);
Menu *FrontendMenu_GetQuickRaceSettings(void);
Menu *FrontendMenu_GetQuickRaceAdvancedSettings(void);
Menu *FrontendMenu_GetControls(void);
Menu *FrontendMenu_GetDeviceCalibration(void);
Menu *FrontendMenu_GetDeviceBindings(void);
Menu *FrontendMenu_GetPadSettings(void);
Menu *FrontendMenu_GetDeviceConfiguration(void);

#endif
