#include <windows.h>
#include "Car.h"
#include "CarResources.h"
#include "CarPhysics.h"
#include "Game.h"
#include "CarParts.h"
#include "OptionPreviewGeometry.h"
#include "StageTiming.h"
#include "StageWeather.h"
#include "Stage.h"
#include "StageBlock.h"
#include "CarLightState.h"
#include "Glow.h"
#include "CarExhaust.h"
#include <stddef.h>

// Preserve the original Win32 layouts used by array indexing, bulk copies
// and packed callback tables. Keep these checks out of shared headers:
// extra declarations there can alter MSVC6 code generation in unrelated TUs.
typedef char CarSizeCheck[sizeof(Car) == 0xc24 ? 1 : -1];
typedef char CarPositionOffsetCheck[offsetof(Car, position) == 0x2d0 ? 1 : -1];
typedef char CarWheelNodesOffsetCheck[offsetof(Car, pWheelNodes) == 0x738 ? 1 : -1];
typedef char CarWheelLoadOffsetCheck[offsetof(Car, wheelLoad) == 0x860 ? 1 : -1];
typedef char CarIndexOffsetCheck[offsetof(Car, index) == 0xb1a ? 1 : -1];
typedef char CarCameraRejectionOffsetCheck[offsetof(Car, firstCameraBlocked) == 0xb68 ? 1 : -1];
typedef char CarRemoteFlagOffsetCheck[offsetof(Car, field_0xc1c) == 0xc1c ? 1 : -1];
typedef char CallbackStateRecordSizeCheck[sizeof(CallbackStateRecord) == 8 ? 1 : -1];
typedef char CallbackStateTimerOffsetCheck[offsetof(CallbackStateRecord, elapsedTicks) == 4 ? 1 : -1];
typedef char StateCallbackPairSizeCheck[sizeof(StateCallbackPair) == 8 ? 1 : -1];
typedef char CallbackStateMachineSizeCheck[sizeof(CallbackStateMachine) == 0x10 ? 1 : -1];
typedef char CallbackStateRecordsOffsetCheck[offsetof(CallbackStateMachine, records) == 4 ? 1 : -1];
typedef char CallbackStateRulesOffsetCheck[offsetof(CallbackStateMachine, rules) == 0xc ? 1 : -1];
typedef char SessionPlayerRecordSizeCheck[sizeof(SessionPlayerRecord) == 0xd0 ? 1 : -1];
typedef char CarPartSetSizeCheck[sizeof(CarPartSet) == 0x4d0 ? 1 : -1];
typedef char CarPartDamageValuesCheck[offsetof(CarPartSet, damageValues) == 0x240 ? 1 : -1];
typedef char CarPartDamageScalesCheck[offsetof(CarPartSet, damageScales) == 0x2c8 ? 1 : -1];
typedef char CarPartDamageBiasesCheck[offsetof(CarPartSet, damageBiases) == 0x350 ? 1 : -1];
typedef char CarPartWobbleCheck[offsetof(CarPartSet, steeringWobble) == 0x3d8 ? 1 : -1];
typedef char CarPartSuspensionCheck[offsetof(CarPartSet, suspensionDamageOffset) == 0x3dc ? 1 : -1];
typedef char CarPartWheelDragCheck[offsetof(CarPartSet, wheelDamageDrag) == 0x3ec ? 1 : -1];
typedef char CarPartFrontBrakeCheck[offsetof(CarPartSet, frontBrakeScale) == 0x3fc ? 1 : -1];
typedef char CarPartRearBrakeCheck[offsetof(CarPartSet, rearBrakeScale) == 0x400 ? 1 : -1];
typedef char CarPartEngineTorqueCheck[offsetof(CarPartSet, engineTorqueScale) == 0x404 ? 1 : -1];
typedef char CarPartBodyDragCheck[offsetof(CarPartSet, bodyDamageDrag) == 0x408 ? 1 : -1];
typedef char CarPartBoundsCheck[offsetof(CarPartSet, maxX) == 0x410 ? 1 : -1];
typedef char CarPartBreakIndicesCheck[offsetof(CarPartSet, breakPartIndex) == 0x460 ? 1 : -1];
typedef char CarPartGearDamageCheck[offsetof(CarPartSet, gearShiftDamage) == 0x468 ? 1 : -1];
typedef char CarPartGlassCooldownCheck[offsetof(CarPartSet, glassCooldown) == 0x469 ? 1 : -1];
typedef char CarPartGlassEmittedCheck[offsetof(CarPartSet, glassDebrisEmitted) == 0x46c ? 1 : -1];
typedef char CarPartDamagedCheck[offsetof(CarPartSet, partDamaged) == 0x470 ? 1 : -1];
typedef char CarPartBrokenCheck[offsetof(CarPartSet, partBroken) == 0x490 ? 1 : -1];
typedef char CarPartStateSizeCheck[sizeof(PartState) == 0x1a0 ? 1 : -1];
typedef char CarPartPrevMatrixCheck[offsetof(PartState, prevMatrix) == 0x4c ? 1 : -1];
typedef char CarPartDrawMatrixCheck[offsetof(PartState, drawMatrix) == 0x8c ? 1 : -1];
typedef char CarPartUpdateCheck[offsetof(PartState, update) == 0x110 ? 1 : -1];
typedef char CarPartFlagsCheck[offsetof(PartState, flags) == 0x150 ? 1 : -1];
typedef char CarPartStateTablesCheck[sizeof(CarPartStateTables) == 0x14 ? 1 : -1];
typedef char CarPartStateModesCheck[offsetof(CarPartStateTables, modes) == 0x10 ? 1 : -1];
typedef char CarDamageRecordSizeCheck[sizeof(CarDamageRecord) == 0x290 ? 1 : -1];
typedef char CarLineDescriptorSizeCheck[sizeof(CarFlexibleLineDescriptor) == 0x20 ? 1 : -1];
typedef char CarLineAxisCheck[offsetof(CarFlexibleLineDescriptor, axis) == 0xc ? 1 : -1];
typedef char CarLineLengthCheck[offsetof(CarFlexibleLineDescriptor, length) == 0x18 ? 1 : -1];
typedef char CarLineColourCheck[offsetof(CarFlexibleLineDescriptor, colour) == 0x1c ? 1 : -1];
typedef char CarLineStateSizeCheck[sizeof(CarFlexibleLineState) == 0x3c ? 1 : -1];
typedef char CarLineStateAllocationCheck[3 * sizeof(CarFlexibleLineState) == 0xb4 ? 1 : -1];
typedef char CarLinePreviousCheck[offsetof(CarFlexibleLineState, previousPosition) == 0xc ? 1 : -1];
typedef char CarLineDrawCheck[offsetof(CarFlexibleLineState, drawPosition) == 0x18 ? 1 : -1];
typedef char CarLineEndCheck[offsetof(CarFlexibleLineState, groundEnd) == 0x24 ? 1 : -1];
typedef char CarLineVelocityXCheck[offsetof(CarFlexibleLineState, velocityX) == 0x30 ? 1 : -1];
typedef char CarLineVelocityZCheck[offsetof(CarFlexibleLineState, velocityZ) == 0x34 ? 1 : -1];
typedef char CarLineGroundedCheck[offsetof(CarFlexibleLineState, grounded) == 0x38 ? 1 : -1];
typedef char SceneNodeSizeCheck[sizeof(SceneNode) == 0x18c ? 1 : -1];
typedef char SceneNodeViewMaskCheck[offsetof(SceneNode, viewMask) == 0x17c ? 1 : -1];
typedef char CarPartHiddenCheck[offsetof(CarPartSet, partHidden) == 0x4b0 ? 1 : -1];
typedef char CarLineGroundFlagsCheck[offsetof(CarPartSet, lineGrounded) == 0x4c0 ? 1 : -1];
typedef char CarPartRadiusCheck[offsetof(PartState, boundsRadius) == 0x15c ? 1 : -1];
typedef char CarDamageLinkSizeCheck[sizeof(CarDamageLink) == 0xd ? 1 : -1];
typedef char CarDamageLinkPoolSizeCheck[sizeof(CarDamageLinkPool) == 0x106 ? 1 : -1];
typedef char CarDamageLinkCountCheck[offsetof(CarDamageLinkPool, count) == 0x104 ? 1 : -1];
typedef char CarDamageFirstLinkCheck[offsetof(CarDamageLinkPool, firstLink) == 0x105 ? 1 : -1];
typedef char CarDamageSnapshotSizeCheck[sizeof(CarDamageSnapshot) == 0x40 ? 1 : -1];
typedef char CarDamageHiddenCheck[offsetof(CarDamageSnapshot, partHidden) == 0x24 ? 1 : -1];
typedef char CarDamageGroundFlagsCheck[offsetof(CarDamageSnapshot, lineGrounded) == 0x34 ? 1 : -1];
typedef char CarDamageStageImpactsCheck[offsetof(CarDamageRecord, stageImpacts) == 0x106 ? 1 : -1];
typedef char CarDamageActiveStateCheck[offsetof(CarDamageRecord, damage) == 0x20c ? 1 : -1];
typedef char CarDamageStageStateCheck[offsetof(CarDamageRecord, stageDamage) == 0x24c ? 1 : -1];
typedef char CarDamageStageCapturedCheck[offsetof(CarDamageRecord, stageSnapshotCaptured) == 0x28c ? 1 : -1];

// Motor, controls and gearbox fields recovered from readers and writers.
typedef char CarRecovered_collisionRadius[offsetof(Car, collisionRadius) == 0x758 ? 1 : -1];
typedef char CarRecovered_mass[offsetof(Car, mass) == 0x75c ? 1 : -1];
typedef char CarRecovered_inverseMass[offsetof(Car, inverseMass) == 0x760 ? 1 : -1];
typedef char CarRecovered_engineNetTorque[offsetof(Car, engineNetTorque) == 0x780 ? 1 : -1];
typedef char CarRecovered_engineDragCoefficient[offsetof(Car, engineDragCoefficient) == 0x784 ? 1 : -1];
typedef char CarRecovered_maxThrottleTorque[offsetof(Car, maxThrottleTorque) == 0x788 ? 1 : -1];
typedef char CarRecovered_baseThrottleTorque[offsetof(Car, baseThrottleTorque) == 0x78c ? 1 : -1];
typedef char CarRecovered_throttleRampStep[offsetof(Car, throttleRampStep) == 0x790 ? 1 : -1];
typedef char CarRecovered_engineSpeedLimit[offsetof(Car, engineSpeedLimit) == 0x794 ? 1 : -1];
typedef char CarRecovered_throttleTorque[offsetof(Car, throttleTorque) == 0x79c ? 1 : -1];
typedef char CarRecovered_throttlePhase[offsetof(Car, throttlePhase) == 0x7a0 ? 1 : -1];
typedef char CarRecovered_engineSpeed[offsetof(Car, engineSpeed) == 0x7a4 ? 1 : -1];
typedef char CarRecovered_revLimiterTorque[offsetof(Car, revLimiterTorque) == 0x7b0 ? 1 : -1];
typedef char CarRecovered_baseDriveSplit[offsetof(Car, baseDriveSplit) == 0x7b8 ? 1 : -1];
typedef char CarRecovered_gearRatio[offsetof(Car, gearRatio) == 0x7bc ? 1 : -1];
typedef char CarRecovered_steeringInput[offsetof(Car, steeringInput) == 0x818 ? 1 : -1];
typedef char CarRecovered_steeringTorqueScale[offsetof(Car, steeringTorqueScale) == 0x824 ? 1 : -1];
typedef char CarRecovered_steeringSpeedScale[offsetof(Car, steeringSpeedScale) == 0x828 ? 1 : -1];
typedef char CarRecovered_maxBrakeForce[offsetof(Car, maxBrakeForce) == 0x82c ? 1 : -1];
typedef char CarRecovered_brakeRampStep[offsetof(Car, brakeRampStep) == 0x834 ? 1 : -1];
typedef char CarRecovered_brakePhase[offsetof(Car, brakePhase) == 0x83c ? 1 : -1];
typedef char CarRecovered_handbrakeRampStep[offsetof(Car, handbrakeRampStep) == 0x840 ? 1 : -1];
typedef char CarRecovered_maxHandbrakeForce[offsetof(Car, maxHandbrakeForce) == 0x844 ? 1 : -1];
typedef char CarRecovered_handbrakePhase[offsetof(Car, handbrakePhase) == 0x84c ? 1 : -1];
typedef char CarRecovered_wheelSpinForWheelLean[offsetof(Car, wheelSpinForWheelLean) == 0x890 ? 1 : -1];
typedef char CarRecovered_wheelSpinForBodyLean[offsetof(Car, wheelSpinForBodyLean) == 0x8a0 ? 1 : -1];
typedef char CarRecovered_groundHeightCorrection[offsetof(Car, groundHeightCorrection) == 0x958 ? 1 : -1];
typedef char CarRecovered_wheelLeanDamping[offsetof(Car, wheelLeanDamping) == 0x9b8 ? 1 : -1];
typedef char CarRecovered_bodyLeanDamping[offsetof(Car, bodyLeanDamping) == 0x9bc ? 1 : -1];
typedef char CarRecovered_cheatWheelDrop[offsetof(Car, cheatWheelDrop) == 0xa88 ? 1 : -1];
typedef char CarRecovered_cheatBodyLift[offsetof(Car, cheatBodyLift) == 0xa8c ? 1 : -1];
typedef char CarRecovered_previousWheelSurface[offsetof(Car, previousWheelSurface) == 0xabe ? 1 : -1];
typedef char CarRecovered_engineStartTimer[offsetof(Car, engineStartTimer) == 0xafe ? 1 : -1];
typedef char CarRecovered_requestedGear[offsetof(Car, requestedGear) == 0xb20 ? 1 : -1];
typedef char CarRecovered_autoShiftDelay[offsetof(Car, autoShiftDelay) == 0xb21 ? 1 : -1];
typedef char CarRecovered_lastShiftDirection[offsetof(Car, lastShiftDirection) == 0xb22 ? 1 : -1];
typedef char CarRecovered_damageShiftDelay[offsetof(Car, damageShiftDelay) == 0xb24 ? 1 : -1];
typedef char CarRecovered_engineRestartPending[offsetof(Car, engineRestartPending) == 0xb4c ? 1 : -1];
typedef char CarRecovered_braking[offsetof(Car, braking) == 0xb54 ? 1 : -1];
typedef char CarRecovered_reversing[offsetof(Car, reversing) == 0xb5c ? 1 : -1];
typedef char CarRecovered_revLimiterActive[offsetof(Car, revLimiterActive) == 0xb78 ? 1 : -1];
typedef char CarRecovered_shiftInProgress[offsetof(Car, shiftInProgress) == 0xb84 ? 1 : -1];
typedef char CarRecovered_automaticReverse[offsetof(Car, automaticReverse) == 0xb94 ? 1 : -1];
typedef char CarRecovered_gearAtOrBelowBest[offsetof(Car, gearAtOrBelowBest) == 0xb98 ? 1 : -1];
typedef char CarRecovered_automaticGearbox[offsetof(Car, automaticGearbox) == 0xb9c ? 1 : -1];
typedef char CarRecovered_useUpperCollisionCorners[offsetof(Car, useUpperCollisionCorners) == 0xc00 ? 1 : -1];
typedef char CarRecovered_bodySize[offsetof(Car, bodySize) == 0x1f8 ? 1 : -1];
typedef char CarRecovered_upperCornersLocal[offsetof(Car, upperCornersLocal) == 0x240 ? 1 : -1];
typedef char CarRecovered_groundRightDot[offsetof(Car, groundRightDot) == 0x91c ? 1 : -1];
typedef char CarRecovered_groundUpDot[offsetof(Car, groundUpDot) == 0x920 ? 1 : -1];
typedef char CarRecovered_groundForwardDot[offsetof(Car, groundForwardDot) == 0x924 ? 1 : -1];
typedef char CarRecovered_deepestCorner[offsetof(Car, deepestCorner) == 0xb2b ? 1 : -1];
typedef char CarRecovered_firstCameraBlocked[offsetof(Car, firstCameraBlocked) == 0xb68 ? 1 : -1];
typedef char CarRecovered_steeringAccumulator[offsetof(Car, steeringAccumulator) == 0x81c ? 1 : -1];
typedef char CarRecovered_steeringReturnRate[offsetof(Car, steeringReturnRate) == 0x820 ? 1 : -1];
typedef char CarRecovered_wheelSteeringAngle[offsetof(Car, wheelSteeringAngle) == 0xb10 ? 1 : -1];
typedef char CarRecovered_targetSteeringAngle[offsetof(Car, targetSteeringAngle) == 0xb12 ? 1 : -1];
typedef char CarRecovered_renderSteeringAngle[offsetof(Car, renderSteeringAngle) == 0xb14 ? 1 : -1];
typedef char CarRecovered_maxSteeringAngleDegrees[offsetof(Car, maxSteeringAngleDegrees) == 0xb16 ? 1 : -1];
typedef char CarNetRecordSizeCheck[sizeof(CarNetRecord) == 0xec ? 1 : -1];
typedef char CarNetSteeringCheck[offsetof(CarNetRecord, wheelSteeringAngle) == 0xc4 ? 1 : -1];
typedef char CarNetThrottleCheck[offsetof(CarNetRecord, throttleTorque) == 0xb8 ? 1 : -1];
typedef char CarNetBrakingCheck[offsetof(CarNetRecord, braking) == 0xd0 ? 1 : -1];
typedef char CarNetUpperCornersCheck[offsetof(CarNetRecord, useUpperCollisionCorners) == 0xd4 ? 1 : -1];

// Typed render snapshots and the four 0x18-byte wheel records they contain.
typedef char CarWheelRecordSizeCheck[sizeof(CarWheelRecord) == 0x18 ? 1 : -1];
typedef char CarWheelTiltOffsetCheck[offsetof(CarWheelRecord, tiltDegrees) == 0xc ? 1 : -1];
typedef char CarWheelSteeringOffsetCheck[offsetof(CarWheelRecord, steeringDegrees) == 0x10 ? 1 : -1];
typedef char CarWheelSpinOffsetCheck[offsetof(CarWheelRecord, spinDegrees) == 0x14 ? 1 : -1];
typedef char CarTransformsSizeCheck[sizeof(CarTransforms) == 0xfc ? 1 : -1];
typedef char CarTransformsBody2Check[offsetof(CarTransforms, body2) == 0x40 ? 1 : -1];
typedef char CarTransformsWheelsCheck[offsetof(CarTransforms, wheels) == 0x80 ? 1 : -1];
typedef char CarTransformsNormalCheck[offsetof(CarTransforms, groundNormal) == 0xe0 ? 1 : -1];
typedef char CarTransformsHeightsCheck[offsetof(CarTransforms, cornerHeight) == 0xec ? 1 : -1];
typedef char CarRenderBoxStrideCheck[8 * sizeof(FixVector) == 0x60 ? 1 : -1];

typedef char CarSimulationInterpolationCheck[offsetof(Car, simulationInterpolation) == 0xa90 ? 1 : -1];
typedef char CarSimulationRateCheck[offsetof(Car, simulationRateHz) == 0xa98 ? 1 : -1];
typedef char CarSimulationStepsCheck[offsetof(Car, simulationStepsRemaining) == 0xb43 ? 1 : -1];

// Car contact patches, shadows and skid range flags.
typedef char CarContactSizeCheck[sizeof(CarContact) == 0x2a4 ? 1 : -1];
typedef char CarContactFrontMidCheck[offsetof(CarContact, wheelFrontMid) == 0x198 ? 1 : -1];
typedef char CarContactRearMidCheck[offsetof(CarContact, wheelRearMid) == 0x1c8 ? 1 : -1];
typedef char CarContactShadowCheck[offsetof(CarContact, shadowLevel) == 0x250 ? 1 : -1];
typedef char CarContactGhostCheck[offsetof(CarContact, ghostContact) == 0x294 ? 1 : -1];
typedef char CarContactWheelsCheck[offsetof(CarContact, wheelPatchesEnabled) == 0x298 ? 1 : -1];
typedef char CarContactSkidOffsetCheck[offsetof(CarContact, skidIndexOffset) == 0x29c ? 1 : -1];
typedef char CarContactSkidDirectionCheck[offsetof(CarContact, skidRangeAscending) == 0x2a0 ? 1 : -1];

// Scene records and the composite stage-car resource block.
typedef char CarSceneRecordSizeCheck[sizeof(CarSceneRecord) == 0x24 ? 1 : -1];
typedef char CarSceneRecord_bodyNodeCheck[offsetof(CarSceneRecord, bodyNode) == 0x4 ? 1 : -1];
typedef char CarSceneRecord_rootNodeCheck[offsetof(CarSceneRecord, rootNode) == 0x8 ? 1 : -1];
typedef char CarSceneRecord_alternateWheelSceneCheck[offsetof(CarSceneRecord, alternateWheelScene) == 0xc ? 1 : -1];
typedef char CarSceneRecord_originalWheelObjectsCheck[offsetof(CarSceneRecord, originalWheelObjects) == 0x10 ? 1 : -1];
typedef char CarSceneRecord_detailCodeCheck[offsetof(CarSceneRecord, detailCode) == 0x20 ? 1 : -1];
typedef char CarSceneRecord_variantCodeCheck[offsetof(CarSceneRecord, variantCode) == 0x21 ? 1 : -1];
typedef char g_carScenesCapacityCheck[sizeof(g_carScenes) / sizeof(g_carScenes[0]) == 16 ? 1 : -1];
typedef char g_carAuxiliaryBuffersCapacityCheck[sizeof(g_carAuxiliaryBuffers) / sizeof(g_carAuxiliaryBuffers[0]) == 16 ? 1 : -1];
typedef char g_carAlternateBodyScenesCapacityCheck[sizeof(g_carAlternateBodyScenes) / sizeof(g_carAlternateBodyScenes[0]) == 16 ? 1 : -1];
typedef char g_carWheelModelBuffersCapacityCheck[sizeof(g_carWheelModelBuffers) / sizeof(g_carWheelModelBuffers[0]) == 16 ? 1 : -1];
typedef char g_carAlternateBodyBuffersCapacityCheck[sizeof(g_carAlternateBodyBuffers) / sizeof(g_carAlternateBodyBuffers[0]) == 16 ? 1 : -1];
typedef char g_carModelBuffersCapacityCheck[sizeof(g_carModelBuffers) / sizeof(g_carModelBuffers[0]) == 16 ? 1 : -1];
typedef char g_carInfoBuffersCapacityCheck[sizeof(g_carInfoBuffers) / sizeof(g_carInfoBuffers[0]) == 8 ? 1 : -1];

// Scene binding and matrix identities established by model load and reload.
typedef char CarBinding_physicsMatrixCheck[offsetof(Car, physicsMatrix) == 0x0 ? 1 : -1];
typedef char CarBinding_bodyMatrixCheck[offsetof(Car, bodyMatrix) == 0x40 ? 1 : -1];
typedef char CarBinding_pSceneRootCheck[offsetof(Car, pSceneRoot) == 0x71c ? 1 : -1];
typedef char CarBinding_pBodyNodeCheck[offsetof(Car, pBodyNode) == 0x720 ? 1 : -1];
typedef char CarBinding_pAlternateBodyNodeCheck[offsetof(Car, pAlternateBodyNode) == 0x724 ? 1 : -1];

// Weather, lighting and precipitation layouts recovered as one family.
typedef char ViewWeatherStateSizeCheck[sizeof(ViewWeatherState) == 0x178 ? 1 : -1];
typedef char ViewWeatherState_kindOffsetCheck[offsetof(ViewWeatherState, kind) == 0x0 ? 1 : -1];
typedef char ViewWeatherState_targetKindOffsetCheck[offsetof(ViewWeatherState, targetKind) == 0x4 ? 1 : -1];
typedef char ViewWeatherState_centreOffsetCheck[offsetof(ViewWeatherState, centre) == 0x8 ? 1 : -1];
typedef char ViewWeatherState_previousCentreOffsetCheck[offsetof(ViewWeatherState, previousCentre) == 0x14 ? 1 : -1];
typedef char ViewWeatherState_relativeVelocityOffsetCheck[offsetof(ViewWeatherState, relativeVelocity) == 0x20 ? 1 : -1];
typedef char ViewWeatherState_velocityOffsetCheck[offsetof(ViewWeatherState, velocity) == 0x2c ? 1 : -1];
typedef char ViewWeatherState_snowSwayAxisOffsetCheck[offsetof(ViewWeatherState, snowSwayAxis) == 0x38 ? 1 : -1];
typedef char ViewWeatherState_splashDisplacementOffsetCheck[offsetof(ViewWeatherState, splashDisplacement) == 0x44 ? 1 : -1];
typedef char ViewWeatherState_inverseFallDisplacementOffsetCheck[offsetof(ViewWeatherState, inverseFallDisplacement) == 0x50 ? 1 : -1];
typedef char ViewWeatherState_intensityOffsetCheck[offsetof(ViewWeatherState, intensity) == 0x54 ? 1 : -1];
typedef char ViewWeatherState_particleCountOffsetCheck[offsetof(ViewWeatherState, particleCount) == 0x58 ? 1 : -1];
typedef char ViewWeatherState_targetParticleCountOffsetCheck[offsetof(ViewWeatherState, targetParticleCount) == 0x5c ? 1 : -1];
typedef char ViewWeatherState_particleCountChangeRateOffsetCheck[offsetof(ViewWeatherState, particleCountChangeRate) == 0x60 ? 1 : -1];
typedef char ViewWeatherState_precipitationFadeOffsetCheck[offsetof(ViewWeatherState, precipitationFade) == 0x64 ? 1 : -1];
typedef char ViewWeatherState_sunVisibilityOffsetCheck[offsetof(ViewWeatherState, sunVisibility) == 0x68 ? 1 : -1];
typedef char ViewWeatherState_routePositionOffsetCheck[offsetof(ViewWeatherState, routePosition) == 0x6c ? 1 : -1];
typedef char ViewWeatherState_lastRoutePositionOffsetCheck[offsetof(ViewWeatherState, lastRoutePosition) == 0x70 ? 1 : -1];
typedef char ViewWeatherState_particleCapacityOffsetCheck[offsetof(ViewWeatherState, particleCapacity) == 0x74 ? 1 : -1];
typedef char ViewWeatherState_firstParticleOffsetCheck[offsetof(ViewWeatherState, firstParticle) == 0x76 ? 1 : -1];
typedef char ViewWeatherState_groundTrianglesOffsetCheck[offsetof(ViewWeatherState, groundTriangles) == 0x78 ? 1 : -1];
typedef char ViewWeatherState_field_0xaaOffsetCheck[offsetof(ViewWeatherState, field_0xaa) == 0xaa ? 1 : -1];
typedef char ViewWeatherState_groundHeightsOffsetCheck[offsetof(ViewWeatherState, groundHeights) == 0xac ? 1 : -1];
typedef char ViewWeatherState_relativeGroundHeightsOffsetCheck[offsetof(ViewWeatherState, relativeGroundHeights) == 0x110 ? 1 : -1];
typedef char ViewWeatherState_shelteredOffsetCheck[offsetof(ViewWeatherState, sheltered) == 0x174 ? 1 : -1];
typedef char ViewLightingRampSizeCheck[sizeof(ViewLightingRamp) == 0x2c ? 1 : -1];
typedef char ViewLightingRamp_routePositionOffsetCheck[offsetof(ViewLightingRamp, routePosition) == 0x0 ? 1 : -1];
typedef char ViewLightingRamp_lastRoutePositionOffsetCheck[offsetof(ViewLightingRamp, lastRoutePosition) == 0x4 ? 1 : -1];
typedef char ViewLightingRamp_routeBlendOffsetCheck[offsetof(ViewLightingRamp, routeBlend) == 0x8 ? 1 : -1];
typedef char ViewLightingRamp_routeBlendOffsetOffsetCheck[offsetof(ViewLightingRamp, routeBlendOffset) == 0xc ? 1 : -1];
typedef char ViewLightingRamp_blendOffsetCheck[offsetof(ViewLightingRamp, blend) == 0x10 ? 1 : -1];
typedef char ViewLightingRamp_sunYawOffsetCheck[offsetof(ViewLightingRamp, sunYaw) == 0x14 ? 1 : -1];
typedef char ViewLightingRamp_previousBlendOffsetCheck[offsetof(ViewLightingRamp, previousBlend) == 0x18 ? 1 : -1];
typedef char ViewLightingRamp_drawBlendOffsetCheck[offsetof(ViewLightingRamp, drawBlend) == 0x1c ? 1 : -1];
typedef char ViewLightingRamp_previousSunYawOffsetCheck[offsetof(ViewLightingRamp, previousSunYaw) == 0x20 ? 1 : -1];
typedef char ViewLightingRamp_drawSunYawOffsetCheck[offsetof(ViewLightingRamp, drawSunYaw) == 0x24 ? 1 : -1];
typedef char ViewLightingRamp_lightingDirtyOffsetCheck[offsetof(ViewLightingRamp, lightingDirty) == 0x28 ? 1 : -1];
typedef char CarSurfaceRampSizeCheck[sizeof(CarSurfaceRamp) == 0xc ? 1 : -1];
typedef char CarSurfaceRamp_routePositionOffsetCheck[offsetof(CarSurfaceRamp, routePosition) == 0x0 ? 1 : -1];
typedef char CarSurfaceRamp_lastRoutePositionOffsetCheck[offsetof(CarSurfaceRamp, lastRoutePosition) == 0x4 ? 1 : -1];
typedef char CarSurfaceRamp_blendOffsetCheck[offsetof(CarSurfaceRamp, blend) == 0x8 ? 1 : -1];
typedef char WeatherWindTransitionSizeCheck[sizeof(WeatherWindTransition) == 0xc ? 1 : -1];
typedef char WeatherWindTransition_targetStrengthOffsetCheck[offsetof(WeatherWindTransition, targetStrength) == 0x0 ? 1 : -1];
typedef char WeatherWindTransition_changeRateOffsetCheck[offsetof(WeatherWindTransition, changeRate) == 0x4 ? 1 : -1];
typedef char WeatherWindTransition_holdTimeOffsetCheck[offsetof(WeatherWindTransition, holdTime) == 0x8 ? 1 : -1];
typedef char StageLightPresetSizeCheck[sizeof(StageLightPreset) == 0x48 ? 1 : -1];
typedef char StageLightPreset_meshHeightParametersOffsetCheck[offsetof(StageLightPreset, meshHeightParameters) == 0x0 ? 1 : -1];
typedef char StageLightPreset_field_0xcOffsetCheck[offsetof(StageLightPreset, field_0xc) == 0xc ? 1 : -1];
typedef char StageLightPreset_sunIconSizeOffsetCheck[offsetof(StageLightPreset, sunIconSize) == 0x10 ? 1 : -1];
typedef char StageLightPreset_fogStartOffsetCheck[offsetof(StageLightPreset, fogStart) == 0x14 ? 1 : -1];
typedef char StageLightPreset_fogEndOffsetCheck[offsetof(StageLightPreset, fogEnd) == 0x18 ? 1 : -1];
typedef char StageLightPreset_colourOffsetCheck[offsetof(StageLightPreset, colour) == 0x1c ? 1 : -1];
typedef char StageLightingValuesSizeCheck[sizeof(StageLightingValues) == 0xb4 ? 1 : -1];
typedef char StageLightingValues_lowColourOffsetCheck[offsetof(StageLightingValues, lowColour) == 0x0 ? 1 : -1];
typedef char StageLightingValues_highColourDeltaOffsetCheck[offsetof(StageLightingValues, highColourDelta) == 0xc ? 1 : -1];
typedef char StageLightingValues_heightReferenceColourOffsetCheck[offsetof(StageLightingValues, heightReferenceColour) == 0x18 ? 1 : -1];
typedef char StageLightingValues_sunIconColourOffsetCheck[offsetof(StageLightingValues, sunIconColour) == 0x24 ? 1 : -1];
typedef char StageLightingValues_groundColourOffsetCheck[offsetof(StageLightingValues, groundColour) == 0x30 ? 1 : -1];
typedef char StageLightingValues_objectColourOffsetCheck[offsetof(StageLightingValues, objectColour) == 0x3c ? 1 : -1];
typedef char StageLightingValues_ambientColourOffsetCheck[offsetof(StageLightingValues, ambientColour) == 0x48 ? 1 : -1];
typedef char StageLightingValues_lightColourOffsetCheck[offsetof(StageLightingValues, lightColour) == 0x54 ? 1 : -1];
typedef char StageLightingValues_mesh5ColourOffsetCheck[offsetof(StageLightingValues, mesh5Colour) == 0x60 ? 1 : -1];
typedef char StageLightingValues_meshHeightParametersOffsetCheck[offsetof(StageLightingValues, meshHeightParameters) == 0x6c ? 1 : -1];
typedef char StageLightingValues_fogColourOffsetCheck[offsetof(StageLightingValues, fogColour) == 0x78 ? 1 : -1];
typedef char StageLightingValues_skyColourOffsetCheck[offsetof(StageLightingValues, skyColour) == 0x84 ? 1 : -1];
typedef char StageLightingValues_skyAlphaOffsetCheck[offsetof(StageLightingValues, skyAlpha) == 0x90 ? 1 : -1];
typedef char StageLightingValues_fogStartOffsetCheck[offsetof(StageLightingValues, fogStart) == 0x94 ? 1 : -1];
typedef char StageLightingValues_fogEndOffsetCheck[offsetof(StageLightingValues, fogEnd) == 0x98 ? 1 : -1];
typedef char StageLightingValues_heightReferenceBlendOffsetCheck[offsetof(StageLightingValues, heightReferenceBlend) == 0x9c ? 1 : -1];
typedef char StageLightingValues_groundReferenceBlendOffsetCheck[offsetof(StageLightingValues, groundReferenceBlend) == 0xa0 ? 1 : -1];
typedef char StageLightingValues_objectAlphaOffsetCheck[offsetof(StageLightingValues, objectAlpha) == 0xa4 ? 1 : -1];
typedef char StageLightingValues_mesh5AlphaOffsetCheck[offsetof(StageLightingValues, mesh5Alpha) == 0xa8 ? 1 : -1];
typedef char StageLightingValues_sunIconSizeOffsetCheck[offsetof(StageLightingValues, sunIconSize) == 0xac ? 1 : -1];
typedef char StageLightingValues_intensityOffsetCheck[offsetof(StageLightingValues, intensity) == 0xb0 ? 1 : -1];
typedef char StageLightingStateSizeCheck[sizeof(StageLightingState) == 0x178 ? 1 : -1];
typedef char StageLightingState_primaryOffsetCheck[offsetof(StageLightingState, primary) == 0x0 ? 1 : -1];
typedef char StageLightingState_secondaryOffsetCheck[offsetof(StageLightingState, secondary) == 0xb4 ? 1 : -1];
typedef char StageLightingState_blendOffsetCheck[offsetof(StageLightingState, blend) == 0x168 ? 1 : -1];
typedef char StageLightingState_intensityOffsetCheck[offsetof(StageLightingState, intensity) == 0x16c ? 1 : -1];
typedef char StageLightingState_lightningSectorOffsetCheck[offsetof(StageLightingState, lightningSector) == 0x170 ? 1 : -1];
typedef char StageLightingState_previousLightningSectorOffsetCheck[offsetof(StageLightingState, previousLightningSector) == 0x172 ? 1 : -1];
typedef char StageLightingState_fogEnabledOffsetCheck[offsetof(StageLightingState, fogEnabled) == 0x174 ? 1 : -1];
typedef char StageWeatherParticleSizeCheck[sizeof(StageWeatherParticle) == 0x24 ? 1 : -1];
typedef char StageWeatherParticle_xOffsetCheck[offsetof(StageWeatherParticle, x) == 0x0 ? 1 : -1];
typedef char StageWeatherParticle_yOffsetCheck[offsetof(StageWeatherParticle, y) == 0x4 ? 1 : -1];
typedef char StageWeatherParticle_zOffsetCheck[offsetof(StageWeatherParticle, z) == 0x8 ? 1 : -1];
typedef char StageWeatherParticle_spinOffsetCheck[offsetof(StageWeatherParticle, spin) == 0xc ? 1 : -1];
typedef char StageWeatherParticle_swayAmplitudeOffsetCheck[offsetof(StageWeatherParticle, swayAmplitude) == 0x10 ? 1 : -1];
typedef char StageWeatherParticle_snowPhaseDegreesOffsetCheck[offsetof(StageWeatherParticle, snowPhaseDegrees) == 0x14 ? 1 : -1];
typedef char StageWeatherParticle_splashGroundHeightOffsetCheck[offsetof(StageWeatherParticle, splashGroundHeight) == 0x14 ? 1 : -1];
typedef char StageWeatherParticle_scaleOffsetCheck[offsetof(StageWeatherParticle, scale) == 0x18 ? 1 : -1];
typedef char StageWeatherParticle_field_0x1cOffsetCheck[offsetof(StageWeatherParticle, field_0x1c) == 0x1c ? 1 : -1];
typedef char StageWeatherParticle_textureVariantOffsetCheck[offsetof(StageWeatherParticle, textureVariant) == 0x1d ? 1 : -1];
typedef char StageWeatherParticle_field_0x1eOffsetCheck[offsetof(StageWeatherParticle, field_0x1e) == 0x1e ? 1 : -1];
typedef char StageWeatherParticle_wrappedOffsetCheck[offsetof(StageWeatherParticle, wrapped) == 0x20 ? 1 : -1];
typedef char WeatherParticlePoolCapacityCheck[sizeof(g_weatherParticles) / sizeof(g_weatherParticles[0]) == 400 ? 1 : -1];
typedef char WeatherTerrainCacheCapacityCheck[sizeof(((ViewWeatherState *)0)->groundTriangles) / sizeof(short) == 25 ? 1 : -1];

// Part geometry and countdown fields consumed by the car damage/render chain.
typedef char CarPartVertexGeometrySizeCheck[sizeof(DeformVertex) == 0x20 ? 1 : -1];
typedef char CarPartFloatVertexGeometrySizeCheck[sizeof(DeformFloatVertex) == 0x30 ? 1 : -1];
typedef char MeshTriangleGeometrySizeCheck[sizeof(MeshTriangle) == 0x4c ? 1 : -1];
typedef char MeshGeometrySizeCheck[sizeof(Mesh) == 0x120 ? 1 : -1];
typedef char CarPartSet_meshes_GeometryOffsetCheck[offsetof(CarPartSet, geometry) + offsetof(DeformMeshSources, meshes) == 0x0 ? 1 : -1];
typedef char CarPartSet_nodes_GeometryOffsetCheck[offsetof(CarPartSet, geometry) + offsetof(DeformMeshSources, nodes) == 0x3c ? 1 : -1];
typedef char CarPartSet_vertices_GeometryOffsetCheck[offsetof(CarPartSet, geometry) + offsetof(DeformMeshSources, vertices) == 0x78 ? 1 : -1];
typedef char CarPartSet_centres_GeometryOffsetCheck[offsetof(CarPartSet, centres) == 0xb4 ? 1 : -1];
typedef char CarPartSet_halfExtents_GeometryOffsetCheck[offsetof(CarPartSet, halfExtents) == 0x168 ? 1 : -1];
typedef char CarPartSet_damageGrid_GeometryOffsetCheck[offsetof(CarPartSet, damageGrid) == 0x21c ? 1 : -1];
typedef char CarPartSet_brokenLightFlickerTimer_GeometryOffsetCheck[offsetof(CarPartSet, brokenLightFlickerTimer) == 0x40c ? 1 : -1];
typedef char CarPartSet_vertexCount_GeometryOffsetCheck[offsetof(CarPartSet, vertexCount) == 0x420 ? 1 : -1];
typedef char CarPartSet_count_GeometryOffsetCheck[offsetof(CarPartSet, count) == 0x45c ? 1 : -1];
typedef char CarPartSet_brokenLightFlickerPhase_GeometryOffsetCheck[offsetof(CarPartSet, brokenLightFlickerPhase) == 0x4cc ? 1 : -1];
typedef char CarPartVertex_pos_GeometryOffsetCheck[offsetof(DeformVertex, pos) == 0x0 ? 1 : -1];
typedef char CarPartVertex_normal_GeometryOffsetCheck[offsetof(DeformVertex, normal) == 0xc ? 1 : -1];
typedef char CarPartVertex_normal8_GeometryOffsetCheck[offsetof(DeformVertex, normal8) == 0x18 ? 1 : -1];
typedef char CarPartVertex_rawNormal_GeometryOffsetCheck[offsetof(DeformVertex, rawNormal) == 0x1b ? 1 : -1];
typedef char CarPartFloatVertex_pos_GeometryOffsetCheck[offsetof(DeformFloatVertex, pos) == 0x0 ? 1 : -1];
typedef char CarPartFloatVertex_normal_GeometryOffsetCheck[offsetof(DeformFloatVertex, normal) == 0xc ? 1 : -1];
typedef char CarPartFloatVertex_colour_GeometryOffsetCheck[offsetof(DeformFloatVertex, colour) == 0x18 ? 1 : -1];
typedef char MeshTriangle_vertexIndex_GeometryOffsetCheck[offsetof(MeshTriangle, vertexIndex) == 0x40 ? 1 : -1];
typedef char Mesh_pVertexData_GeometryOffsetCheck[offsetof(Mesh, pVertexData) == 0xc ? 1 : -1];
typedef char Mesh_pTriangles_GeometryOffsetCheck[offsetof(Mesh, pTriangles) == 0x24 ? 1 : -1];
typedef char Mesh_triangleCount_GeometryOffsetCheck[offsetof(Mesh, triangleCount) == 0x28 ? 1 : -1];
typedef char CarPartSet_meshes_GeometryCapacityCheck[sizeof(((CarPartSet *)0)->geometry.meshes) / sizeof(((CarPartSet *)0)->geometry.meshes[0]) == 15 ? 1 : -1];
typedef char CarPartSet_nodes_GeometryCapacityCheck[sizeof(((CarPartSet *)0)->geometry.nodes) / sizeof(((CarPartSet *)0)->geometry.nodes[0]) == 15 ? 1 : -1];
typedef char CarPartSet_vertices_GeometryCapacityCheck[sizeof(((CarPartSet *)0)->geometry.vertices) / sizeof(((CarPartSet *)0)->geometry.vertices[0]) == 15 ? 1 : -1];
typedef char CarPartSet_centres_GeometryCapacityCheck[sizeof(((CarPartSet *)0)->centres) / sizeof(((CarPartSet *)0)->centres[0]) == 15 ? 1 : -1];
typedef char CarPartSet_halfExtents_GeometryCapacityCheck[sizeof(((CarPartSet *)0)->halfExtents) / sizeof(((CarPartSet *)0)->halfExtents[0]) == 15 ? 1 : -1];
typedef char CarPartSet_vertexCount_GeometryCapacityCheck[sizeof(((CarPartSet *)0)->vertexCount) / sizeof(((CarPartSet *)0)->vertexCount[0]) == 15 ? 1 : -1];
typedef char MeshTriangle_vertexIndex_GeometryCapacityCheck[sizeof(((MeshTriangle *)0)->vertexIndex) / sizeof(((MeshTriangle *)0)->vertexIndex[0]) == 3 ? 1 : -1];
typedef char CarBodyNodePartSetupOffsetCheck[offsetof(Car, pBodyNode) == 0x720 ? 1 : -1];
typedef char CarSceneRootLightOffsetCheck[offsetof(Car, pSceneRoot) == 0x71c ? 1 : -1];

// Shared deformation prefix and the distinct preview counts/scene/box records.
typedef char DeformMeshSources_SizeCheck[sizeof(DeformMeshSources) == 0xb4 ? 1 : -1];
typedef char DeformMeshSources_meshes_OffsetCheck[offsetof(DeformMeshSources, meshes) == 0x0 ? 1 : -1];
typedef char DeformMeshSources_nodes_OffsetCheck[offsetof(DeformMeshSources, nodes) == 0x3c ? 1 : -1];
typedef char DeformMeshSources_vertices_OffsetCheck[offsetof(DeformMeshSources, vertices) == 0x78 ? 1 : -1];
typedef char OptionPreviewMeshRecord_SizeCheck[sizeof(OptionPreviewMeshRecord) == 0x2ac ? 1 : -1];
typedef char OptionPreviewMeshRecord_geometry_OffsetCheck[offsetof(OptionPreviewMeshRecord, geometry) == 0x0 ? 1 : -1];
typedef char OptionPreviewMeshRecord_centre_OffsetCheck[offsetof(OptionPreviewMeshRecord, centre) == 0xb4 ? 1 : -1];
typedef char OptionPreviewMeshRecord_halfSize_OffsetCheck[offsetof(OptionPreviewMeshRecord, halfSize) == 0x168 ? 1 : -1];
typedef char OptionPreviewMeshRecord_maxX_OffsetCheck[offsetof(OptionPreviewMeshRecord, maxX) == 0x21c ? 1 : -1];
typedef char OptionPreviewMeshRecord_minX_OffsetCheck[offsetof(OptionPreviewMeshRecord, minX) == 0x220 ? 1 : -1];
typedef char OptionPreviewMeshRecord_maxZ_OffsetCheck[offsetof(OptionPreviewMeshRecord, maxZ) == 0x224 ? 1 : -1];
typedef char OptionPreviewMeshRecord_minZ_OffsetCheck[offsetof(OptionPreviewMeshRecord, minZ) == 0x228 ? 1 : -1];
typedef char OptionPreviewMeshRecord_cornerHeightOffsets_OffsetCheck[offsetof(OptionPreviewMeshRecord, cornerHeightOffsets) == 0x22c ? 1 : -1];
typedef char OptionPreviewMeshRecord_partDamageFractions_OffsetCheck[offsetof(OptionPreviewMeshRecord, partDamageFractions) == 0x23c ? 1 : -1];
typedef char OptionPreviewMeshRecord_vertexCount_OffsetCheck[offsetof(OptionPreviewMeshRecord, vertexCount) == 0x24c ? 1 : -1];
typedef char OptionPreviewMeshRecord_meshCount_OffsetCheck[offsetof(OptionPreviewMeshRecord, meshCount) == 0x26a ? 1 : -1];
typedef char OptionPreviewMeshRecord_meshVisible_OffsetCheck[offsetof(OptionPreviewMeshRecord, meshVisible) == 0x26c ? 1 : -1];
typedef char OptionPreviewMeshRecord_verticesAssigned_OffsetCheck[offsetof(OptionPreviewMeshRecord, verticesAssigned) == 0x2a8 ? 1 : -1];
typedef char OptionPreviewSceneRecord_SizeCheck[sizeof(OptionPreviewSceneRecord) == 0x54 ? 1 : -1];
typedef char OptionPreviewSceneRecord_modelClass_OffsetCheck[offsetof(OptionPreviewSceneRecord, modelClass) == 0x0 ? 1 : -1];
typedef char OptionPreviewSceneRecord_bodyNode_OffsetCheck[offsetof(OptionPreviewSceneRecord, bodyNode) == 0x4 ? 1 : -1];
typedef char OptionPreviewSceneRecord_rootNode_OffsetCheck[offsetof(OptionPreviewSceneRecord, rootNode) == 0x8 ? 1 : -1];
typedef char OptionPreviewSceneRecord_lowWheelRoot_OffsetCheck[offsetof(OptionPreviewSceneRecord, lowWheelRoot) == 0xc ? 1 : -1];
typedef char OptionPreviewSceneRecord_sixWheelRoot_OffsetCheck[offsetof(OptionPreviewSceneRecord, sixWheelRoot) == 0x10 ? 1 : -1];
typedef char OptionPreviewSceneRecord_wheelNodes_OffsetCheck[offsetof(OptionPreviewSceneRecord, wheelNodes) == 0x14 ? 1 : -1];
typedef char OptionPreviewSceneRecord_normalWheelMeshes_OffsetCheck[offsetof(OptionPreviewSceneRecord, normalWheelMeshes) == 0x24 ? 1 : -1];
typedef char OptionPreviewSceneRecord_lowWheelMeshes_OffsetCheck[offsetof(OptionPreviewSceneRecord, lowWheelMeshes) == 0x34 ? 1 : -1];
typedef char OptionPreviewSceneRecord_sixWheelMeshes_OffsetCheck[offsetof(OptionPreviewSceneRecord, sixWheelMeshes) == 0x44 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_SizeCheck[sizeof(OptionPreviewDeformGeometry) == 0x138 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_pEntry_OffsetCheck[offsetof(OptionPreviewDeformGeometry, pEntry) == 0x0 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_corner_OffsetCheck[offsetof(OptionPreviewDeformGeometry, corner) == 0x4 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_vertex_OffsetCheck[offsetof(OptionPreviewDeformGeometry, vertex) == 0x64 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_anchor_OffsetCheck[offsetof(OptionPreviewDeformGeometry, anchor) == 0xf4 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_animationPhaseDegrees_OffsetCheck[offsetof(OptionPreviewDeformGeometry, animationPhaseDegrees) == 0x124 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_anchorPhaseDegrees_OffsetCheck[offsetof(OptionPreviewDeformGeometry, anchorPhaseDegrees) == 0x128 ? 1 : -1];
typedef char DeformMeshSources_meshes_CapacityCheck[sizeof(((DeformMeshSources *)0)->meshes) / sizeof(((DeformMeshSources *)0)->meshes[0]) == 15 ? 1 : -1];
typedef char DeformMeshSources_nodes_CapacityCheck[sizeof(((DeformMeshSources *)0)->nodes) / sizeof(((DeformMeshSources *)0)->nodes[0]) == 15 ? 1 : -1];
typedef char DeformMeshSources_vertices_CapacityCheck[sizeof(((DeformMeshSources *)0)->vertices) / sizeof(((DeformMeshSources *)0)->vertices[0]) == 15 ? 1 : -1];
typedef char OptionPreviewMeshRecord_centre_CapacityCheck[sizeof(((OptionPreviewMeshRecord *)0)->centre) / sizeof(((OptionPreviewMeshRecord *)0)->centre[0]) == 15 ? 1 : -1];
typedef char OptionPreviewMeshRecord_halfSize_CapacityCheck[sizeof(((OptionPreviewMeshRecord *)0)->halfSize) / sizeof(((OptionPreviewMeshRecord *)0)->halfSize[0]) == 15 ? 1 : -1];
typedef char OptionPreviewMeshRecord_vertexCount_CapacityCheck[sizeof(((OptionPreviewMeshRecord *)0)->vertexCount) / sizeof(((OptionPreviewMeshRecord *)0)->vertexCount[0]) == 15 ? 1 : -1];
typedef char OptionPreviewMeshRecord_meshVisible_CapacityCheck[sizeof(((OptionPreviewMeshRecord *)0)->meshVisible) / sizeof(((OptionPreviewMeshRecord *)0)->meshVisible[0]) == 15 ? 1 : -1];
typedef char OptionPreviewSceneRecord_wheelNodes_CapacityCheck[sizeof(((OptionPreviewSceneRecord *)0)->wheelNodes) / sizeof(((OptionPreviewSceneRecord *)0)->wheelNodes[0]) == 4 ? 1 : -1];
typedef char OptionPreviewSceneRecord_normalWheelMeshes_CapacityCheck[sizeof(((OptionPreviewSceneRecord *)0)->normalWheelMeshes) / sizeof(((OptionPreviewSceneRecord *)0)->normalWheelMeshes[0]) == 4 ? 1 : -1];
typedef char OptionPreviewSceneRecord_lowWheelMeshes_CapacityCheck[sizeof(((OptionPreviewSceneRecord *)0)->lowWheelMeshes) / sizeof(((OptionPreviewSceneRecord *)0)->lowWheelMeshes[0]) == 4 ? 1 : -1];
typedef char OptionPreviewSceneRecord_sixWheelMeshes_CapacityCheck[sizeof(((OptionPreviewSceneRecord *)0)->sixWheelMeshes) / sizeof(((OptionPreviewSceneRecord *)0)->sixWheelMeshes[0]) == 4 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_corner_CapacityCheck[sizeof(((OptionPreviewDeformGeometry *)0)->corner) / sizeof(((OptionPreviewDeformGeometry *)0)->corner[0]) == 8 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_vertex_CapacityCheck[sizeof(((OptionPreviewDeformGeometry *)0)->vertex) / sizeof(((OptionPreviewDeformGeometry *)0)->vertex[0]) == 12 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_anchor_CapacityCheck[sizeof(((OptionPreviewDeformGeometry *)0)->anchor) / sizeof(((OptionPreviewDeformGeometry *)0)->anchor[0]) == 4 ? 1 : -1];
typedef char OptionPreviewDeformGeometry_anchorPhaseDegrees_CapacityCheck[sizeof(((OptionPreviewDeformGeometry *)0)->anchorPhaseDegrees) / sizeof(((OptionPreviewDeformGeometry *)0)->anchorPhaseDegrees[0]) == 4 ? 1 : -1];
typedef char PreviewVertexCountWidthCheck[sizeof(((OptionPreviewMeshRecord *)0)->vertexCount[0]) == 2 ? 1 : -1];
typedef char PreviewMeshCountWidthCheck[sizeof(((OptionPreviewMeshRecord *)0)->meshCount) == 1 ? 1 : -1];
typedef char g_previewMeshRecords_CapacityCheck[sizeof(g_previewMeshRecords) / sizeof(g_previewMeshRecords[0]) == 16 ? 1 : -1];
typedef char g_previewSceneRecords_CapacityCheck[sizeof(g_previewSceneRecords) / sizeof(g_previewSceneRecords[0]) == 16 ? 1 : -1];
typedef char g_previewDeformGeometry_CapacityCheck[sizeof(g_previewDeformGeometry) / sizeof(g_previewDeformGeometry[0]) == 8 ? 1 : -1];
typedef char g_previewOriginalVertices_CapacityCheck[sizeof(g_previewOriginalVertices) / sizeof(g_previewOriginalVertices[0]) == 16 ? 1 : -1];
typedef char g_previewOriginalNodeTypes_CapacityCheck[sizeof(g_previewOriginalNodeTypes) / sizeof(g_previewOriginalNodeTypes[0]) == 16 ? 1 : -1];

// Packed impact payloads and the persistent damage prefix, distinct from a car record.
extern PreviewSignedAngles g_previewRotationAngles[4];
extern PreviewSignedAngles g_previewRotationDeltas[4];
extern PreviewSignedAngles g_previewRotationStartAngles[4];
extern PreviewSignedAngles g_previewRotationTargets[4];
extern int g_previewRotationStartTimes[20];
extern BYTE g_previewRotationActive[4];
extern FixAngles g_previewPartRotationPresets[12];
extern PreviewModelReferenceGeometry g_previewReferenceModels[14];
extern PreviewProjectedQuad g_previewProjectedPartQuads[12];
typedef char CarImpactPayload_RecoveredSizeCheck[sizeof(CarImpactPayload) == 0xc ? 1 : -1];
typedef char RallyCarDamageState_RecoveredSizeCheck[sizeof(RallyCarDamageState) == 0x148 ? 1 : -1];
typedef char PreviewSignedAngles_RecoveredSizeCheck[sizeof(PreviewSignedAngles) == 0x8 ? 1 : -1];
typedef char PreviewModelReferenceGeometry_RecoveredSizeCheck[sizeof(PreviewModelReferenceGeometry) == 0x240 ? 1 : -1];
typedef char PreviewScreenPoint_RecoveredSizeCheck[sizeof(PreviewScreenPoint) == 0x8 ? 1 : -1];
typedef char PreviewProjectedQuad_RecoveredSizeCheck[sizeof(PreviewProjectedQuad) == 0x20 ? 1 : -1];
typedef char CarImpactPayload_strength_RecoveredOffsetCheck[offsetof(CarImpactPayload, strength) == 0x0 ? 1 : -1];
typedef char CarImpactPayload_mode_RecoveredOffsetCheck[offsetof(CarImpactPayload, mode) == 0x1 ? 1 : -1];
typedef char CarImpactPayload_axisRadius_RecoveredOffsetCheck[offsetof(CarImpactPayload, axisRadius) == 0x2 ? 1 : -1];
typedef char CarImpactPayload_normal_RecoveredOffsetCheck[offsetof(CarImpactPayload, normal) == 0x3 ? 1 : -1];
typedef char CarImpactPayload_axis_RecoveredOffsetCheck[offsetof(CarImpactPayload, axis) == 0x6 ? 1 : -1];
typedef char CarImpactPayload_position_RecoveredOffsetCheck[offsetof(CarImpactPayload, position) == 0x9 ? 1 : -1];
typedef char CarDamageLink_impact_RecoveredOffsetCheck[offsetof(CarDamageLink, impact) == 0x0 ? 1 : -1];
typedef char CarDamageLink_next_RecoveredOffsetCheck[offsetof(CarDamageLink, next) == 0xc ? 1 : -1];
typedef char RallyCarDamageState_impacts_RecoveredOffsetCheck[offsetof(RallyCarDamageState, impacts) == 0x0 ? 1 : -1];
typedef char RallyCarDamageState_damage_RecoveredOffsetCheck[offsetof(RallyCarDamageState, damage) == 0x108 ? 1 : -1];
typedef char PreviewSignedAngles_x_RecoveredOffsetCheck[offsetof(PreviewSignedAngles, x) == 0x0 ? 1 : -1];
typedef char PreviewSignedAngles_y_RecoveredOffsetCheck[offsetof(PreviewSignedAngles, y) == 0x2 ? 1 : -1];
typedef char PreviewSignedAngles_z_RecoveredOffsetCheck[offsetof(PreviewSignedAngles, z) == 0x4 ? 1 : -1];
typedef char PreviewSignedAngles_field_0x6_RecoveredOffsetCheck[offsetof(PreviewSignedAngles, field_0x6) == 0x6 ? 1 : -1];
typedef char PreviewModelReferenceGeometry_partVertices_RecoveredOffsetCheck[offsetof(PreviewModelReferenceGeometry, partVertices) == 0x0 ? 1 : -1];
typedef char PreviewScreenPoint_x_RecoveredOffsetCheck[offsetof(PreviewScreenPoint, x) == 0x0 ? 1 : -1];
typedef char PreviewScreenPoint_y_RecoveredOffsetCheck[offsetof(PreviewScreenPoint, y) == 0x4 ? 1 : -1];
typedef char PreviewProjectedQuad_points_RecoveredOffsetCheck[offsetof(PreviewProjectedQuad, points) == 0x0 ? 1 : -1];
typedef char CarImpactPayload_normal_RecoveredCapacityCheck[sizeof(((CarImpactPayload *)0)->normal) / sizeof(((CarImpactPayload *)0)->normal[0]) == 3 ? 1 : -1];
typedef char CarImpactPayload_axis_RecoveredCapacityCheck[sizeof(((CarImpactPayload *)0)->axis) / sizeof(((CarImpactPayload *)0)->axis[0]) == 3 ? 1 : -1];
typedef char CarImpactPayload_position_RecoveredCapacityCheck[sizeof(((CarImpactPayload *)0)->position) / sizeof(((CarImpactPayload *)0)->position[0]) == 3 ? 1 : -1];
typedef char CarDamageLinkPool_links_RecoveredCapacityCheck[sizeof(((CarDamageLinkPool *)0)->links) / sizeof(((CarDamageLinkPool *)0)->links[0]) == 20 ? 1 : -1];
typedef char PreviewModelReferenceGeometry_partVertices_RecoveredCapacityCheck[sizeof(((PreviewModelReferenceGeometry *)0)->partVertices) / sizeof(((PreviewModelReferenceGeometry *)0)->partVertices[0]) == 12 ? 1 : -1];
typedef char PreviewProjectedQuad_points_RecoveredCapacityCheck[sizeof(((PreviewProjectedQuad *)0)->points) / sizeof(((PreviewProjectedQuad *)0)->points[0]) == 4 ? 1 : -1];
typedef char PreviewReferencePartVertexCapacityCheck[sizeof(((PreviewModelReferenceGeometry *)0)->partVertices[0]) / sizeof(FixVector) == 4 ? 1 : -1];
typedef char g_previewRotationAngles_RecoveredCapacityCheck[sizeof(g_previewRotationAngles) / sizeof(g_previewRotationAngles[0]) == 4 ? 1 : -1];
typedef char g_previewRotationDeltas_RecoveredCapacityCheck[sizeof(g_previewRotationDeltas) / sizeof(g_previewRotationDeltas[0]) == 4 ? 1 : -1];
typedef char g_previewRotationStartAngles_RecoveredCapacityCheck[sizeof(g_previewRotationStartAngles) / sizeof(g_previewRotationStartAngles[0]) == 4 ? 1 : -1];
typedef char g_previewRotationTargets_RecoveredCapacityCheck[sizeof(g_previewRotationTargets) / sizeof(g_previewRotationTargets[0]) == 4 ? 1 : -1];
typedef char g_previewRotationStartTimes_RecoveredCapacityCheck[sizeof(g_previewRotationStartTimes) / sizeof(g_previewRotationStartTimes[0]) == 20 ? 1 : -1];
typedef char g_previewRotationActive_RecoveredCapacityCheck[sizeof(g_previewRotationActive) / sizeof(g_previewRotationActive[0]) == 4 ? 1 : -1];
typedef char g_previewPartRotationPresets_RecoveredCapacityCheck[sizeof(g_previewPartRotationPresets) / sizeof(g_previewPartRotationPresets[0]) == 12 ? 1 : -1];
typedef char g_previewReferenceModels_RecoveredCapacityCheck[sizeof(g_previewReferenceModels) / sizeof(g_previewReferenceModels[0]) == 14 ? 1 : -1];
typedef char g_previewProjectedPartQuads_RecoveredCapacityCheck[sizeof(g_previewProjectedPartQuads) / sizeof(g_previewProjectedPartQuads[0]) == 12 ? 1 : -1];

// CIN views: trailing [1] arrays express variable tails, not fixed capacities.
typedef char CarLightPoint_CINViewSizeCheck[sizeof(CarLightPoint) == 0x28 ? 1 : -1];
typedef char CarLightProfile_CINViewSizeCheck[sizeof(CarLightProfile) == 0x2c ? 1 : -1];
typedef char CarSkidProfilePoint_CINViewSizeCheck[sizeof(CarSkidProfilePoint) == 0x8 ? 1 : -1];
typedef char CarContactProfile_CINViewSizeCheck[sizeof(CarContactProfile) == 0x14 ? 1 : -1];
typedef char CarGlassProfile_CINViewSizeCheck[sizeof(CarGlassProfile) == 0x54 ? 1 : -1];
typedef char CarFlexibleLineDescriptor_CINViewSizeCheck[sizeof(CarFlexibleLineDescriptor) == 0x20 ? 1 : -1];
typedef char CarFlexibleLineProfile_CINViewSizeCheck[sizeof(CarFlexibleLineProfile) == 0x30 ? 1 : -1];
typedef char CarInteriorProfile_CINViewSizeCheck[sizeof(CarInteriorProfile) == 0x30 ? 1 : -1];
typedef char CarInteriorProfilePointers_CINViewSizeCheck[sizeof(CarInteriorProfilePointers) == 0x1c ? 1 : -1];
typedef char CarInteriorNodes_CINViewSizeCheck[sizeof(CarInteriorNodes) == 0x1c ? 1 : -1];
typedef char CarWiperState_CINViewSizeCheck[sizeof(CarWiperState) == 0xc ? 1 : -1];
typedef char CarInteriorRuntimeTables_CINViewSizeCheck[sizeof(CarInteriorRuntimeTables) == 0x90 ? 1 : -1];
typedef char GenericFile_CINViewSizeCheck[sizeof(GenericFile) == 0xc ? 1 : -1];
typedef char CarInfoDirectory_sectionOffsets_CINOffsetCheck[offsetof(CarInfoDirectory, sectionOffsets) == 0x0 ? 1 : -1];
typedef char CarLightPoint_pos_CINOffsetCheck[offsetof(CarLightPoint, pos) == 0x0 ? 1 : -1];
typedef char CarLightPoint_dir_CINOffsetCheck[offsetof(CarLightPoint, dir) == 0xc ? 1 : -1];
typedef char CarLightPoint_size_CINOffsetCheck[offsetof(CarLightPoint, size) == 0x18 ? 1 : -1];
typedef char CarLightPoint_intensity_CINOffsetCheck[offsetof(CarLightPoint, intensity) == 0x1c ? 1 : -1];
typedef char CarLightPoint_type_CINOffsetCheck[offsetof(CarLightPoint, type) == 0x20 ? 1 : -1];
typedef char CarLightPoint_slot_CINOffsetCheck[offsetof(CarLightPoint, slot) == 0x21 ? 1 : -1];
typedef char CarLightPoint_part_CINOffsetCheck[offsetof(CarLightPoint, part) == 0x22 ? 1 : -1];
typedef char CarLightPoint_pad_0x23_CINOffsetCheck[offsetof(CarLightPoint, pad_0x23) == 0x23 ? 1 : -1];
typedef char CarLightPoint_object_CINOffsetCheck[offsetof(CarLightPoint, object) == 0x24 ? 1 : -1];
typedef char CarLightPoint_vertex_CINOffsetCheck[offsetof(CarLightPoint, vertex) == 0x26 ? 1 : -1];
typedef char CarLightProfile_count_CINOffsetCheck[offsetof(CarLightProfile, count) == 0x0 ? 1 : -1];
typedef char CarLightProfile_points_CINOffsetCheck[offsetof(CarLightProfile, points) == 0x4 ? 1 : -1];
typedef char CarSkidProfilePoint_longitudinalDistance_CINOffsetCheck[offsetof(CarSkidProfilePoint, longitudinalDistance) == 0x0 ? 1 : -1];
typedef char CarSkidProfilePoint_lateralWidth_CINOffsetCheck[offsetof(CarSkidProfilePoint, lateralWidth) == 0x4 ? 1 : -1];
typedef char CarContactProfile_pointCount_CINOffsetCheck[offsetof(CarContactProfile, pointCount) == 0x0 ? 1 : -1];
typedef char CarContactProfile_visibleRangeStart_CINOffsetCheck[offsetof(CarContactProfile, visibleRangeStart) == 0x1 ? 1 : -1];
typedef char CarContactProfile_visibleRangeCount_CINOffsetCheck[offsetof(CarContactProfile, visibleRangeCount) == 0x2 ? 1 : -1];
typedef char CarContactProfile_field_0x3_CINOffsetCheck[offsetof(CarContactProfile, field_0x3) == 0x3 ? 1 : -1];
typedef char CarContactProfile_longitudinalOffset_CINOffsetCheck[offsetof(CarContactProfile, longitudinalOffset) == 0x4 ? 1 : -1];
typedef char CarContactProfile_wheelPatchLength_CINOffsetCheck[offsetof(CarContactProfile, wheelPatchLength) == 0x8 ? 1 : -1];
typedef char CarContactProfile_points_CINOffsetCheck[offsetof(CarContactProfile, points) == 0xc ? 1 : -1];
typedef char CarGlassProfile_tint_CINOffsetCheck[offsetof(CarGlassProfile, tint) == 0x0 ? 1 : -1];
typedef char CarGlassProfile_windowVertices_CINOffsetCheck[offsetof(CarGlassProfile, windowVertices) == 0xc ? 1 : -1];
typedef char CarFlexibleLineProfile_constraintAxis_CINOffsetCheck[offsetof(CarFlexibleLineProfile, constraintAxis) == 0x0 ? 1 : -1];
typedef char CarFlexibleLineProfile_count_CINOffsetCheck[offsetof(CarFlexibleLineProfile, count) == 0xc ? 1 : -1];
typedef char CarFlexibleLineProfile_descriptors_CINOffsetCheck[offsetof(CarFlexibleLineProfile, descriptors) == 0x10 ? 1 : -1];
typedef char CarInteriorProfile_firstWiperRotation_CINOffsetCheck[offsetof(CarInteriorProfile, firstWiperRotation) == 0x0 ? 1 : -1];
typedef char CarInteriorProfile_firstWiperMaxAngle_CINOffsetCheck[offsetof(CarInteriorProfile, firstWiperMaxAngle) == 0x8 ? 1 : -1];
typedef char CarInteriorProfile_field_0xa_CINOffsetCheck[offsetof(CarInteriorProfile, field_0xa) == 0xa ? 1 : -1];
typedef char CarInteriorProfile_driverPoseOffset_CINOffsetCheck[offsetof(CarInteriorProfile, driverPoseOffset) == 0xc ? 1 : -1];
typedef char CarInteriorProfile_driverRestYaw_CINOffsetCheck[offsetof(CarInteriorProfile, driverRestYaw) == 0x18 ? 1 : -1];
typedef char CarInteriorProfile_field_0x1a_CINOffsetCheck[offsetof(CarInteriorProfile, field_0x1a) == 0x1a ? 1 : -1];
typedef char CarInteriorProfile_steeringBaseRotation_CINOffsetCheck[offsetof(CarInteriorProfile, steeringBaseRotation) == 0x1c ? 1 : -1];
typedef char CarInteriorProfile_secondWiperRotation_CINOffsetCheck[offsetof(CarInteriorProfile, secondWiperRotation) == 0x24 ? 1 : -1];
typedef char CarInteriorProfile_secondWiperMaxAngle_CINOffsetCheck[offsetof(CarInteriorProfile, secondWiperMaxAngle) == 0x2c ? 1 : -1];
typedef char CarInteriorProfilePointers_firstWiperRotation_CINOffsetCheck[offsetof(CarInteriorProfilePointers, firstWiperRotation) == 0x0 ? 1 : -1];
typedef char CarInteriorProfilePointers_firstWiperMaxAngle_CINOffsetCheck[offsetof(CarInteriorProfilePointers, firstWiperMaxAngle) == 0x4 ? 1 : -1];
typedef char CarInteriorProfilePointers_driverPoseOffset_CINOffsetCheck[offsetof(CarInteriorProfilePointers, driverPoseOffset) == 0x8 ? 1 : -1];
typedef char CarInteriorProfilePointers_driverRestYaw_CINOffsetCheck[offsetof(CarInteriorProfilePointers, driverRestYaw) == 0xc ? 1 : -1];
typedef char CarInteriorProfilePointers_steeringBaseRotation_CINOffsetCheck[offsetof(CarInteriorProfilePointers, steeringBaseRotation) == 0x10 ? 1 : -1];
typedef char CarInteriorProfilePointers_secondWiperRotation_CINOffsetCheck[offsetof(CarInteriorProfilePointers, secondWiperRotation) == 0x14 ? 1 : -1];
typedef char CarInteriorProfilePointers_secondWiperMaxAngle_CINOffsetCheck[offsetof(CarInteriorProfilePointers, secondWiperMaxAngle) == 0x18 ? 1 : -1];
typedef char CarInteriorNodes_steeringRestNode_CINOffsetCheck[offsetof(CarInteriorNodes, steeringRestNode) == 0x0 ? 1 : -1];
typedef char CarInteriorNodes_steeringBlendNode_CINOffsetCheck[offsetof(CarInteriorNodes, steeringBlendNode) == 0x4 ? 1 : -1];
typedef char CarInteriorNodes_steeringReferenceNode_CINOffsetCheck[offsetof(CarInteriorNodes, steeringReferenceNode) == 0x8 ? 1 : -1];
typedef char CarInteriorNodes_driverPoseNode_CINOffsetCheck[offsetof(CarInteriorNodes, driverPoseNode) == 0xc ? 1 : -1];
typedef char CarInteriorNodes_steeringWheelNode_CINOffsetCheck[offsetof(CarInteriorNodes, steeringWheelNode) == 0x10 ? 1 : -1];
typedef char CarInteriorNodes_wiperNodes_CINOffsetCheck[offsetof(CarInteriorNodes, wiperNodes) == 0x14 ? 1 : -1];
typedef char CarWiperState_mode_CINOffsetCheck[offsetof(CarWiperState, mode) == 0x0 ? 1 : -1];
typedef char CarWiperState_sweepingForward_CINOffsetCheck[offsetof(CarWiperState, sweepingForward) == 0x4 ? 1 : -1];
typedef char CarWiperState_angle_CINOffsetCheck[offsetof(CarWiperState, angle) == 0x8 ? 1 : -1];
typedef char CarWiperState_step_CINOffsetCheck[offsetof(CarWiperState, step) == 0xa ? 1 : -1];
typedef char CarInteriorRuntimeTables_modelClasses_CINOffsetCheck[offsetof(CarInteriorRuntimeTables, modelClasses) == 0x0 ? 1 : -1];
typedef char CarInteriorRuntimeTables_wipers_CINOffsetCheck[offsetof(CarInteriorRuntimeTables, wipers) == 0x8 ? 1 : -1];
typedef char CarInteriorRuntimeTables_profiles_CINOffsetCheck[offsetof(CarInteriorRuntimeTables, profiles) == 0x20 ? 1 : -1];
typedef char CarInteriorRuntimeTables_nodes_CINOffsetCheck[offsetof(CarInteriorRuntimeTables, nodes) == 0x58 ? 1 : -1];
typedef char GenericFile_buffer_CINOffsetCheck[offsetof(GenericFile, buffer) == 0x0 ? 1 : -1];
typedef char GenericFile_fileSize_CINOffsetCheck[offsetof(GenericFile, fileSize) == 0x4 ? 1 : -1];
typedef char GenericFile_didFileLoad_CINOffsetCheck[offsetof(GenericFile, didFileLoad) == 0x8 ? 1 : -1];
typedef char StageArchiveTables_archives_CINOffsetCheck[offsetof(StageArchiveTables, archives) == 0x0 ? 1 : -1];
typedef char StageArchiveTables_driverCount_CINOffsetCheck[offsetof(StageArchiveTables, driverCount) == 0x180 ? 1 : -1];
typedef char StageArchiveTables_secondaryCount_CINOffsetCheck[offsetof(StageArchiveTables, secondaryCount) == 0x184 ? 1 : -1];
typedef char CarGlassProfile_tint_CINCapacityCheck[sizeof(((CarGlassProfile *)0)->tint) / sizeof(((CarGlassProfile *)0)->tint[0]) == 3 ? 1 : -1];
typedef char CarGlassProfile_windowVertices_CINCapacityCheck[sizeof(((CarGlassProfile *)0)->windowVertices) / sizeof(((CarGlassProfile *)0)->windowVertices[0]) == 6 ? 1 : -1];
typedef char CarInteriorNodes_wiperNodes_CINCapacityCheck[sizeof(((CarInteriorNodes *)0)->wiperNodes) / sizeof(((CarInteriorNodes *)0)->wiperNodes[0]) == 2 ? 1 : -1];
typedef char CarInteriorRuntimeTables_modelClasses_CINCapacityCheck[sizeof(((CarInteriorRuntimeTables *)0)->modelClasses) / sizeof(((CarInteriorRuntimeTables *)0)->modelClasses[0]) == 8 ? 1 : -1];
typedef char CarInteriorRuntimeTables_wipers_CINCapacityCheck[sizeof(((CarInteriorRuntimeTables *)0)->wipers) / sizeof(((CarInteriorRuntimeTables *)0)->wipers[0]) == 2 ? 1 : -1];
typedef char CarInteriorRuntimeTables_profiles_CINCapacityCheck[sizeof(((CarInteriorRuntimeTables *)0)->profiles) / sizeof(((CarInteriorRuntimeTables *)0)->profiles[0]) == 2 ? 1 : -1];
typedef char CarInteriorRuntimeTables_nodes_CINCapacityCheck[sizeof(((CarInteriorRuntimeTables *)0)->nodes) / sizeof(((CarInteriorRuntimeTables *)0)->nodes[0]) == 2 ? 1 : -1];
typedef char StageArchiveTables_archives_CINCapacityCheck[sizeof(((StageArchiveTables *)0)->archives) / sizeof(((StageArchiveTables *)0)->archives[0]) == 32 ? 1 : -1];
typedef char CarGlassTintWidthCheck[sizeof(((CarGlassProfile *)0)->tint[0]) == 4 ? 1 : -1];
typedef char CarInfoOffsetWidthCheck[sizeof(((CarInfoDirectory *)0)->sectionOffsets[0]) == 2 ? 1 : -1];
extern CarGlassProfile *g_carGlassProfiles[8];
typedef char g_carGlassProfiles_CINCapacityCheck[sizeof(g_carGlassProfiles) / sizeof(g_carGlassProfiles[0]) == 8 ? 1 : -1];
extern FixVector *g_carFlexibleLineConstraintAxes[8];
typedef char g_carFlexibleLineConstraintAxes_CINCapacityCheck[sizeof(g_carFlexibleLineConstraintAxes) / sizeof(g_carFlexibleLineConstraintAxes[0]) == 8 ? 1 : -1];
extern CarLightProfile *g_carLightProfiles[8];
typedef char g_carLightProfiles_CINCapacityCheck[sizeof(g_carLightProfiles) / sizeof(g_carLightProfiles[0]) == 8 ? 1 : -1];
extern CarSkidProfilePoint *g_physSkidProfilePoints[8];
typedef char g_physSkidProfilePoints_CINCapacityCheck[sizeof(g_physSkidProfilePoints) / sizeof(g_physSkidProfilePoints[0]) == 8 ? 1 : -1];
extern FixVector *g_carCameraOffsets[8];
typedef char g_carCameraOffsets_CINCapacityCheck[sizeof(g_carCameraOffsets) / sizeof(g_carCameraOffsets[0]) == 8 ? 1 : -1];
extern BYTE *g_physSkidCount[8];
typedef char g_physSkidCount_CINCapacityCheck[sizeof(g_physSkidCount) / sizeof(g_physSkidCount[0]) == 8 ? 1 : -1];
extern BYTE *g_physSkidRange[8];
typedef char g_physSkidRange_CINCapacityCheck[sizeof(g_physSkidRange) / sizeof(g_physSkidRange[0]) == 8 ? 1 : -1];
extern int *g_physSkidOffset[8];
typedef char g_physSkidOffset_CINCapacityCheck[sizeof(g_physSkidOffset) / sizeof(g_physSkidOffset[0]) == 8 ? 1 : -1];
extern int *g_physWheelLength[8];
typedef char g_physWheelLength_CINCapacityCheck[sizeof(g_physWheelLength) / sizeof(g_physWheelLength[0]) == 8 ? 1 : -1];
typedef char g_carInteriorModelClasses_CINCapacityCheck[sizeof(g_carInteriorModelClasses) / sizeof(g_carInteriorModelClasses[0]) == 8 ? 1 : -1];
typedef char g_carWiperStates_CINCapacityCheck[sizeof(g_carWiperStates) / sizeof(g_carWiperStates[0]) == 2 ? 1 : -1];
typedef char g_carInteriorProfilePointers_CINCapacityCheck[sizeof(g_carInteriorProfilePointers) / sizeof(g_carInteriorProfilePointers[0]) == 2 ? 1 : -1];
typedef char g_carInteriorNodeRows_CINCapacityCheck[sizeof(g_carInteriorNodeRows) / sizeof(g_carInteriorNodeRows[0]) == 2 ? 1 : -1];

extern BYTE g_viewObjectCarIndices[16];
extern int g_viewObjectLevels[64];
typedef char ViewObjectCarIndexCapacityCheck[sizeof(g_viewObjectCarIndices) == 16 ? 1 : -1];
typedef char ViewObjectLevelCapacityCheck[sizeof(g_viewObjectLevels) / sizeof(g_viewObjectLevels[0]) == 64 ? 1 : -1];

// Stage interior resources and shared light records (tandas 19–21).
typedef char CarDriverPoseState_RecoveredSizeCheck[(sizeof(CarDriverPoseState) == 0x24) ? 1 : -1];
typedef char CarInteriorDashTextures_RecoveredSizeCheck[(sizeof(CarInteriorDashTextures) == 0x8) ? 1 : -1];
typedef char CarLightTextureState_RecoveredSizeCheck[(sizeof(CarLightTextureState) == 0x48) ? 1 : -1];
typedef char CarHeadlightGlowRecord_RecoveredSizeCheck[(sizeof(CarHeadlightGlowRecord) == 0x5c) ? 1 : -1];
typedef char CarDriverPoseState_phaseAngle_RecoveredOffsetCheck[(offsetof(CarDriverPoseState, phaseAngle) == 0x0) ? 1 : -1];
typedef char CarDriverPoseState_rotation_RecoveredOffsetCheck[(offsetof(CarDriverPoseState, rotation) == 0x2) ? 1 : -1];
typedef char CarDriverPoseState_field_0xa_RecoveredOffsetCheck[(offsetof(CarDriverPoseState, field_0xa) == 0xa) ? 1 : -1];
typedef char CarDriverPoseState_offset_RecoveredOffsetCheck[(offsetof(CarDriverPoseState, offset) == 0xc) ? 1 : -1];
typedef char CarDriverPoseState_mountOffset_RecoveredOffsetCheck[(offsetof(CarDriverPoseState, mountOffset) == 0x18) ? 1 : -1];
typedef char CarInteriorDashTextures_revCounter_RecoveredOffsetCheck[(offsetof(CarInteriorDashTextures, revCounter) == 0x0) ? 1 : -1];
typedef char CarInteriorDashTextures_digit_RecoveredOffsetCheck[(offsetof(CarInteriorDashTextures, digit) == 0x4) ? 1 : -1];
typedef char CarLightTextureState_textures_RecoveredOffsetCheck[(offsetof(CarLightTextureState, textures) == 0x0) ? 1 : -1];
typedef char CarLightTextureState_levels_RecoveredOffsetCheck[(offsetof(CarLightTextureState, levels) == 0x8) ? 1 : -1];
typedef char CarLightTextureState_appliedLevels_RecoveredOffsetCheck[(offsetof(CarLightTextureState, appliedLevels) == 0x1c) ? 1 : -1];
typedef char CarLightTextureState_fadedLevels_RecoveredOffsetCheck[(offsetof(CarLightTextureState, fadedLevels) == 0x30) ? 1 : -1];
typedef char CarLightTextureState_channelMasks_RecoveredOffsetCheck[(offsetof(CarLightTextureState, channelMasks) == 0x44) ? 1 : -1];
typedef char CarLightTextureState_combineFirstTwoChannels_RecoveredOffsetCheck[(offsetof(CarLightTextureState, combineFirstTwoChannels) == 0x46) ? 1 : -1];
typedef char CarHeadlightGlowRecord_velocity_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, velocity) == 0x0) ? 1 : -1];
typedef char CarHeadlightGlowRecord_position_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, position) == 0xc) ? 1 : -1];
typedef char CarHeadlightGlowRecord_normal_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, normal) == 0x18) ? 1 : -1];
typedef char CarHeadlightGlowRecord_fade_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, fade) == 0x24) ? 1 : -1];
typedef char CarHeadlightGlowRecord_prevPosition_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, prevPosition) == 0x28) ? 1 : -1];
typedef char CarHeadlightGlowRecord_prevNormal_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, prevNormal) == 0x34) ? 1 : -1];
typedef char CarHeadlightGlowRecord_prevFade_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, prevFade) == 0x40) ? 1 : -1];
typedef char CarHeadlightGlowRecord_height_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, height) == 0x44) ? 1 : -1];
typedef char CarHeadlightGlowRecord_life_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, life) == 0x48) ? 1 : -1];
typedef char CarHeadlightGlowRecord_triangle_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, triangle) == 0x4c) ? 1 : -1];
typedef char CarHeadlightGlowRecord_field_0x4e_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, field_0x4e) == 0x4e) ? 1 : -1];
typedef char CarHeadlightGlowRecord_pGlow_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, pGlow) == 0x50) ? 1 : -1];
typedef char CarHeadlightGlowRecord_active_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, active) == 0x54) ? 1 : -1];
typedef char CarHeadlightGlowRecord_car_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, car) == 0x58) ? 1 : -1];
typedef char CarHeadlightGlowRecord_field_0x59_RecoveredOffsetCheck[(offsetof(CarHeadlightGlowRecord, field_0x59) == 0x59) ? 1 : -1];
typedef char g_carAppliedRevTextureLevels_RecoveredCapacityCheck[(sizeof(g_carAppliedRevTextureLevels) / sizeof(g_carAppliedRevTextureLevels[0]) == 2) ? 1 : -1];
typedef char g_carRequestedRevTextureLevels_RecoveredCapacityCheck[(sizeof(g_carRequestedRevTextureLevels) / sizeof(g_carRequestedRevTextureLevels[0]) == 2) ? 1 : -1];
typedef char g_carRequestedDigitTextureAlphas_RecoveredCapacityCheck[(sizeof(g_carRequestedDigitTextureAlphas) / sizeof(g_carRequestedDigitTextureAlphas[0]) == 2) ? 1 : -1];
typedef char g_carAppliedDigitTextureAlphas_RecoveredCapacityCheck[(sizeof(g_carAppliedDigitTextureAlphas) / sizeof(g_carAppliedDigitTextureAlphas[0]) == 2) ? 1 : -1];
typedef char g_carDetailBodyNodes_RecoveredCapacityCheck[(sizeof(g_carDetailBodyNodes) / sizeof(g_carDetailBodyNodes[0]) == 8) ? 1 : -1];
typedef char g_carDefaultBodyNodes_RecoveredCapacityCheck[(sizeof(g_carDefaultBodyNodes) / sizeof(g_carDefaultBodyNodes[0]) == 8) ? 1 : -1];
typedef char g_carDriverPoseNeedsReset_RecoveredCapacityCheck[(sizeof(g_carDriverPoseNeedsReset) / sizeof(g_carDriverPoseNeedsReset[0]) == 2) ? 1 : -1];
typedef char g_carInteriorArchives_RecoveredCapacityCheck[(sizeof(g_carInteriorArchives) / sizeof(g_carInteriorArchives[0]) == 16) ? 1 : -1];
typedef char g_carInteriorRoots_RecoveredCapacityCheck[(sizeof(g_carInteriorRoots) / sizeof(g_carInteriorRoots[0]) == 8) ? 1 : -1];
typedef char g_carInteriorDashTextures_RecoveredCapacityCheck[(sizeof(g_carInteriorDashTextures) / sizeof(g_carInteriorDashTextures[0]) == 2) ? 1 : -1];
typedef char g_carDriverRestPositions_RecoveredCapacityCheck[(sizeof(g_carDriverRestPositions) / sizeof(g_carDriverRestPositions[0]) == 2) ? 1 : -1];
typedef char g_carDriverPoseStates_RecoveredCapacityCheck[(sizeof(g_carDriverPoseStates) / sizeof(g_carDriverPoseStates[0]) == 2) ? 1 : -1];
typedef char g_carInteriorModelBuffers_RecoveredCapacityCheck[(sizeof(g_carInteriorModelBuffers) / sizeof(g_carInteriorModelBuffers[0]) == 2) ? 1 : -1];
typedef char g_carInteriorLoaded_RecoveredCapacityCheck[(sizeof(g_carInteriorLoaded) / sizeof(g_carInteriorLoaded[0]) == 2) ? 1 : -1];
typedef char g_carLightTextureStates_RecoveredCapacityCheck[(sizeof(g_carLightTextureStates) / sizeof(g_carLightTextureStates[0]) == 8) ? 1 : -1];
typedef char g_carHeadlightGlowRecords_RecoveredCapacityCheck[(sizeof(g_carHeadlightGlowRecords) / sizeof(g_carHeadlightGlowRecords[0]) == 100) ? 1 : -1];
typedef char g_carHeadlightGlowCooldowns_RecoveredCapacityCheck[(sizeof(g_carHeadlightGlowCooldowns) / sizeof(g_carHeadlightGlowCooldowns[0]) == 8) ? 1 : -1];
typedef char g_carAppliedRevTextureLevels_RecoveredRowCapacityCheck[(sizeof(g_carAppliedRevTextureLevels[0]) / sizeof(g_carAppliedRevTextureLevels[0][0]) == 12) ? 1 : -1];
typedef char g_carRequestedRevTextureLevels_RecoveredRowCapacityCheck[(sizeof(g_carRequestedRevTextureLevels[0]) / sizeof(g_carRequestedRevTextureLevels[0][0]) == 12) ? 1 : -1];
typedef char g_carRequestedDigitTextureAlphas_RecoveredRowCapacityCheck[(sizeof(g_carRequestedDigitTextureAlphas[0]) / sizeof(g_carRequestedDigitTextureAlphas[0][0]) == 7) ? 1 : -1];
typedef char g_carAppliedDigitTextureAlphas_RecoveredRowCapacityCheck[(sizeof(g_carAppliedDigitTextureAlphas[0]) / sizeof(g_carAppliedDigitTextureAlphas[0][0]) == 7) ? 1 : -1];
typedef char CarLightTextureState_TwoTextures_RecoveredCapacityCheck[(sizeof(((CarLightTextureState *)0)->textures) / sizeof(Texture *) == 2) ? 1 : -1];
typedef char CarLightTextureState_TwoLevelSets_RecoveredCapacityCheck[(sizeof(((CarLightTextureState *)0)->levels) / sizeof(((CarLightTextureState *)0)->levels[0]) == 2) ? 1 : -1];
typedef char CarLightTextureState_FiveLevels_RecoveredCapacityCheck[(sizeof(((CarLightTextureState *)0)->levels[0]) / sizeof(short) == 5) ? 1 : -1];
typedef char CarLightTextureState_TwoMasks_RecoveredCapacityCheck[(sizeof(((CarLightTextureState *)0)->channelMasks) == 2) ? 1 : -1];

typedef char g_carSteeringBlendLastGears_RecoveredCapacityCheck[(sizeof(g_carSteeringBlendLastGears) / sizeof(g_carSteeringBlendLastGears[0]) == 2) ? 1 : -1];
typedef char g_carSteeringBlendModes_RecoveredCapacityCheck[(sizeof(g_carSteeringBlendModes) / sizeof(g_carSteeringBlendModes[0]) == 2) ? 1 : -1];
typedef char g_carSteeringBlendFrames_RecoveredCapacityCheck[(sizeof(g_carSteeringBlendFrames) / sizeof(g_carSteeringBlendFrames[0]) == 2) ? 1 : -1];

// Shared glow renderer and exhaust views, verified against their writers/readers.
typedef char GlowLightSizeCheck[sizeof(GlowLight) == 0x5c ? 1 : -1];
typedef char GlowLight_type_OffsetCheck[offsetof(GlowLight, type) == 0x0 ? 1 : -1];
typedef char GlowLight_pos_OffsetCheck[offsetof(GlowLight, pos) == 0x4 ? 1 : -1];
typedef char GlowLight_dir_OffsetCheck[offsetof(GlowLight, dir) == 0x10 ? 1 : -1];
typedef char GlowLight_planePoint_OffsetCheck[offsetof(GlowLight, planePoint) == 0x1c ? 1 : -1];
typedef char GlowLight_planeNormal_OffsetCheck[offsetof(GlowLight, planeNormal) == 0x28 ? 1 : -1];
typedef char GlowLight_sizeX_OffsetCheck[offsetof(GlowLight, sizeX) == 0x34 ? 1 : -1];
typedef char GlowLight_sizeY_OffsetCheck[offsetof(GlowLight, sizeY) == 0x38 ? 1 : -1];
typedef char GlowLight_intensity_OffsetCheck[offsetof(GlowLight, intensity) == 0x3c ? 1 : -1];
typedef char GlowLight_projectedSizeScale_OffsetCheck[offsetof(GlowLight, projectedSizeScale) == 0x40 ? 1 : -1];
typedef char GlowLight_layerIntensity_OffsetCheck[offsetof(GlowLight, layerIntensity) == 0x44 ? 1 : -1];
typedef char GlowLight_pTexture_OffsetCheck[offsetof(GlowLight, pTexture) == 0x48 ? 1 : -1];
typedef char GlowLight_pLayerTexture_OffsetCheck[offsetof(GlowLight, pLayerTexture) == 0x4c ? 1 : -1];
typedef char GlowLight_enabled_OffsetCheck[offsetof(GlowLight, enabled) == 0x50 ? 1 : -1];
typedef char GlowLight_projectedBrightness_OffsetCheck[offsetof(GlowLight, projectedBrightness) == 0x51 ? 1 : -1];
typedef char GlowLight_field_0x52_OffsetCheck[offsetof(GlowLight, field_0x52) == 0x52 ? 1 : -1];
typedef char GlowLight_pNode_OffsetCheck[offsetof(GlowLight, pNode) == 0x54 ? 1 : -1];
typedef char GlowLight_field_0x58_OffsetCheck[offsetof(GlowLight, field_0x58) == 0x58 ? 1 : -1];
typedef char g_carExhaustPoints_CapacityCheck[sizeof(g_carExhaustPoints) == 64 ? 1 : -1];
typedef char g_carExhaustGlows_CapacityCheck[sizeof(g_carExhaustGlows) == 64 ? 1 : -1];
typedef char g_carExhaustWorldPositions_CapacityCheck[sizeof(g_carExhaustWorldPositions) == 96 ? 1 : -1];
typedef char g_carExhaustBurstFrames_CapacityCheck[sizeof(g_carExhaustBurstFrames) == 8 ? 1 : -1];
