#include <windows.h>
#include "Car.h"
#include "Sector.h"
#include "CarResources.h"
#include "CarPhysics.h"
#include "Game.h"
#include "CarParts.h"
#include "OptionPreviewGeometry.h"
#include "StageTiming.h"
#include "StageWeather.h"
#include "Stage.h"
#include "StageBlock.h"
#include "CarLightState.h"
#include "Glow.h"
#include "CarExhaust.h"
#include <stddef.h>
#include "LayoutChecks.h"

// Preserve the original Win32 layouts used by array indexing, bulk copies
// and packed callback tables. Keep these checks out of shared headers:
// extra declarations there can alter MSVC6 code generation in unrelated TUs.
CMR2_LAYOUT_CHECK(CarSizeCheck, sizeof(Car) == 0xc24);
CMR2_LAYOUT_CHECK(CarPositionOffsetCheck, offsetof(Car, position) == 0x2d0);
CMR2_LAYOUT_CHECK(CarWheelNodesOffsetCheck, offsetof(Car, pWheelNodes) == 0x738);
CMR2_LAYOUT_CHECK(CarWheelLoadOffsetCheck, offsetof(Car, wheelLoad) == 0x860);
CMR2_LAYOUT_CHECK(CarIndexOffsetCheck, offsetof(Car, index) == 0xb1a);
CMR2_LAYOUT_CHECK(CarCameraRejectionOffsetCheck, offsetof(Car, firstCameraBlocked) == 0xb68);
CMR2_LAYOUT_CHECK(CarRemoteFlagOffsetCheck, offsetof(Car, field_0xc1c) == 0xc1c);
CMR2_LAYOUT_CHECK(CallbackStateRecordSizeCheck, sizeof(CallbackStateRecord) == 8);
CMR2_LAYOUT_CHECK(CallbackStateTimerOffsetCheck, offsetof(CallbackStateRecord, elapsedTicks) == 4);
CMR2_LAYOUT_CHECK(StateCallbackPairSizeCheck, sizeof(StateCallbackPair) == 8);
CMR2_LAYOUT_CHECK(CallbackStateMachineSizeCheck, sizeof(CallbackStateMachine) == 0x10);
CMR2_LAYOUT_CHECK(CallbackStateRecordsOffsetCheck, offsetof(CallbackStateMachine, records) == 4);
CMR2_LAYOUT_CHECK(CallbackStateRulesOffsetCheck, offsetof(CallbackStateMachine, rules) == 0xc);
CMR2_LAYOUT_CHECK(SessionPlayerRecordSizeCheck, sizeof(SessionPlayerRecord) == 0xd0);
CMR2_LAYOUT_CHECK(CarPartSetSizeCheck, sizeof(CarPartSet) == 0x4d0);
CMR2_LAYOUT_CHECK(CarPartDamageValuesCheck, offsetof(CarPartSet, damageValues) == 0x240);
CMR2_LAYOUT_CHECK(CarPartDamageScalesCheck, offsetof(CarPartSet, damageScales) == 0x2c8);
CMR2_LAYOUT_CHECK(CarPartDamageBiasesCheck, offsetof(CarPartSet, damageBiases) == 0x350);
CMR2_LAYOUT_CHECK(CarPartWobbleCheck, offsetof(CarPartSet, steeringWobble) == 0x3d8);
CMR2_LAYOUT_CHECK(CarPartSuspensionCheck, offsetof(CarPartSet, suspensionDamageOffset) == 0x3dc);
CMR2_LAYOUT_CHECK(CarPartWheelDragCheck, offsetof(CarPartSet, wheelDamageDrag) == 0x3ec);
CMR2_LAYOUT_CHECK(CarPartFrontBrakeCheck, offsetof(CarPartSet, frontBrakeScale) == 0x3fc);
CMR2_LAYOUT_CHECK(CarPartRearBrakeCheck, offsetof(CarPartSet, rearBrakeScale) == 0x400);
CMR2_LAYOUT_CHECK(CarPartEngineTorqueCheck, offsetof(CarPartSet, engineTorqueScale) == 0x404);
CMR2_LAYOUT_CHECK(CarPartBodyDragCheck, offsetof(CarPartSet, bodyDamageDrag) == 0x408);
CMR2_LAYOUT_CHECK(CarPartBoundsCheck, offsetof(CarPartSet, maxX) == 0x410);
CMR2_LAYOUT_CHECK(CarPartBreakIndicesCheck, offsetof(CarPartSet, breakPartIndex) == 0x460);
CMR2_LAYOUT_CHECK(CarPartGearDamageCheck, offsetof(CarPartSet, gearShiftDamage) == 0x468);
CMR2_LAYOUT_CHECK(CarPartGlassCooldownCheck, offsetof(CarPartSet, glassCooldown) == 0x469);
CMR2_LAYOUT_CHECK(CarPartGlassEmittedCheck, offsetof(CarPartSet, glassDebrisEmitted) == 0x46c);
CMR2_LAYOUT_CHECK(CarPartDamagedCheck, offsetof(CarPartSet, partDamaged) == 0x470);
CMR2_LAYOUT_CHECK(CarPartBrokenCheck, offsetof(CarPartSet, partBroken) == 0x490);
CMR2_LAYOUT_CHECK(CarPartStateSizeCheck, sizeof(PartState) == 0x1a0);
CMR2_LAYOUT_CHECK(CarPartPrevMatrixCheck, offsetof(PartState, prevMatrix) == 0x4c);
CMR2_LAYOUT_CHECK(CarPartDrawMatrixCheck, offsetof(PartState, drawMatrix) == 0x8c);
CMR2_LAYOUT_CHECK(CarPartUpdateCheck, offsetof(PartState, update) == 0x110);
CMR2_LAYOUT_CHECK(CarPartFlagsCheck, offsetof(PartState, flags) == 0x150);
CMR2_LAYOUT_CHECK(CarPartStateTablesCheck, sizeof(CarPartStateTables) == 0x14);
CMR2_LAYOUT_CHECK(CarPartStateModesCheck, offsetof(CarPartStateTables, modes) == 0x10);
CMR2_LAYOUT_CHECK(CarDamageRecordSizeCheck, sizeof(CarDamageRecord) == 0x290);
CMR2_LAYOUT_CHECK(CarLineDescriptorSizeCheck, sizeof(CarFlexibleLineDescriptor) == 0x20);
CMR2_LAYOUT_CHECK(CarLineAxisCheck, offsetof(CarFlexibleLineDescriptor, axis) == 0xc);
CMR2_LAYOUT_CHECK(CarLineLengthCheck, offsetof(CarFlexibleLineDescriptor, length) == 0x18);
CMR2_LAYOUT_CHECK(CarLineColourCheck, offsetof(CarFlexibleLineDescriptor, colour) == 0x1c);
CMR2_LAYOUT_CHECK(CarLineStateSizeCheck, sizeof(CarFlexibleLineState) == 0x3c);
CMR2_LAYOUT_CHECK(CarLineStateAllocationCheck, 3 * sizeof(CarFlexibleLineState) == 0xb4);
CMR2_LAYOUT_CHECK(CarLinePreviousCheck, offsetof(CarFlexibleLineState, previousPosition) == 0xc);
CMR2_LAYOUT_CHECK(CarLineDrawCheck, offsetof(CarFlexibleLineState, drawPosition) == 0x18);
CMR2_LAYOUT_CHECK(CarLineEndCheck, offsetof(CarFlexibleLineState, groundEnd) == 0x24);
CMR2_LAYOUT_CHECK(CarLineVelocityXCheck, offsetof(CarFlexibleLineState, velocityX) == 0x30);
CMR2_LAYOUT_CHECK(CarLineVelocityZCheck, offsetof(CarFlexibleLineState, velocityZ) == 0x34);
CMR2_LAYOUT_CHECK(CarLineGroundedCheck, offsetof(CarFlexibleLineState, grounded) == 0x38);
CMR2_LAYOUT_CHECK(SceneNodeSizeCheck, sizeof(SceneNode) == 0x18c);
CMR2_LAYOUT_CHECK(SceneNodeViewMaskCheck, offsetof(SceneNode, viewMask) == 0x17c);
CMR2_LAYOUT_CHECK(CarPartHiddenCheck, offsetof(CarPartSet, partHidden) == 0x4b0);
CMR2_LAYOUT_CHECK(CarLineGroundFlagsCheck, offsetof(CarPartSet, lineGrounded) == 0x4c0);
CMR2_LAYOUT_CHECK(CarPartRadiusCheck, offsetof(PartState, boundsRadius) == 0x15c);
CMR2_LAYOUT_CHECK(CarDamageLinkSizeCheck, sizeof(CarDamageLink) == 0xd);
CMR2_LAYOUT_CHECK(CarDamageLinkPoolSizeCheck, sizeof(CarDamageLinkPool) == 0x106);
CMR2_LAYOUT_CHECK(CarDamageLinkCountCheck, offsetof(CarDamageLinkPool, count) == 0x104);
CMR2_LAYOUT_CHECK(CarDamageFirstLinkCheck, offsetof(CarDamageLinkPool, firstLink) == 0x105);
CMR2_LAYOUT_CHECK(CarDamageSnapshotSizeCheck, sizeof(CarDamageSnapshot) == 0x40);
CMR2_LAYOUT_CHECK(CarDamageHiddenCheck, offsetof(CarDamageSnapshot, partHidden) == 0x24);
CMR2_LAYOUT_CHECK(CarDamageGroundFlagsCheck, offsetof(CarDamageSnapshot, lineGrounded) == 0x34);
CMR2_LAYOUT_CHECK(CarDamageStageImpactsCheck, offsetof(CarDamageRecord, stageImpacts) == 0x106);
CMR2_LAYOUT_CHECK(CarDamageActiveStateCheck, offsetof(CarDamageRecord, damage) == 0x20c);
CMR2_LAYOUT_CHECK(CarDamageStageStateCheck, offsetof(CarDamageRecord, stageDamage) == 0x24c);
CMR2_LAYOUT_CHECK(CarDamageStageCapturedCheck, offsetof(CarDamageRecord, stageSnapshotCaptured) == 0x28c);

// Motor, controls and gearbox fields recovered from readers and writers.
CMR2_LAYOUT_CHECK(CarRecovered_collisionRadius, offsetof(Car, collisionRadius) == 0x758);
CMR2_LAYOUT_CHECK(CarRecovered_mass, offsetof(Car, mass) == 0x75c);
CMR2_LAYOUT_CHECK(CarRecovered_inverseMass, offsetof(Car, inverseMass) == 0x760);
CMR2_LAYOUT_CHECK(CarRecovered_engineNetTorque, offsetof(Car, engineNetTorque) == 0x780);
CMR2_LAYOUT_CHECK(CarRecovered_engineDragCoefficient, offsetof(Car, engineDragCoefficient) == 0x784);
CMR2_LAYOUT_CHECK(CarRecovered_maxThrottleTorque, offsetof(Car, maxThrottleTorque) == 0x788);
CMR2_LAYOUT_CHECK(CarRecovered_baseThrottleTorque, offsetof(Car, baseThrottleTorque) == 0x78c);
CMR2_LAYOUT_CHECK(CarRecovered_throttleRampStep, offsetof(Car, throttleRampStep) == 0x790);
CMR2_LAYOUT_CHECK(CarRecovered_engineSpeedLimit, offsetof(Car, engineSpeedLimit) == 0x794);
CMR2_LAYOUT_CHECK(CarRecovered_throttleTorque, offsetof(Car, throttleTorque) == 0x79c);
CMR2_LAYOUT_CHECK(CarRecovered_throttlePhase, offsetof(Car, throttlePhase) == 0x7a0);
CMR2_LAYOUT_CHECK(CarRecovered_engineSpeed, offsetof(Car, engineSpeed) == 0x7a4);
CMR2_LAYOUT_CHECK(CarRecovered_revLimiterTorque, offsetof(Car, revLimiterTorque) == 0x7b0);
CMR2_LAYOUT_CHECK(CarRecovered_baseDriveSplit, offsetof(Car, baseDriveSplit) == 0x7b8);
CMR2_LAYOUT_CHECK(CarRecovered_gearRatio, offsetof(Car, gearRatio) == 0x7bc);
CMR2_LAYOUT_CHECK(CarRecovered_steeringInput, offsetof(Car, steeringInput) == 0x818);
CMR2_LAYOUT_CHECK(CarRecovered_steeringTorqueScale, offsetof(Car, steeringTorqueScale) == 0x824);
CMR2_LAYOUT_CHECK(CarRecovered_steeringSpeedScale, offsetof(Car, steeringSpeedScale) == 0x828);
CMR2_LAYOUT_CHECK(CarRecovered_maxBrakeForce, offsetof(Car, maxBrakeForce) == 0x82c);
CMR2_LAYOUT_CHECK(CarRecovered_brakeRampStep, offsetof(Car, brakeRampStep) == 0x834);
CMR2_LAYOUT_CHECK(CarRecovered_brakePhase, offsetof(Car, brakePhase) == 0x83c);
CMR2_LAYOUT_CHECK(CarRecovered_handbrakeRampStep, offsetof(Car, handbrakeRampStep) == 0x840);
CMR2_LAYOUT_CHECK(CarRecovered_maxHandbrakeForce, offsetof(Car, maxHandbrakeForce) == 0x844);
CMR2_LAYOUT_CHECK(CarRecovered_handbrakePhase, offsetof(Car, handbrakePhase) == 0x84c);
CMR2_LAYOUT_CHECK(CarRecovered_wheelSpinForWheelLean, offsetof(Car, wheelSpinForWheelLean) == 0x890);
CMR2_LAYOUT_CHECK(CarRecovered_wheelSpinForBodyLean, offsetof(Car, wheelSpinForBodyLean) == 0x8a0);
CMR2_LAYOUT_CHECK(CarRecovered_groundHeightCorrection, offsetof(Car, groundHeightCorrection) == 0x958);
CMR2_LAYOUT_CHECK(CarRecovered_wheelLeanDamping, offsetof(Car, wheelLeanDamping) == 0x9b8);
CMR2_LAYOUT_CHECK(CarRecovered_bodyLeanDamping, offsetof(Car, bodyLeanDamping) == 0x9bc);
CMR2_LAYOUT_CHECK(CarRecovered_cheatWheelDrop, offsetof(Car, cheatWheelDrop) == 0xa88);
CMR2_LAYOUT_CHECK(CarRecovered_cheatBodyLift, offsetof(Car, cheatBodyLift) == 0xa8c);
CMR2_LAYOUT_CHECK(CarRecovered_previousWheelSurface, offsetof(Car, previousWheelSurface) == 0xabe);
CMR2_LAYOUT_CHECK(CarRecovered_engineStartTimer, offsetof(Car, engineStartTimer) == 0xafe);
CMR2_LAYOUT_CHECK(CarRecovered_requestedGear, offsetof(Car, requestedGear) == 0xb20);
CMR2_LAYOUT_CHECK(CarRecovered_autoShiftDelay, offsetof(Car, autoShiftDelay) == 0xb21);
CMR2_LAYOUT_CHECK(CarRecovered_lastShiftDirection, offsetof(Car, lastShiftDirection) == 0xb22);
CMR2_LAYOUT_CHECK(CarRecovered_damageShiftDelay, offsetof(Car, damageShiftDelay) == 0xb24);
CMR2_LAYOUT_CHECK(CarRecovered_engineRestartPending, offsetof(Car, engineRestartPending) == 0xb4c);
CMR2_LAYOUT_CHECK(CarRecovered_braking, offsetof(Car, braking) == 0xb54);
CMR2_LAYOUT_CHECK(CarRecovered_reversing, offsetof(Car, reversing) == 0xb5c);
CMR2_LAYOUT_CHECK(CarRecovered_revLimiterActive, offsetof(Car, revLimiterActive) == 0xb78);
CMR2_LAYOUT_CHECK(CarRecovered_shiftInProgress, offsetof(Car, shiftInProgress) == 0xb84);
CMR2_LAYOUT_CHECK(CarRecovered_automaticReverse, offsetof(Car, automaticReverse) == 0xb94);
CMR2_LAYOUT_CHECK(CarRecovered_gearAtOrBelowBest, offsetof(Car, gearAtOrBelowBest) == 0xb98);
CMR2_LAYOUT_CHECK(CarRecovered_automaticGearbox, offsetof(Car, automaticGearbox) == 0xb9c);
CMR2_LAYOUT_CHECK(CarRecovered_useUpperCollisionCorners, offsetof(Car, useUpperCollisionCorners) == 0xc00);
CMR2_LAYOUT_CHECK(CarRecovered_bodySize, offsetof(Car, bodySize) == 0x1f8);
CMR2_LAYOUT_CHECK(CarRecovered_upperCornersLocal, offsetof(Car, upperCornersLocal) == 0x240);
CMR2_LAYOUT_CHECK(CarRecovered_groundRightDot, offsetof(Car, groundRightDot) == 0x91c);
CMR2_LAYOUT_CHECK(CarRecovered_groundUpDot, offsetof(Car, groundUpDot) == 0x920);
CMR2_LAYOUT_CHECK(CarRecovered_groundForwardDot, offsetof(Car, groundForwardDot) == 0x924);
CMR2_LAYOUT_CHECK(CarRecovered_deepestCorner, offsetof(Car, deepestCorner) == 0xb2b);
CMR2_LAYOUT_CHECK(CarRecovered_firstCameraBlocked, offsetof(Car, firstCameraBlocked) == 0xb68);
CMR2_LAYOUT_CHECK(CarRecovered_steeringAccumulator, offsetof(Car, steeringAccumulator) == 0x81c);
CMR2_LAYOUT_CHECK(CarRecovered_steeringReturnRate, offsetof(Car, steeringReturnRate) == 0x820);
CMR2_LAYOUT_CHECK(CarRecovered_wheelSteeringAngle, offsetof(Car, wheelSteeringAngle) == 0xb10);
CMR2_LAYOUT_CHECK(CarRecovered_targetSteeringAngle, offsetof(Car, targetSteeringAngle) == 0xb12);
CMR2_LAYOUT_CHECK(CarRecovered_renderSteeringAngle, offsetof(Car, renderSteeringAngle) == 0xb14);
CMR2_LAYOUT_CHECK(CarRecovered_maxSteeringAngleDegrees, offsetof(Car, maxSteeringAngleDegrees) == 0xb16);
CMR2_LAYOUT_CHECK(CarNetRecordSizeCheck, sizeof(CarNetRecord) == 0xec);
CMR2_LAYOUT_CHECK(CarNetSteeringCheck, offsetof(CarNetRecord, wheelSteeringAngle) == 0xc4);
CMR2_LAYOUT_CHECK(CarNetThrottleCheck, offsetof(CarNetRecord, throttleTorque) == 0xb8);
CMR2_LAYOUT_CHECK(CarNetBrakingCheck, offsetof(CarNetRecord, braking) == 0xd0);
CMR2_LAYOUT_CHECK(CarNetUpperCornersCheck, offsetof(CarNetRecord, useUpperCollisionCorners) == 0xd4);

// Typed render snapshots and the four 0x18-byte wheel records they contain.
CMR2_LAYOUT_CHECK(CarWheelRecordSizeCheck, sizeof(CarWheelRecord) == 0x18);
CMR2_LAYOUT_CHECK(CarWheelTiltOffsetCheck, offsetof(CarWheelRecord, tiltDegrees) == 0xc);
CMR2_LAYOUT_CHECK(CarWheelSteeringOffsetCheck, offsetof(CarWheelRecord, steeringDegrees) == 0x10);
CMR2_LAYOUT_CHECK(CarWheelSpinOffsetCheck, offsetof(CarWheelRecord, spinDegrees) == 0x14);
CMR2_LAYOUT_CHECK(CarTransformsSizeCheck, sizeof(CarTransforms) == 0xfc);
CMR2_LAYOUT_CHECK(CarTransformsBody2Check, offsetof(CarTransforms, body2) == 0x40);
CMR2_LAYOUT_CHECK(CarTransformsWheelsCheck, offsetof(CarTransforms, wheels) == 0x80);
CMR2_LAYOUT_CHECK(CarTransformsNormalCheck, offsetof(CarTransforms, groundNormal) == 0xe0);
CMR2_LAYOUT_CHECK(CarTransformsHeightsCheck, offsetof(CarTransforms, cornerHeight) == 0xec);
CMR2_LAYOUT_CHECK(CarRenderBoxStrideCheck, 8 * sizeof(FixVector) == 0x60);

CMR2_LAYOUT_CHECK(CarSimulationInterpolationCheck, offsetof(Car, simulationInterpolation) == 0xa90);
CMR2_LAYOUT_CHECK(CarSimulationRateCheck, offsetof(Car, simulationRateHz) == 0xa98);
CMR2_LAYOUT_CHECK(CarSimulationStepsCheck, offsetof(Car, simulationStepsRemaining) == 0xb43);

// Car contact patches, shadows and skid range flags.
CMR2_LAYOUT_CHECK(CarContactSizeCheck, sizeof(CarContact) == 0x2a4);
CMR2_LAYOUT_CHECK(CarContactFrontMidCheck, offsetof(CarContact, wheelFrontMid) == 0x198);
CMR2_LAYOUT_CHECK(CarContactRearMidCheck, offsetof(CarContact, wheelRearMid) == 0x1c8);
CMR2_LAYOUT_CHECK(CarContactShadowCheck, offsetof(CarContact, shadowLevel) == 0x250);
CMR2_LAYOUT_CHECK(CarContactGhostCheck, offsetof(CarContact, ghostContact) == 0x294);
CMR2_LAYOUT_CHECK(CarContactWheelsCheck, offsetof(CarContact, wheelPatchesEnabled) == 0x298);
CMR2_LAYOUT_CHECK(CarContactSkidOffsetCheck, offsetof(CarContact, skidIndexOffset) == 0x29c);
CMR2_LAYOUT_CHECK(CarContactSkidDirectionCheck, offsetof(CarContact, skidRangeAscending) == 0x2a0);

// Scene records and the composite stage-car resource block.
CMR2_LAYOUT_CHECK(CarSceneRecordSizeCheck, sizeof(CarSceneRecord) == 0x24);
CMR2_LAYOUT_CHECK(CarSceneRecord_bodyNodeCheck, offsetof(CarSceneRecord, bodyNode) == 0x4);
CMR2_LAYOUT_CHECK(CarSceneRecord_rootNodeCheck, offsetof(CarSceneRecord, rootNode) == 0x8);
CMR2_LAYOUT_CHECK(CarSceneRecord_alternateWheelSceneCheck, offsetof(CarSceneRecord, alternateWheelScene) == 0xc);
CMR2_LAYOUT_CHECK(CarSceneRecord_originalWheelObjectsCheck, offsetof(CarSceneRecord, originalWheelObjects) == 0x10);
CMR2_LAYOUT_CHECK(CarSceneRecord_detailCodeCheck, offsetof(CarSceneRecord, detailCode) == 0x20);
CMR2_LAYOUT_CHECK(CarSceneRecord_variantCodeCheck, offsetof(CarSceneRecord, variantCode) == 0x21);
CMR2_LAYOUT_CHECK(g_carScenesCapacityCheck, sizeof(g_carScenes) / sizeof(g_carScenes[0]) == 16);
CMR2_LAYOUT_CHECK(g_carAuxiliaryBuffersCapacityCheck, sizeof(g_carAuxiliaryBuffers) / sizeof(g_carAuxiliaryBuffers[0]) == 16);
CMR2_LAYOUT_CHECK(g_carAlternateBodyScenesCapacityCheck, sizeof(g_carAlternateBodyScenes) / sizeof(g_carAlternateBodyScenes[0]) == 16);
CMR2_LAYOUT_CHECK(g_carWheelModelBuffersCapacityCheck, sizeof(g_carWheelModelBuffers) / sizeof(g_carWheelModelBuffers[0]) == 16);
CMR2_LAYOUT_CHECK(g_carAlternateBodyBuffersCapacityCheck, sizeof(g_carAlternateBodyBuffers) / sizeof(g_carAlternateBodyBuffers[0]) == 16);
CMR2_LAYOUT_CHECK(g_carModelBuffersCapacityCheck, sizeof(g_carModelBuffers) / sizeof(g_carModelBuffers[0]) == 16);
CMR2_LAYOUT_CHECK(g_carInfoBuffersCapacityCheck, sizeof(g_carInfoBuffers) / sizeof(g_carInfoBuffers[0]) == 8);

// Scene binding and matrix identities established by model load and reload.
CMR2_LAYOUT_CHECK(CarBinding_physicsMatrixCheck, offsetof(Car, physicsMatrix) == 0x0);
CMR2_LAYOUT_CHECK(CarBinding_bodyMatrixCheck, offsetof(Car, bodyMatrix) == 0x40);
CMR2_LAYOUT_CHECK(CarBinding_pSceneRootCheck, offsetof(Car, pSceneRoot) == 0x71c);
CMR2_LAYOUT_CHECK(CarBinding_pBodyNodeCheck, offsetof(Car, pBodyNode) == 0x720);
CMR2_LAYOUT_CHECK(CarBinding_pAlternateBodyNodeCheck, offsetof(Car, pAlternateBodyNode) == 0x724);

// Weather, lighting and precipitation layouts recovered as one family.
CMR2_LAYOUT_CHECK(ViewWeatherStateSizeCheck, sizeof(ViewWeatherState) == 0x178);
CMR2_LAYOUT_CHECK(ViewWeatherState_kindOffsetCheck, offsetof(ViewWeatherState, kind) == 0x0);
CMR2_LAYOUT_CHECK(ViewWeatherState_targetKindOffsetCheck, offsetof(ViewWeatherState, targetKind) == 0x4);
CMR2_LAYOUT_CHECK(ViewWeatherState_centreOffsetCheck, offsetof(ViewWeatherState, centre) == 0x8);
CMR2_LAYOUT_CHECK(ViewWeatherState_previousCentreOffsetCheck, offsetof(ViewWeatherState, previousCentre) == 0x14);
CMR2_LAYOUT_CHECK(ViewWeatherState_relativeVelocityOffsetCheck, offsetof(ViewWeatherState, relativeVelocity) == 0x20);
CMR2_LAYOUT_CHECK(ViewWeatherState_velocityOffsetCheck, offsetof(ViewWeatherState, velocity) == 0x2c);
CMR2_LAYOUT_CHECK(ViewWeatherState_snowSwayAxisOffsetCheck, offsetof(ViewWeatherState, snowSwayAxis) == 0x38);
CMR2_LAYOUT_CHECK(ViewWeatherState_splashDisplacementOffsetCheck, offsetof(ViewWeatherState, splashDisplacement) == 0x44);
CMR2_LAYOUT_CHECK(ViewWeatherState_inverseFallDisplacementOffsetCheck, offsetof(ViewWeatherState, inverseFallDisplacement) == 0x50);
CMR2_LAYOUT_CHECK(ViewWeatherState_intensityOffsetCheck, offsetof(ViewWeatherState, intensity) == 0x54);
CMR2_LAYOUT_CHECK(ViewWeatherState_particleCountOffsetCheck, offsetof(ViewWeatherState, particleCount) == 0x58);
CMR2_LAYOUT_CHECK(ViewWeatherState_targetParticleCountOffsetCheck, offsetof(ViewWeatherState, targetParticleCount) == 0x5c);
CMR2_LAYOUT_CHECK(ViewWeatherState_particleCountChangeRateOffsetCheck, offsetof(ViewWeatherState, particleCountChangeRate) == 0x60);
CMR2_LAYOUT_CHECK(ViewWeatherState_precipitationFadeOffsetCheck, offsetof(ViewWeatherState, precipitationFade) == 0x64);
CMR2_LAYOUT_CHECK(ViewWeatherState_sunVisibilityOffsetCheck, offsetof(ViewWeatherState, sunVisibility) == 0x68);
CMR2_LAYOUT_CHECK(ViewWeatherState_routePositionOffsetCheck, offsetof(ViewWeatherState, routePosition) == 0x6c);
CMR2_LAYOUT_CHECK(ViewWeatherState_lastRoutePositionOffsetCheck, offsetof(ViewWeatherState, lastRoutePosition) == 0x70);
CMR2_LAYOUT_CHECK(ViewWeatherState_particleCapacityOffsetCheck, offsetof(ViewWeatherState, particleCapacity) == 0x74);
CMR2_LAYOUT_CHECK(ViewWeatherState_firstParticleOffsetCheck, offsetof(ViewWeatherState, firstParticle) == 0x76);
CMR2_LAYOUT_CHECK(ViewWeatherState_groundTrianglesOffsetCheck, offsetof(ViewWeatherState, groundTriangles) == 0x78);
CMR2_LAYOUT_CHECK(ViewWeatherState_field_0xaaOffsetCheck, offsetof(ViewWeatherState, field_0xaa) == 0xaa);
CMR2_LAYOUT_CHECK(ViewWeatherState_groundHeightsOffsetCheck, offsetof(ViewWeatherState, groundHeights) == 0xac);
CMR2_LAYOUT_CHECK(ViewWeatherState_relativeGroundHeightsOffsetCheck, offsetof(ViewWeatherState, relativeGroundHeights) == 0x110);
CMR2_LAYOUT_CHECK(ViewWeatherState_shelteredOffsetCheck, offsetof(ViewWeatherState, sheltered) == 0x174);
CMR2_LAYOUT_CHECK(ViewLightingRampSizeCheck, sizeof(ViewLightingRamp) == 0x2c);
CMR2_LAYOUT_CHECK(ViewLightingRamp_routePositionOffsetCheck, offsetof(ViewLightingRamp, routePosition) == 0x0);
CMR2_LAYOUT_CHECK(ViewLightingRamp_lastRoutePositionOffsetCheck, offsetof(ViewLightingRamp, lastRoutePosition) == 0x4);
CMR2_LAYOUT_CHECK(ViewLightingRamp_routeBlendOffsetCheck, offsetof(ViewLightingRamp, routeBlend) == 0x8);
CMR2_LAYOUT_CHECK(ViewLightingRamp_routeBlendOffsetOffsetCheck, offsetof(ViewLightingRamp, routeBlendOffset) == 0xc);
CMR2_LAYOUT_CHECK(ViewLightingRamp_blendOffsetCheck, offsetof(ViewLightingRamp, blend) == 0x10);
CMR2_LAYOUT_CHECK(ViewLightingRamp_sunYawOffsetCheck, offsetof(ViewLightingRamp, sunYaw) == 0x14);
CMR2_LAYOUT_CHECK(ViewLightingRamp_previousBlendOffsetCheck, offsetof(ViewLightingRamp, previousBlend) == 0x18);
CMR2_LAYOUT_CHECK(ViewLightingRamp_drawBlendOffsetCheck, offsetof(ViewLightingRamp, drawBlend) == 0x1c);
CMR2_LAYOUT_CHECK(ViewLightingRamp_previousSunYawOffsetCheck, offsetof(ViewLightingRamp, previousSunYaw) == 0x20);
CMR2_LAYOUT_CHECK(ViewLightingRamp_drawSunYawOffsetCheck, offsetof(ViewLightingRamp, drawSunYaw) == 0x24);
CMR2_LAYOUT_CHECK(ViewLightingRamp_lightingDirtyOffsetCheck, offsetof(ViewLightingRamp, lightingDirty) == 0x28);
CMR2_LAYOUT_CHECK(CarSurfaceRampSizeCheck, sizeof(CarSurfaceRamp) == 0xc);
CMR2_LAYOUT_CHECK(CarSurfaceRamp_routePositionOffsetCheck, offsetof(CarSurfaceRamp, routePosition) == 0x0);
CMR2_LAYOUT_CHECK(CarSurfaceRamp_lastRoutePositionOffsetCheck, offsetof(CarSurfaceRamp, lastRoutePosition) == 0x4);
CMR2_LAYOUT_CHECK(CarSurfaceRamp_blendOffsetCheck, offsetof(CarSurfaceRamp, blend) == 0x8);
CMR2_LAYOUT_CHECK(WeatherWindTransitionSizeCheck, sizeof(WeatherWindTransition) == 0xc);
CMR2_LAYOUT_CHECK(WeatherWindTransition_targetStrengthOffsetCheck, offsetof(WeatherWindTransition, targetStrength) == 0x0);
CMR2_LAYOUT_CHECK(WeatherWindTransition_changeRateOffsetCheck, offsetof(WeatherWindTransition, changeRate) == 0x4);
CMR2_LAYOUT_CHECK(WeatherWindTransition_holdTimeOffsetCheck, offsetof(WeatherWindTransition, holdTime) == 0x8);
CMR2_LAYOUT_CHECK(StageLightPresetSizeCheck, sizeof(StageLightPreset) == 0x48);
CMR2_LAYOUT_CHECK(StageLightPreset_meshHeightParametersOffsetCheck, offsetof(StageLightPreset, meshHeightParameters) == 0x0);
CMR2_LAYOUT_CHECK(StageLightPreset_field_0xcOffsetCheck, offsetof(StageLightPreset, field_0xc) == 0xc);
CMR2_LAYOUT_CHECK(StageLightPreset_sunIconSizeOffsetCheck, offsetof(StageLightPreset, sunIconSize) == 0x10);
CMR2_LAYOUT_CHECK(StageLightPreset_fogStartOffsetCheck, offsetof(StageLightPreset, fogStart) == 0x14);
CMR2_LAYOUT_CHECK(StageLightPreset_fogEndOffsetCheck, offsetof(StageLightPreset, fogEnd) == 0x18);
CMR2_LAYOUT_CHECK(StageLightPreset_colourOffsetCheck, offsetof(StageLightPreset, colour) == 0x1c);
CMR2_LAYOUT_CHECK(StageLightingValuesSizeCheck, sizeof(StageLightingValues) == 0xb4);
CMR2_LAYOUT_CHECK(StageLightingValues_lowColourOffsetCheck, offsetof(StageLightingValues, lowColour) == 0x0);
CMR2_LAYOUT_CHECK(StageLightingValues_highColourDeltaOffsetCheck, offsetof(StageLightingValues, highColourDelta) == 0xc);
CMR2_LAYOUT_CHECK(StageLightingValues_heightReferenceColourOffsetCheck, offsetof(StageLightingValues, heightReferenceColour) == 0x18);
CMR2_LAYOUT_CHECK(StageLightingValues_sunIconColourOffsetCheck, offsetof(StageLightingValues, sunIconColour) == 0x24);
CMR2_LAYOUT_CHECK(StageLightingValues_groundColourOffsetCheck, offsetof(StageLightingValues, groundColour) == 0x30);
CMR2_LAYOUT_CHECK(StageLightingValues_objectColourOffsetCheck, offsetof(StageLightingValues, objectColour) == 0x3c);
CMR2_LAYOUT_CHECK(StageLightingValues_ambientColourOffsetCheck, offsetof(StageLightingValues, ambientColour) == 0x48);
CMR2_LAYOUT_CHECK(StageLightingValues_lightColourOffsetCheck, offsetof(StageLightingValues, lightColour) == 0x54);
CMR2_LAYOUT_CHECK(StageLightingValues_mesh5ColourOffsetCheck, offsetof(StageLightingValues, mesh5Colour) == 0x60);
CMR2_LAYOUT_CHECK(StageLightingValues_meshHeightParametersOffsetCheck, offsetof(StageLightingValues, meshHeightParameters) == 0x6c);
CMR2_LAYOUT_CHECK(StageLightingValues_fogColourOffsetCheck, offsetof(StageLightingValues, fogColour) == 0x78);
CMR2_LAYOUT_CHECK(StageLightingValues_skyColourOffsetCheck, offsetof(StageLightingValues, skyColour) == 0x84);
CMR2_LAYOUT_CHECK(StageLightingValues_skyAlphaOffsetCheck, offsetof(StageLightingValues, skyAlpha) == 0x90);
CMR2_LAYOUT_CHECK(StageLightingValues_fogStartOffsetCheck, offsetof(StageLightingValues, fogStart) == 0x94);
CMR2_LAYOUT_CHECK(StageLightingValues_fogEndOffsetCheck, offsetof(StageLightingValues, fogEnd) == 0x98);
CMR2_LAYOUT_CHECK(StageLightingValues_heightReferenceBlendOffsetCheck, offsetof(StageLightingValues, heightReferenceBlend) == 0x9c);
CMR2_LAYOUT_CHECK(StageLightingValues_groundReferenceBlendOffsetCheck, offsetof(StageLightingValues, groundReferenceBlend) == 0xa0);
CMR2_LAYOUT_CHECK(StageLightingValues_objectAlphaOffsetCheck, offsetof(StageLightingValues, objectAlpha) == 0xa4);
CMR2_LAYOUT_CHECK(StageLightingValues_mesh5AlphaOffsetCheck, offsetof(StageLightingValues, mesh5Alpha) == 0xa8);
CMR2_LAYOUT_CHECK(StageLightingValues_sunIconSizeOffsetCheck, offsetof(StageLightingValues, sunIconSize) == 0xac);
CMR2_LAYOUT_CHECK(StageLightingValues_intensityOffsetCheck, offsetof(StageLightingValues, intensity) == 0xb0);
CMR2_LAYOUT_CHECK(StageLightingStateSizeCheck, sizeof(StageLightingState) == 0x178);
CMR2_LAYOUT_CHECK(StageLightingState_primaryOffsetCheck, offsetof(StageLightingState, primary) == 0x0);
CMR2_LAYOUT_CHECK(StageLightingState_secondaryOffsetCheck, offsetof(StageLightingState, secondary) == 0xb4);
CMR2_LAYOUT_CHECK(StageLightingState_blendOffsetCheck, offsetof(StageLightingState, blend) == 0x168);
CMR2_LAYOUT_CHECK(StageLightingState_intensityOffsetCheck, offsetof(StageLightingState, intensity) == 0x16c);
CMR2_LAYOUT_CHECK(StageLightingState_lightningSectorOffsetCheck, offsetof(StageLightingState, lightningSector) == 0x170);
CMR2_LAYOUT_CHECK(StageLightingState_previousLightningSectorOffsetCheck, offsetof(StageLightingState, previousLightningSector) == 0x172);
CMR2_LAYOUT_CHECK(StageLightingState_fogEnabledOffsetCheck, offsetof(StageLightingState, fogEnabled) == 0x174);
CMR2_LAYOUT_CHECK(StageWeatherParticleSizeCheck, sizeof(StageWeatherParticle) == 0x24);
CMR2_LAYOUT_CHECK(StageWeatherParticle_xOffsetCheck, offsetof(StageWeatherParticle, x) == 0x0);
CMR2_LAYOUT_CHECK(StageWeatherParticle_yOffsetCheck, offsetof(StageWeatherParticle, y) == 0x4);
CMR2_LAYOUT_CHECK(StageWeatherParticle_zOffsetCheck, offsetof(StageWeatherParticle, z) == 0x8);
CMR2_LAYOUT_CHECK(StageWeatherParticle_spinOffsetCheck, offsetof(StageWeatherParticle, spin) == 0xc);
CMR2_LAYOUT_CHECK(StageWeatherParticle_swayAmplitudeOffsetCheck, offsetof(StageWeatherParticle, swayAmplitude) == 0x10);
CMR2_LAYOUT_CHECK(StageWeatherParticle_snowPhaseDegreesOffsetCheck, offsetof(StageWeatherParticle, snowPhaseDegrees) == 0x14);
CMR2_LAYOUT_CHECK(StageWeatherParticle_splashGroundHeightOffsetCheck, offsetof(StageWeatherParticle, splashGroundHeight) == 0x14);
CMR2_LAYOUT_CHECK(StageWeatherParticle_scaleOffsetCheck, offsetof(StageWeatherParticle, scale) == 0x18);
CMR2_LAYOUT_CHECK(StageWeatherParticle_field_0x1cOffsetCheck, offsetof(StageWeatherParticle, field_0x1c) == 0x1c);
CMR2_LAYOUT_CHECK(StageWeatherParticle_textureVariantOffsetCheck, offsetof(StageWeatherParticle, textureVariant) == 0x1d);
CMR2_LAYOUT_CHECK(StageWeatherParticle_field_0x1eOffsetCheck, offsetof(StageWeatherParticle, field_0x1e) == 0x1e);
CMR2_LAYOUT_CHECK(StageWeatherParticle_wrappedOffsetCheck, offsetof(StageWeatherParticle, wrapped) == 0x20);
CMR2_LAYOUT_CHECK(WeatherParticlePoolCapacityCheck, sizeof(g_weatherParticles) / sizeof(g_weatherParticles[0]) == 400);
CMR2_LAYOUT_CHECK(WeatherTerrainCacheCapacityCheck, sizeof(((ViewWeatherState *)0)->groundTriangles) / sizeof(short) == 25);

// Part geometry and countdown fields consumed by the car damage/render chain.
CMR2_LAYOUT_CHECK(CarPartVertexGeometrySizeCheck, sizeof(DeformVertex) == 0x20);
CMR2_LAYOUT_CHECK(CarPartFloatVertexGeometrySizeCheck, sizeof(DeformFloatVertex) == 0x30);
CMR2_LAYOUT_CHECK(MeshTriangleGeometrySizeCheck, sizeof(MeshTriangle) == 0x4c);
CMR2_LAYOUT_CHECK(MeshGeometrySizeCheck, sizeof(Mesh) == 0x120);
CMR2_LAYOUT_CHECK(CarPartSet_meshes_GeometryOffsetCheck, offsetof(CarPartSet, geometry) + offsetof(DeformMeshSources, meshes) == 0x0);
CMR2_LAYOUT_CHECK(CarPartSet_nodes_GeometryOffsetCheck, offsetof(CarPartSet, geometry) + offsetof(DeformMeshSources, nodes) == 0x3c);
CMR2_LAYOUT_CHECK(CarPartSet_vertices_GeometryOffsetCheck, offsetof(CarPartSet, geometry) + offsetof(DeformMeshSources, vertices) == 0x78);
CMR2_LAYOUT_CHECK(CarPartSet_centres_GeometryOffsetCheck, offsetof(CarPartSet, centres) == 0xb4);
CMR2_LAYOUT_CHECK(CarPartSet_halfExtents_GeometryOffsetCheck, offsetof(CarPartSet, halfExtents) == 0x168);
CMR2_LAYOUT_CHECK(CarPartSet_damageGrid_GeometryOffsetCheck, offsetof(CarPartSet, damageGrid) == 0x21c);
CMR2_LAYOUT_CHECK(CarPartSet_brokenLightFlickerTimer_GeometryOffsetCheck, offsetof(CarPartSet, brokenLightFlickerTimer) == 0x40c);
CMR2_LAYOUT_CHECK(CarPartSet_vertexCount_GeometryOffsetCheck, offsetof(CarPartSet, vertexCount) == 0x420);
CMR2_LAYOUT_CHECK(CarPartSet_count_GeometryOffsetCheck, offsetof(CarPartSet, count) == 0x45c);
CMR2_LAYOUT_CHECK(CarPartSet_brokenLightFlickerPhase_GeometryOffsetCheck, offsetof(CarPartSet, brokenLightFlickerPhase) == 0x4cc);
CMR2_LAYOUT_CHECK(CarPartVertex_pos_GeometryOffsetCheck, offsetof(DeformVertex, pos) == 0x0);
CMR2_LAYOUT_CHECK(CarPartVertex_normal_GeometryOffsetCheck, offsetof(DeformVertex, normal) == 0xc);
CMR2_LAYOUT_CHECK(CarPartVertex_normal8_GeometryOffsetCheck, offsetof(DeformVertex, normal8) == 0x18);
CMR2_LAYOUT_CHECK(CarPartVertex_rawNormal_GeometryOffsetCheck, offsetof(DeformVertex, rawNormal) == 0x1b);
CMR2_LAYOUT_CHECK(CarPartFloatVertex_pos_GeometryOffsetCheck, offsetof(DeformFloatVertex, pos) == 0x0);
CMR2_LAYOUT_CHECK(CarPartFloatVertex_normal_GeometryOffsetCheck, offsetof(DeformFloatVertex, normal) == 0xc);
CMR2_LAYOUT_CHECK(CarPartFloatVertex_colour_GeometryOffsetCheck, offsetof(DeformFloatVertex, colour) == 0x18);
CMR2_LAYOUT_CHECK(MeshTriangle_vertexIndex_GeometryOffsetCheck, offsetof(MeshTriangle, vertexIndex) == 0x40);
CMR2_LAYOUT_CHECK(Mesh_pVertexData_GeometryOffsetCheck, offsetof(Mesh, pVertexData) == 0xc);
CMR2_LAYOUT_CHECK(Mesh_pTriangles_GeometryOffsetCheck, offsetof(Mesh, pTriangles) == 0x24);
CMR2_LAYOUT_CHECK(Mesh_triangleCount_GeometryOffsetCheck, offsetof(Mesh, triangleCount) == 0x28);
CMR2_LAYOUT_CHECK(CarPartSet_meshes_GeometryCapacityCheck, sizeof(((CarPartSet *)0)->geometry.meshes) / sizeof(((CarPartSet *)0)->geometry.meshes[0]) == 15);
CMR2_LAYOUT_CHECK(CarPartSet_nodes_GeometryCapacityCheck, sizeof(((CarPartSet *)0)->geometry.nodes) / sizeof(((CarPartSet *)0)->geometry.nodes[0]) == 15);
CMR2_LAYOUT_CHECK(CarPartSet_vertices_GeometryCapacityCheck, sizeof(((CarPartSet *)0)->geometry.vertices) / sizeof(((CarPartSet *)0)->geometry.vertices[0]) == 15);
CMR2_LAYOUT_CHECK(CarPartSet_centres_GeometryCapacityCheck, sizeof(((CarPartSet *)0)->centres) / sizeof(((CarPartSet *)0)->centres[0]) == 15);
CMR2_LAYOUT_CHECK(CarPartSet_halfExtents_GeometryCapacityCheck, sizeof(((CarPartSet *)0)->halfExtents) / sizeof(((CarPartSet *)0)->halfExtents[0]) == 15);
CMR2_LAYOUT_CHECK(CarPartSet_vertexCount_GeometryCapacityCheck, sizeof(((CarPartSet *)0)->vertexCount) / sizeof(((CarPartSet *)0)->vertexCount[0]) == 15);
CMR2_LAYOUT_CHECK(MeshTriangle_vertexIndex_GeometryCapacityCheck, sizeof(((MeshTriangle *)0)->vertexIndex) / sizeof(((MeshTriangle *)0)->vertexIndex[0]) == 3);
CMR2_LAYOUT_CHECK(CarBodyNodePartSetupOffsetCheck, offsetof(Car, pBodyNode) == 0x720);
CMR2_LAYOUT_CHECK(CarSceneRootLightOffsetCheck, offsetof(Car, pSceneRoot) == 0x71c);

// Shared deformation prefix and the distinct preview counts/scene/box records.
CMR2_LAYOUT_CHECK(DeformMeshSources_SizeCheck, sizeof(DeformMeshSources) == 0xb4);
CMR2_LAYOUT_CHECK(DeformMeshSources_meshes_OffsetCheck, offsetof(DeformMeshSources, meshes) == 0x0);
CMR2_LAYOUT_CHECK(DeformMeshSources_nodes_OffsetCheck, offsetof(DeformMeshSources, nodes) == 0x3c);
CMR2_LAYOUT_CHECK(DeformMeshSources_vertices_OffsetCheck, offsetof(DeformMeshSources, vertices) == 0x78);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_SizeCheck, sizeof(OptionPreviewMeshRecord) == 0x2ac);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_geometry_OffsetCheck, offsetof(OptionPreviewMeshRecord, geometry) == 0x0);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_centre_OffsetCheck, offsetof(OptionPreviewMeshRecord, centre) == 0xb4);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_halfSize_OffsetCheck, offsetof(OptionPreviewMeshRecord, halfSize) == 0x168);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_maxX_OffsetCheck, offsetof(OptionPreviewMeshRecord, maxX) == 0x21c);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_minX_OffsetCheck, offsetof(OptionPreviewMeshRecord, minX) == 0x220);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_maxZ_OffsetCheck, offsetof(OptionPreviewMeshRecord, maxZ) == 0x224);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_minZ_OffsetCheck, offsetof(OptionPreviewMeshRecord, minZ) == 0x228);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_cornerHeightOffsets_OffsetCheck, offsetof(OptionPreviewMeshRecord, cornerHeightOffsets) == 0x22c);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_partDamageFractions_OffsetCheck, offsetof(OptionPreviewMeshRecord, partDamageFractions) == 0x23c);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_vertexCount_OffsetCheck, offsetof(OptionPreviewMeshRecord, vertexCount) == 0x24c);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_meshCount_OffsetCheck, offsetof(OptionPreviewMeshRecord, meshCount) == 0x26a);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_meshVisible_OffsetCheck, offsetof(OptionPreviewMeshRecord, meshVisible) == 0x26c);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_verticesAssigned_OffsetCheck, offsetof(OptionPreviewMeshRecord, verticesAssigned) == 0x2a8);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_SizeCheck, sizeof(OptionPreviewSceneRecord) == 0x54);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_modelClass_OffsetCheck, offsetof(OptionPreviewSceneRecord, modelClass) == 0x0);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_bodyNode_OffsetCheck, offsetof(OptionPreviewSceneRecord, bodyNode) == 0x4);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_rootNode_OffsetCheck, offsetof(OptionPreviewSceneRecord, rootNode) == 0x8);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_lowWheelRoot_OffsetCheck, offsetof(OptionPreviewSceneRecord, lowWheelRoot) == 0xc);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_sixWheelRoot_OffsetCheck, offsetof(OptionPreviewSceneRecord, sixWheelRoot) == 0x10);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_wheelNodes_OffsetCheck, offsetof(OptionPreviewSceneRecord, wheelNodes) == 0x14);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_normalWheelMeshes_OffsetCheck, offsetof(OptionPreviewSceneRecord, normalWheelMeshes) == 0x24);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_lowWheelMeshes_OffsetCheck, offsetof(OptionPreviewSceneRecord, lowWheelMeshes) == 0x34);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_sixWheelMeshes_OffsetCheck, offsetof(OptionPreviewSceneRecord, sixWheelMeshes) == 0x44);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_SizeCheck, sizeof(OptionPreviewDeformGeometry) == 0x138);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_pEntry_OffsetCheck, offsetof(OptionPreviewDeformGeometry, pEntry) == 0x0);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_corner_OffsetCheck, offsetof(OptionPreviewDeformGeometry, corner) == 0x4);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_vertex_OffsetCheck, offsetof(OptionPreviewDeformGeometry, vertex) == 0x64);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_anchor_OffsetCheck, offsetof(OptionPreviewDeformGeometry, anchor) == 0xf4);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_animationPhaseDegrees_OffsetCheck, offsetof(OptionPreviewDeformGeometry, animationPhaseDegrees) == 0x124);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_anchorPhaseDegrees_OffsetCheck, offsetof(OptionPreviewDeformGeometry, anchorPhaseDegrees) == 0x128);
CMR2_LAYOUT_CHECK(DeformMeshSources_meshes_CapacityCheck, sizeof(((DeformMeshSources *)0)->meshes) / sizeof(((DeformMeshSources *)0)->meshes[0]) == 15);
CMR2_LAYOUT_CHECK(DeformMeshSources_nodes_CapacityCheck, sizeof(((DeformMeshSources *)0)->nodes) / sizeof(((DeformMeshSources *)0)->nodes[0]) == 15);
CMR2_LAYOUT_CHECK(DeformMeshSources_vertices_CapacityCheck, sizeof(((DeformMeshSources *)0)->vertices) / sizeof(((DeformMeshSources *)0)->vertices[0]) == 15);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_centre_CapacityCheck, sizeof(((OptionPreviewMeshRecord *)0)->centre) / sizeof(((OptionPreviewMeshRecord *)0)->centre[0]) == 15);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_halfSize_CapacityCheck, sizeof(((OptionPreviewMeshRecord *)0)->halfSize) / sizeof(((OptionPreviewMeshRecord *)0)->halfSize[0]) == 15);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_vertexCount_CapacityCheck, sizeof(((OptionPreviewMeshRecord *)0)->vertexCount) / sizeof(((OptionPreviewMeshRecord *)0)->vertexCount[0]) == 15);
CMR2_LAYOUT_CHECK(OptionPreviewMeshRecord_meshVisible_CapacityCheck, sizeof(((OptionPreviewMeshRecord *)0)->meshVisible) / sizeof(((OptionPreviewMeshRecord *)0)->meshVisible[0]) == 15);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_wheelNodes_CapacityCheck, sizeof(((OptionPreviewSceneRecord *)0)->wheelNodes) / sizeof(((OptionPreviewSceneRecord *)0)->wheelNodes[0]) == 4);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_normalWheelMeshes_CapacityCheck, sizeof(((OptionPreviewSceneRecord *)0)->normalWheelMeshes) / sizeof(((OptionPreviewSceneRecord *)0)->normalWheelMeshes[0]) == 4);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_lowWheelMeshes_CapacityCheck, sizeof(((OptionPreviewSceneRecord *)0)->lowWheelMeshes) / sizeof(((OptionPreviewSceneRecord *)0)->lowWheelMeshes[0]) == 4);
CMR2_LAYOUT_CHECK(OptionPreviewSceneRecord_sixWheelMeshes_CapacityCheck, sizeof(((OptionPreviewSceneRecord *)0)->sixWheelMeshes) / sizeof(((OptionPreviewSceneRecord *)0)->sixWheelMeshes[0]) == 4);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_corner_CapacityCheck, sizeof(((OptionPreviewDeformGeometry *)0)->corner) / sizeof(((OptionPreviewDeformGeometry *)0)->corner[0]) == 8);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_vertex_CapacityCheck, sizeof(((OptionPreviewDeformGeometry *)0)->vertex) / sizeof(((OptionPreviewDeformGeometry *)0)->vertex[0]) == 12);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_anchor_CapacityCheck, sizeof(((OptionPreviewDeformGeometry *)0)->anchor) / sizeof(((OptionPreviewDeformGeometry *)0)->anchor[0]) == 4);
CMR2_LAYOUT_CHECK(OptionPreviewDeformGeometry_anchorPhaseDegrees_CapacityCheck, sizeof(((OptionPreviewDeformGeometry *)0)->anchorPhaseDegrees) / sizeof(((OptionPreviewDeformGeometry *)0)->anchorPhaseDegrees[0]) == 4);
CMR2_LAYOUT_CHECK(PreviewVertexCountWidthCheck, sizeof(((OptionPreviewMeshRecord *)0)->vertexCount[0]) == 2);
CMR2_LAYOUT_CHECK(PreviewMeshCountWidthCheck, sizeof(((OptionPreviewMeshRecord *)0)->meshCount) == 1);
CMR2_LAYOUT_CHECK(g_previewMeshRecords_CapacityCheck, sizeof(g_previewMeshRecords) / sizeof(g_previewMeshRecords[0]) == 16);
CMR2_LAYOUT_CHECK(g_previewSceneRecords_CapacityCheck, sizeof(g_previewSceneRecords) / sizeof(g_previewSceneRecords[0]) == 16);
CMR2_LAYOUT_CHECK(g_previewDeformGeometry_CapacityCheck, sizeof(g_previewDeformGeometry) / sizeof(g_previewDeformGeometry[0]) == 8);
CMR2_LAYOUT_CHECK(g_previewOriginalVertices_CapacityCheck, sizeof(g_previewOriginalVertices) / sizeof(g_previewOriginalVertices[0]) == 16);
CMR2_LAYOUT_CHECK(g_previewOriginalNodeTypes_CapacityCheck, sizeof(g_previewOriginalNodeTypes) / sizeof(g_previewOriginalNodeTypes[0]) == 16);

// Packed impact payloads and the persistent damage prefix, distinct from a car record.
extern PreviewSignedAngles g_previewRotationAngles[4];
extern PreviewSignedAngles g_previewRotationDeltas[4];
extern PreviewSignedAngles g_previewRotationStartAngles[4];
extern PreviewSignedAngles g_previewRotationTargets[4];
extern int g_previewRotationStartTimes[20];
extern BYTE g_previewRotationActive[4];
extern FixAngles g_previewPartRotationPresets[12];
extern PreviewModelReferenceGeometry g_previewReferenceModels[14];
extern PreviewProjectedQuad g_previewProjectedPartQuads[12];
CMR2_LAYOUT_CHECK(CarImpactPayload_RecoveredSizeCheck, sizeof(CarImpactPayload) == 0xc);
CMR2_LAYOUT_CHECK(RallyCarDamageState_RecoveredSizeCheck, sizeof(RallyCarDamageState) == 0x148);
CMR2_LAYOUT_CHECK(PreviewSignedAngles_RecoveredSizeCheck, sizeof(PreviewSignedAngles) == 0x8);
CMR2_LAYOUT_CHECK(PreviewModelReferenceGeometry_RecoveredSizeCheck, sizeof(PreviewModelReferenceGeometry) == 0x240);
CMR2_LAYOUT_CHECK(PreviewScreenPoint_RecoveredSizeCheck, sizeof(PreviewScreenPoint) == 0x8);
CMR2_LAYOUT_CHECK(PreviewProjectedQuad_RecoveredSizeCheck, sizeof(PreviewProjectedQuad) == 0x20);
CMR2_LAYOUT_CHECK(CarImpactPayload_strength_RecoveredOffsetCheck, offsetof(CarImpactPayload, strength) == 0x0);
CMR2_LAYOUT_CHECK(CarImpactPayload_mode_RecoveredOffsetCheck, offsetof(CarImpactPayload, mode) == 0x1);
CMR2_LAYOUT_CHECK(CarImpactPayload_axisRadius_RecoveredOffsetCheck, offsetof(CarImpactPayload, axisRadius) == 0x2);
CMR2_LAYOUT_CHECK(CarImpactPayload_normal_RecoveredOffsetCheck, offsetof(CarImpactPayload, normal) == 0x3);
CMR2_LAYOUT_CHECK(CarImpactPayload_axis_RecoveredOffsetCheck, offsetof(CarImpactPayload, axis) == 0x6);
CMR2_LAYOUT_CHECK(CarImpactPayload_position_RecoveredOffsetCheck, offsetof(CarImpactPayload, position) == 0x9);
CMR2_LAYOUT_CHECK(CarDamageLink_impact_RecoveredOffsetCheck, offsetof(CarDamageLink, impact) == 0x0);
CMR2_LAYOUT_CHECK(CarDamageLink_next_RecoveredOffsetCheck, offsetof(CarDamageLink, next) == 0xc);
CMR2_LAYOUT_CHECK(RallyCarDamageState_impacts_RecoveredOffsetCheck, offsetof(RallyCarDamageState, impacts) == 0x0);
CMR2_LAYOUT_CHECK(RallyCarDamageState_damage_RecoveredOffsetCheck, offsetof(RallyCarDamageState, damage) == 0x108);
CMR2_LAYOUT_CHECK(PreviewSignedAngles_x_RecoveredOffsetCheck, offsetof(PreviewSignedAngles, x) == 0x0);
CMR2_LAYOUT_CHECK(PreviewSignedAngles_y_RecoveredOffsetCheck, offsetof(PreviewSignedAngles, y) == 0x2);
CMR2_LAYOUT_CHECK(PreviewSignedAngles_z_RecoveredOffsetCheck, offsetof(PreviewSignedAngles, z) == 0x4);
CMR2_LAYOUT_CHECK(PreviewSignedAngles_field_0x6_RecoveredOffsetCheck, offsetof(PreviewSignedAngles, field_0x6) == 0x6);
CMR2_LAYOUT_CHECK(PreviewModelReferenceGeometry_partVertices_RecoveredOffsetCheck, offsetof(PreviewModelReferenceGeometry, partVertices) == 0x0);
CMR2_LAYOUT_CHECK(PreviewScreenPoint_x_RecoveredOffsetCheck, offsetof(PreviewScreenPoint, x) == 0x0);
CMR2_LAYOUT_CHECK(PreviewScreenPoint_y_RecoveredOffsetCheck, offsetof(PreviewScreenPoint, y) == 0x4);
CMR2_LAYOUT_CHECK(PreviewProjectedQuad_points_RecoveredOffsetCheck, offsetof(PreviewProjectedQuad, points) == 0x0);
CMR2_LAYOUT_CHECK(CarImpactPayload_normal_RecoveredCapacityCheck, sizeof(((CarImpactPayload *)0)->normal) / sizeof(((CarImpactPayload *)0)->normal[0]) == 3);
CMR2_LAYOUT_CHECK(CarImpactPayload_axis_RecoveredCapacityCheck, sizeof(((CarImpactPayload *)0)->axis) / sizeof(((CarImpactPayload *)0)->axis[0]) == 3);
CMR2_LAYOUT_CHECK(CarImpactPayload_position_RecoveredCapacityCheck, sizeof(((CarImpactPayload *)0)->position) / sizeof(((CarImpactPayload *)0)->position[0]) == 3);
CMR2_LAYOUT_CHECK(CarDamageLinkPool_links_RecoveredCapacityCheck, sizeof(((CarDamageLinkPool *)0)->links) / sizeof(((CarDamageLinkPool *)0)->links[0]) == 20);
CMR2_LAYOUT_CHECK(PreviewModelReferenceGeometry_partVertices_RecoveredCapacityCheck, sizeof(((PreviewModelReferenceGeometry *)0)->partVertices) / sizeof(((PreviewModelReferenceGeometry *)0)->partVertices[0]) == 12);
CMR2_LAYOUT_CHECK(PreviewProjectedQuad_points_RecoveredCapacityCheck, sizeof(((PreviewProjectedQuad *)0)->points) / sizeof(((PreviewProjectedQuad *)0)->points[0]) == 4);
CMR2_LAYOUT_CHECK(PreviewReferencePartVertexCapacityCheck, sizeof(((PreviewModelReferenceGeometry *)0)->partVertices[0]) / sizeof(FixVector) == 4);
CMR2_LAYOUT_CHECK(g_previewRotationAngles_RecoveredCapacityCheck, sizeof(g_previewRotationAngles) / sizeof(g_previewRotationAngles[0]) == 4);
CMR2_LAYOUT_CHECK(g_previewRotationDeltas_RecoveredCapacityCheck, sizeof(g_previewRotationDeltas) / sizeof(g_previewRotationDeltas[0]) == 4);
CMR2_LAYOUT_CHECK(g_previewRotationStartAngles_RecoveredCapacityCheck, sizeof(g_previewRotationStartAngles) / sizeof(g_previewRotationStartAngles[0]) == 4);
CMR2_LAYOUT_CHECK(g_previewRotationTargets_RecoveredCapacityCheck, sizeof(g_previewRotationTargets) / sizeof(g_previewRotationTargets[0]) == 4);
CMR2_LAYOUT_CHECK(g_previewRotationStartTimes_RecoveredCapacityCheck, sizeof(g_previewRotationStartTimes) / sizeof(g_previewRotationStartTimes[0]) == 20);
CMR2_LAYOUT_CHECK(g_previewRotationActive_RecoveredCapacityCheck, sizeof(g_previewRotationActive) / sizeof(g_previewRotationActive[0]) == 4);
CMR2_LAYOUT_CHECK(g_previewPartRotationPresets_RecoveredCapacityCheck, sizeof(g_previewPartRotationPresets) / sizeof(g_previewPartRotationPresets[0]) == 12);
CMR2_LAYOUT_CHECK(g_previewReferenceModels_RecoveredCapacityCheck, sizeof(g_previewReferenceModels) / sizeof(g_previewReferenceModels[0]) == 14);
CMR2_LAYOUT_CHECK(g_previewProjectedPartQuads_RecoveredCapacityCheck, sizeof(g_previewProjectedPartQuads) / sizeof(g_previewProjectedPartQuads[0]) == 12);

// CIN views: trailing [1] arrays express variable tails, not fixed capacities.
CMR2_LAYOUT_CHECK(CarLightPoint_CINViewSizeCheck, sizeof(CarLightPoint) == 0x28);
CMR2_LAYOUT_CHECK(CarLightProfile_CINViewSizeCheck, sizeof(CarLightProfile) == 0x2c);
CMR2_LAYOUT_CHECK(CarSkidProfilePoint_CINViewSizeCheck, sizeof(CarSkidProfilePoint) == 0x8);
CMR2_LAYOUT_CHECK(CarContactProfile_CINViewSizeCheck, sizeof(CarContactProfile) == 0x14);
CMR2_LAYOUT_CHECK(CarGlassProfile_CINViewSizeCheck, sizeof(CarGlassProfile) == 0x54);
CMR2_LAYOUT_CHECK(CarFlexibleLineDescriptor_CINViewSizeCheck, sizeof(CarFlexibleLineDescriptor) == 0x20);
CMR2_LAYOUT_CHECK(CarFlexibleLineProfile_CINViewSizeCheck, sizeof(CarFlexibleLineProfile) == 0x30);
CMR2_LAYOUT_CHECK(CarInteriorProfile_CINViewSizeCheck, sizeof(CarInteriorProfile) == 0x30);
CMR2_LAYOUT_CHECK(CarInteriorProfilePointers_CINViewSizeCheck, sizeof(CarInteriorProfilePointers) == 0x1c);
CMR2_LAYOUT_CHECK(CarInteriorNodes_CINViewSizeCheck, sizeof(CarInteriorNodes) == 0x1c);
CMR2_LAYOUT_CHECK(CarWiperState_CINViewSizeCheck, sizeof(CarWiperState) == 0xc);
CMR2_LAYOUT_CHECK(CarInteriorRuntimeTables_CINViewSizeCheck, sizeof(CarInteriorRuntimeTables) == 0x90);
CMR2_LAYOUT_CHECK(GenericFile_CINViewSizeCheck, sizeof(GenericFile) == 0xc);
CMR2_LAYOUT_CHECK(CarInfoDirectory_sectionOffsets_CINOffsetCheck, offsetof(CarInfoDirectory, sectionOffsets) == 0x0);
CMR2_LAYOUT_CHECK(CarLightPoint_pos_CINOffsetCheck, offsetof(CarLightPoint, pos) == 0x0);
CMR2_LAYOUT_CHECK(CarLightPoint_dir_CINOffsetCheck, offsetof(CarLightPoint, dir) == 0xc);
CMR2_LAYOUT_CHECK(CarLightPoint_size_CINOffsetCheck, offsetof(CarLightPoint, size) == 0x18);
CMR2_LAYOUT_CHECK(CarLightPoint_intensity_CINOffsetCheck, offsetof(CarLightPoint, intensity) == 0x1c);
CMR2_LAYOUT_CHECK(CarLightPoint_type_CINOffsetCheck, offsetof(CarLightPoint, type) == 0x20);
CMR2_LAYOUT_CHECK(CarLightPoint_slot_CINOffsetCheck, offsetof(CarLightPoint, slot) == 0x21);
CMR2_LAYOUT_CHECK(CarLightPoint_part_CINOffsetCheck, offsetof(CarLightPoint, part) == 0x22);
CMR2_LAYOUT_CHECK(CarLightPoint_pad_0x23_CINOffsetCheck, offsetof(CarLightPoint, pad_0x23) == 0x23);
CMR2_LAYOUT_CHECK(CarLightPoint_object_CINOffsetCheck, offsetof(CarLightPoint, object) == 0x24);
CMR2_LAYOUT_CHECK(CarLightPoint_vertex_CINOffsetCheck, offsetof(CarLightPoint, vertex) == 0x26);
CMR2_LAYOUT_CHECK(CarLightProfile_count_CINOffsetCheck, offsetof(CarLightProfile, count) == 0x0);
CMR2_LAYOUT_CHECK(CarLightProfile_points_CINOffsetCheck, offsetof(CarLightProfile, points) == 0x4);
CMR2_LAYOUT_CHECK(CarSkidProfilePoint_longitudinalDistance_CINOffsetCheck, offsetof(CarSkidProfilePoint, longitudinalDistance) == 0x0);
CMR2_LAYOUT_CHECK(CarSkidProfilePoint_lateralWidth_CINOffsetCheck, offsetof(CarSkidProfilePoint, lateralWidth) == 0x4);
CMR2_LAYOUT_CHECK(CarContactProfile_pointCount_CINOffsetCheck, offsetof(CarContactProfile, pointCount) == 0x0);
CMR2_LAYOUT_CHECK(CarContactProfile_visibleRangeStart_CINOffsetCheck, offsetof(CarContactProfile, visibleRangeStart) == 0x1);
CMR2_LAYOUT_CHECK(CarContactProfile_visibleRangeCount_CINOffsetCheck, offsetof(CarContactProfile, visibleRangeCount) == 0x2);
CMR2_LAYOUT_CHECK(CarContactProfile_field_0x3_CINOffsetCheck, offsetof(CarContactProfile, field_0x3) == 0x3);
CMR2_LAYOUT_CHECK(CarContactProfile_longitudinalOffset_CINOffsetCheck, offsetof(CarContactProfile, longitudinalOffset) == 0x4);
CMR2_LAYOUT_CHECK(CarContactProfile_wheelPatchLength_CINOffsetCheck, offsetof(CarContactProfile, wheelPatchLength) == 0x8);
CMR2_LAYOUT_CHECK(CarContactProfile_points_CINOffsetCheck, offsetof(CarContactProfile, points) == 0xc);
CMR2_LAYOUT_CHECK(CarGlassProfile_tint_CINOffsetCheck, offsetof(CarGlassProfile, tint) == 0x0);
CMR2_LAYOUT_CHECK(CarGlassProfile_windowVertices_CINOffsetCheck, offsetof(CarGlassProfile, windowVertices) == 0xc);
CMR2_LAYOUT_CHECK(CarFlexibleLineProfile_constraintAxis_CINOffsetCheck, offsetof(CarFlexibleLineProfile, constraintAxis) == 0x0);
CMR2_LAYOUT_CHECK(CarFlexibleLineProfile_count_CINOffsetCheck, offsetof(CarFlexibleLineProfile, count) == 0xc);
CMR2_LAYOUT_CHECK(CarFlexibleLineProfile_descriptors_CINOffsetCheck, offsetof(CarFlexibleLineProfile, descriptors) == 0x10);
CMR2_LAYOUT_CHECK(CarInteriorProfile_firstWiperRotation_CINOffsetCheck, offsetof(CarInteriorProfile, firstWiperRotation) == 0x0);
CMR2_LAYOUT_CHECK(CarInteriorProfile_firstWiperMaxAngle_CINOffsetCheck, offsetof(CarInteriorProfile, firstWiperMaxAngle) == 0x8);
CMR2_LAYOUT_CHECK(CarInteriorProfile_field_0xa_CINOffsetCheck, offsetof(CarInteriorProfile, field_0xa) == 0xa);
CMR2_LAYOUT_CHECK(CarInteriorProfile_driverPoseOffset_CINOffsetCheck, offsetof(CarInteriorProfile, driverPoseOffset) == 0xc);
CMR2_LAYOUT_CHECK(CarInteriorProfile_driverRestYaw_CINOffsetCheck, offsetof(CarInteriorProfile, driverRestYaw) == 0x18);
CMR2_LAYOUT_CHECK(CarInteriorProfile_field_0x1a_CINOffsetCheck, offsetof(CarInteriorProfile, field_0x1a) == 0x1a);
CMR2_LAYOUT_CHECK(CarInteriorProfile_steeringBaseRotation_CINOffsetCheck, offsetof(CarInteriorProfile, steeringBaseRotation) == 0x1c);
CMR2_LAYOUT_CHECK(CarInteriorProfile_secondWiperRotation_CINOffsetCheck, offsetof(CarInteriorProfile, secondWiperRotation) == 0x24);
CMR2_LAYOUT_CHECK(CarInteriorProfile_secondWiperMaxAngle_CINOffsetCheck, offsetof(CarInteriorProfile, secondWiperMaxAngle) == 0x2c);
CMR2_LAYOUT_CHECK(CarInteriorProfilePointers_firstWiperRotation_CINOffsetCheck, offsetof(CarInteriorProfilePointers, firstWiperRotation) == 0x0);
CMR2_LAYOUT_CHECK(CarInteriorProfilePointers_firstWiperMaxAngle_CINOffsetCheck, offsetof(CarInteriorProfilePointers, firstWiperMaxAngle) == 0x4);
CMR2_LAYOUT_CHECK(CarInteriorProfilePointers_driverPoseOffset_CINOffsetCheck, offsetof(CarInteriorProfilePointers, driverPoseOffset) == 0x8);
CMR2_LAYOUT_CHECK(CarInteriorProfilePointers_driverRestYaw_CINOffsetCheck, offsetof(CarInteriorProfilePointers, driverRestYaw) == 0xc);
CMR2_LAYOUT_CHECK(CarInteriorProfilePointers_steeringBaseRotation_CINOffsetCheck, offsetof(CarInteriorProfilePointers, steeringBaseRotation) == 0x10);
CMR2_LAYOUT_CHECK(CarInteriorProfilePointers_secondWiperRotation_CINOffsetCheck, offsetof(CarInteriorProfilePointers, secondWiperRotation) == 0x14);
CMR2_LAYOUT_CHECK(CarInteriorProfilePointers_secondWiperMaxAngle_CINOffsetCheck, offsetof(CarInteriorProfilePointers, secondWiperMaxAngle) == 0x18);
CMR2_LAYOUT_CHECK(CarInteriorNodes_steeringRestNode_CINOffsetCheck, offsetof(CarInteriorNodes, steeringRestNode) == 0x0);
CMR2_LAYOUT_CHECK(CarInteriorNodes_steeringBlendNode_CINOffsetCheck, offsetof(CarInteriorNodes, steeringBlendNode) == 0x4);
CMR2_LAYOUT_CHECK(CarInteriorNodes_steeringReferenceNode_CINOffsetCheck, offsetof(CarInteriorNodes, steeringReferenceNode) == 0x8);
CMR2_LAYOUT_CHECK(CarInteriorNodes_driverPoseNode_CINOffsetCheck, offsetof(CarInteriorNodes, driverPoseNode) == 0xc);
CMR2_LAYOUT_CHECK(CarInteriorNodes_steeringWheelNode_CINOffsetCheck, offsetof(CarInteriorNodes, steeringWheelNode) == 0x10);
CMR2_LAYOUT_CHECK(CarInteriorNodes_wiperNodes_CINOffsetCheck, offsetof(CarInteriorNodes, wiperNodes) == 0x14);
CMR2_LAYOUT_CHECK(CarWiperState_mode_CINOffsetCheck, offsetof(CarWiperState, mode) == 0x0);
CMR2_LAYOUT_CHECK(CarWiperState_sweepingForward_CINOffsetCheck, offsetof(CarWiperState, sweepingForward) == 0x4);
CMR2_LAYOUT_CHECK(CarWiperState_angle_CINOffsetCheck, offsetof(CarWiperState, angle) == 0x8);
CMR2_LAYOUT_CHECK(CarWiperState_step_CINOffsetCheck, offsetof(CarWiperState, step) == 0xa);
CMR2_LAYOUT_CHECK(CarInteriorRuntimeTables_modelClasses_CINOffsetCheck, offsetof(CarInteriorRuntimeTables, modelClasses) == 0x0);
CMR2_LAYOUT_CHECK(CarInteriorRuntimeTables_wipers_CINOffsetCheck, offsetof(CarInteriorRuntimeTables, wipers) == 0x8);
CMR2_LAYOUT_CHECK(CarInteriorRuntimeTables_profiles_CINOffsetCheck, offsetof(CarInteriorRuntimeTables, profiles) == 0x20);
CMR2_LAYOUT_CHECK(CarInteriorRuntimeTables_nodes_CINOffsetCheck, offsetof(CarInteriorRuntimeTables, nodes) == 0x58);
CMR2_LAYOUT_CHECK(GenericFile_buffer_CINOffsetCheck, offsetof(GenericFile, buffer) == 0x0);
CMR2_LAYOUT_CHECK(GenericFile_fileSize_CINOffsetCheck, offsetof(GenericFile, fileSize) == 0x4);
CMR2_LAYOUT_CHECK(GenericFile_didFileLoad_CINOffsetCheck, offsetof(GenericFile, didFileLoad) == 0x8);
CMR2_LAYOUT_CHECK(StageArchiveTables_archives_CINOffsetCheck, offsetof(StageArchiveTables, archives) == 0x0);
CMR2_LAYOUT_CHECK(StageArchiveTables_driverCount_CINOffsetCheck, offsetof(StageArchiveTables, driverCount) == 0x180);
CMR2_LAYOUT_CHECK(StageArchiveTables_secondaryCount_CINOffsetCheck, offsetof(StageArchiveTables, secondaryCount) == 0x184);
CMR2_LAYOUT_CHECK(CarGlassProfile_tint_CINCapacityCheck, sizeof(((CarGlassProfile *)0)->tint) / sizeof(((CarGlassProfile *)0)->tint[0]) == 3);
CMR2_LAYOUT_CHECK(CarGlassProfile_windowVertices_CINCapacityCheck, sizeof(((CarGlassProfile *)0)->windowVertices) / sizeof(((CarGlassProfile *)0)->windowVertices[0]) == 6);
CMR2_LAYOUT_CHECK(CarInteriorNodes_wiperNodes_CINCapacityCheck, sizeof(((CarInteriorNodes *)0)->wiperNodes) / sizeof(((CarInteriorNodes *)0)->wiperNodes[0]) == 2);
CMR2_LAYOUT_CHECK(CarInteriorRuntimeTables_modelClasses_CINCapacityCheck, sizeof(((CarInteriorRuntimeTables *)0)->modelClasses) / sizeof(((CarInteriorRuntimeTables *)0)->modelClasses[0]) == 8);
CMR2_LAYOUT_CHECK(CarInteriorRuntimeTables_wipers_CINCapacityCheck, sizeof(((CarInteriorRuntimeTables *)0)->wipers) / sizeof(((CarInteriorRuntimeTables *)0)->wipers[0]) == 2);
CMR2_LAYOUT_CHECK(CarInteriorRuntimeTables_profiles_CINCapacityCheck, sizeof(((CarInteriorRuntimeTables *)0)->profiles) / sizeof(((CarInteriorRuntimeTables *)0)->profiles[0]) == 2);
CMR2_LAYOUT_CHECK(CarInteriorRuntimeTables_nodes_CINCapacityCheck, sizeof(((CarInteriorRuntimeTables *)0)->nodes) / sizeof(((CarInteriorRuntimeTables *)0)->nodes[0]) == 2);
CMR2_LAYOUT_CHECK(StageArchiveTables_archives_CINCapacityCheck, sizeof(((StageArchiveTables *)0)->archives) / sizeof(((StageArchiveTables *)0)->archives[0]) == 32);
CMR2_LAYOUT_CHECK(CarGlassTintWidthCheck, sizeof(((CarGlassProfile *)0)->tint[0]) == 4);
CMR2_LAYOUT_CHECK(CarInfoOffsetWidthCheck, sizeof(((CarInfoDirectory *)0)->sectionOffsets[0]) == 2);
extern CarGlassProfile *g_carGlassProfiles[8];
CMR2_LAYOUT_CHECK(g_carGlassProfiles_CINCapacityCheck, sizeof(g_carGlassProfiles) / sizeof(g_carGlassProfiles[0]) == 8);
extern FixVector *g_carFlexibleLineConstraintAxes[8];
CMR2_LAYOUT_CHECK(g_carFlexibleLineConstraintAxes_CINCapacityCheck, sizeof(g_carFlexibleLineConstraintAxes) / sizeof(g_carFlexibleLineConstraintAxes[0]) == 8);
extern CarLightProfile *g_carLightProfiles[8];
CMR2_LAYOUT_CHECK(g_carLightProfiles_CINCapacityCheck, sizeof(g_carLightProfiles) / sizeof(g_carLightProfiles[0]) == 8);
extern CarSkidProfilePoint *g_physSkidProfilePoints[8];
CMR2_LAYOUT_CHECK(g_physSkidProfilePoints_CINCapacityCheck, sizeof(g_physSkidProfilePoints) / sizeof(g_physSkidProfilePoints[0]) == 8);
extern FixVector *g_carCameraOffsets[8];
CMR2_LAYOUT_CHECK(g_carCameraOffsets_CINCapacityCheck, sizeof(g_carCameraOffsets) / sizeof(g_carCameraOffsets[0]) == 8);
extern BYTE *g_physSkidCount[8];
CMR2_LAYOUT_CHECK(g_physSkidCount_CINCapacityCheck, sizeof(g_physSkidCount) / sizeof(g_physSkidCount[0]) == 8);
extern BYTE *g_physSkidRange[8];
CMR2_LAYOUT_CHECK(g_physSkidRange_CINCapacityCheck, sizeof(g_physSkidRange) / sizeof(g_physSkidRange[0]) == 8);
extern int *g_physSkidOffset[8];
CMR2_LAYOUT_CHECK(g_physSkidOffset_CINCapacityCheck, sizeof(g_physSkidOffset) / sizeof(g_physSkidOffset[0]) == 8);
extern int *g_physWheelLength[8];
CMR2_LAYOUT_CHECK(g_physWheelLength_CINCapacityCheck, sizeof(g_physWheelLength) / sizeof(g_physWheelLength[0]) == 8);
CMR2_LAYOUT_CHECK(g_carInteriorModelClasses_CINCapacityCheck, sizeof(g_carInteriorModelClasses) / sizeof(g_carInteriorModelClasses[0]) == 8);
CMR2_LAYOUT_CHECK(g_carWiperStates_CINCapacityCheck, sizeof(g_carWiperStates) / sizeof(g_carWiperStates[0]) == 2);
CMR2_LAYOUT_CHECK(g_carInteriorProfilePointers_CINCapacityCheck, sizeof(g_carInteriorProfilePointers) / sizeof(g_carInteriorProfilePointers[0]) == 2);
CMR2_LAYOUT_CHECK(g_carInteriorNodeRows_CINCapacityCheck, sizeof(g_carInteriorNodeRows) / sizeof(g_carInteriorNodeRows[0]) == 2);

extern BYTE g_viewObjectCarIndices[16];
extern int g_viewObjectLevels[64];
CMR2_LAYOUT_CHECK(ViewObjectCarIndexCapacityCheck, sizeof(g_viewObjectCarIndices) == 16);
CMR2_LAYOUT_CHECK(ViewObjectLevelCapacityCheck, sizeof(g_viewObjectLevels) / sizeof(g_viewObjectLevels[0]) == 64);

// Stage interior resources and shared light records (tandas 19–21).
CMR2_LAYOUT_CHECK(CarDriverPoseState_RecoveredSizeCheck, (sizeof(CarDriverPoseState) == 0x24));
CMR2_LAYOUT_CHECK(CarInteriorDashTextures_RecoveredSizeCheck, (sizeof(CarInteriorDashTextures) == 0x8));
CMR2_LAYOUT_CHECK(CarLightTextureState_RecoveredSizeCheck, (sizeof(CarLightTextureState) == 0x48));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_RecoveredSizeCheck, (sizeof(CarHeadlightGlowRecord) == 0x5c));
CMR2_LAYOUT_CHECK(CarDriverPoseState_phaseAngle_RecoveredOffsetCheck, (offsetof(CarDriverPoseState, phaseAngle) == 0x0));
CMR2_LAYOUT_CHECK(CarDriverPoseState_rotation_RecoveredOffsetCheck, (offsetof(CarDriverPoseState, rotation) == 0x2));
CMR2_LAYOUT_CHECK(CarDriverPoseState_field_0xa_RecoveredOffsetCheck, (offsetof(CarDriverPoseState, field_0xa) == 0xa));
CMR2_LAYOUT_CHECK(CarDriverPoseState_offset_RecoveredOffsetCheck, (offsetof(CarDriverPoseState, offset) == 0xc));
CMR2_LAYOUT_CHECK(CarDriverPoseState_mountOffset_RecoveredOffsetCheck, (offsetof(CarDriverPoseState, mountOffset) == 0x18));
CMR2_LAYOUT_CHECK(CarInteriorDashTextures_revCounter_RecoveredOffsetCheck, (offsetof(CarInteriorDashTextures, revCounter) == 0x0));
CMR2_LAYOUT_CHECK(CarInteriorDashTextures_digit_RecoveredOffsetCheck, (offsetof(CarInteriorDashTextures, digit) == 0x4));
CMR2_LAYOUT_CHECK(CarLightTextureState_textures_RecoveredOffsetCheck, (offsetof(CarLightTextureState, textures) == 0x0));
CMR2_LAYOUT_CHECK(CarLightTextureState_levels_RecoveredOffsetCheck, (offsetof(CarLightTextureState, levels) == 0x8));
CMR2_LAYOUT_CHECK(CarLightTextureState_appliedLevels_RecoveredOffsetCheck, (offsetof(CarLightTextureState, appliedLevels) == 0x1c));
CMR2_LAYOUT_CHECK(CarLightTextureState_fadedLevels_RecoveredOffsetCheck, (offsetof(CarLightTextureState, fadedLevels) == 0x30));
CMR2_LAYOUT_CHECK(CarLightTextureState_channelMasks_RecoveredOffsetCheck, (offsetof(CarLightTextureState, channelMasks) == 0x44));
CMR2_LAYOUT_CHECK(CarLightTextureState_combineFirstTwoChannels_RecoveredOffsetCheck, (offsetof(CarLightTextureState, combineFirstTwoChannels) == 0x46));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_velocity_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, velocity) == 0x0));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_position_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, position) == 0xc));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_normal_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, normal) == 0x18));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_fade_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, fade) == 0x24));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_prevPosition_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, prevPosition) == 0x28));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_prevNormal_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, prevNormal) == 0x34));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_prevFade_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, prevFade) == 0x40));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_height_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, height) == 0x44));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_life_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, life) == 0x48));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_triangle_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, triangle) == 0x4c));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_field_0x4e_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, field_0x4e) == 0x4e));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_pGlow_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, pGlow) == 0x50));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_active_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, active) == 0x54));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_car_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, car) == 0x58));
CMR2_LAYOUT_CHECK(CarHeadlightGlowRecord_field_0x59_RecoveredOffsetCheck, (offsetof(CarHeadlightGlowRecord, field_0x59) == 0x59));
CMR2_LAYOUT_CHECK(g_carAppliedRevTextureLevels_RecoveredCapacityCheck, (sizeof(g_carAppliedRevTextureLevels) / sizeof(g_carAppliedRevTextureLevels[0]) == 2));
CMR2_LAYOUT_CHECK(g_carRequestedRevTextureLevels_RecoveredCapacityCheck, (sizeof(g_carRequestedRevTextureLevels) / sizeof(g_carRequestedRevTextureLevels[0]) == 2));
CMR2_LAYOUT_CHECK(g_carRequestedDigitTextureAlphas_RecoveredCapacityCheck, (sizeof(g_carRequestedDigitTextureAlphas) / sizeof(g_carRequestedDigitTextureAlphas[0]) == 2));
CMR2_LAYOUT_CHECK(g_carAppliedDigitTextureAlphas_RecoveredCapacityCheck, (sizeof(g_carAppliedDigitTextureAlphas) / sizeof(g_carAppliedDigitTextureAlphas[0]) == 2));
CMR2_LAYOUT_CHECK(g_carDetailBodyNodes_RecoveredCapacityCheck, (sizeof(g_carDetailBodyNodes) / sizeof(g_carDetailBodyNodes[0]) == 8));
CMR2_LAYOUT_CHECK(g_carDefaultBodyNodes_RecoveredCapacityCheck, (sizeof(g_carDefaultBodyNodes) / sizeof(g_carDefaultBodyNodes[0]) == 8));
CMR2_LAYOUT_CHECK(g_carDriverPoseNeedsReset_RecoveredCapacityCheck, (sizeof(g_carDriverPoseNeedsReset) / sizeof(g_carDriverPoseNeedsReset[0]) == 2));
CMR2_LAYOUT_CHECK(g_carInteriorArchives_RecoveredCapacityCheck, (sizeof(g_carInteriorArchives) / sizeof(g_carInteriorArchives[0]) == 16));
CMR2_LAYOUT_CHECK(g_carInteriorRoots_RecoveredCapacityCheck, (sizeof(g_carInteriorRoots) / sizeof(g_carInteriorRoots[0]) == 8));
CMR2_LAYOUT_CHECK(g_carInteriorDashTextures_RecoveredCapacityCheck, (sizeof(g_carInteriorDashTextures) / sizeof(g_carInteriorDashTextures[0]) == 2));
CMR2_LAYOUT_CHECK(g_carDriverRestPositions_RecoveredCapacityCheck, (sizeof(g_carDriverRestPositions) / sizeof(g_carDriverRestPositions[0]) == 2));
CMR2_LAYOUT_CHECK(g_carDriverPoseStates_RecoveredCapacityCheck, (sizeof(g_carDriverPoseStates) / sizeof(g_carDriverPoseStates[0]) == 2));
CMR2_LAYOUT_CHECK(g_carInteriorModelBuffers_RecoveredCapacityCheck, (sizeof(g_carInteriorModelBuffers) / sizeof(g_carInteriorModelBuffers[0]) == 2));
CMR2_LAYOUT_CHECK(g_carInteriorLoaded_RecoveredCapacityCheck, (sizeof(g_carInteriorLoaded) / sizeof(g_carInteriorLoaded[0]) == 2));
CMR2_LAYOUT_CHECK(g_carLightTextureStates_RecoveredCapacityCheck, (sizeof(g_carLightTextureStates) / sizeof(g_carLightTextureStates[0]) == 8));
CMR2_LAYOUT_CHECK(g_carHeadlightGlowRecords_RecoveredCapacityCheck, (sizeof(g_carHeadlightGlowRecords) / sizeof(g_carHeadlightGlowRecords[0]) == 100));
CMR2_LAYOUT_CHECK(g_carHeadlightGlowCooldowns_RecoveredCapacityCheck, (sizeof(g_carHeadlightGlowCooldowns) / sizeof(g_carHeadlightGlowCooldowns[0]) == 8));
CMR2_LAYOUT_CHECK(g_carAppliedRevTextureLevels_RecoveredRowCapacityCheck, (sizeof(g_carAppliedRevTextureLevels[0]) / sizeof(g_carAppliedRevTextureLevels[0][0]) == 12));
CMR2_LAYOUT_CHECK(g_carRequestedRevTextureLevels_RecoveredRowCapacityCheck, (sizeof(g_carRequestedRevTextureLevels[0]) / sizeof(g_carRequestedRevTextureLevels[0][0]) == 12));
CMR2_LAYOUT_CHECK(g_carRequestedDigitTextureAlphas_RecoveredRowCapacityCheck, (sizeof(g_carRequestedDigitTextureAlphas[0]) / sizeof(g_carRequestedDigitTextureAlphas[0][0]) == 7));
CMR2_LAYOUT_CHECK(g_carAppliedDigitTextureAlphas_RecoveredRowCapacityCheck, (sizeof(g_carAppliedDigitTextureAlphas[0]) / sizeof(g_carAppliedDigitTextureAlphas[0][0]) == 7));
CMR2_LAYOUT_CHECK(CarLightTextureState_TwoTextures_RecoveredCapacityCheck, (sizeof(((CarLightTextureState *)0)->textures) / sizeof(Texture *) == 2));
CMR2_LAYOUT_CHECK(CarLightTextureState_TwoLevelSets_RecoveredCapacityCheck, (sizeof(((CarLightTextureState *)0)->levels) / sizeof(((CarLightTextureState *)0)->levels[0]) == 2));
CMR2_LAYOUT_CHECK(CarLightTextureState_FiveLevels_RecoveredCapacityCheck, (sizeof(((CarLightTextureState *)0)->levels[0]) / sizeof(short) == 5));
CMR2_LAYOUT_CHECK(CarLightTextureState_TwoMasks_RecoveredCapacityCheck, (sizeof(((CarLightTextureState *)0)->channelMasks) == 2));

CMR2_LAYOUT_CHECK(g_carSteeringBlendLastGears_RecoveredCapacityCheck, (sizeof(g_carSteeringBlendLastGears) / sizeof(g_carSteeringBlendLastGears[0]) == 2));
CMR2_LAYOUT_CHECK(g_carSteeringBlendModes_RecoveredCapacityCheck, (sizeof(g_carSteeringBlendModes) / sizeof(g_carSteeringBlendModes[0]) == 2));
CMR2_LAYOUT_CHECK(g_carSteeringBlendFrames_RecoveredCapacityCheck, (sizeof(g_carSteeringBlendFrames) / sizeof(g_carSteeringBlendFrames[0]) == 2));

// Shared glow renderer and exhaust views, verified against their writers/readers.
CMR2_LAYOUT_CHECK(GlowLightSizeCheck, sizeof(GlowLight) == 0x5c);
CMR2_LAYOUT_CHECK(GlowLight_type_OffsetCheck, offsetof(GlowLight, type) == 0x0);
CMR2_LAYOUT_CHECK(GlowLight_pos_OffsetCheck, offsetof(GlowLight, pos) == 0x4);
CMR2_LAYOUT_CHECK(GlowLight_dir_OffsetCheck, offsetof(GlowLight, dir) == 0x10);
CMR2_LAYOUT_CHECK(GlowLight_planePoint_OffsetCheck, offsetof(GlowLight, planePoint) == 0x1c);
CMR2_LAYOUT_CHECK(GlowLight_planeNormal_OffsetCheck, offsetof(GlowLight, planeNormal) == 0x28);
CMR2_LAYOUT_CHECK(GlowLight_sizeX_OffsetCheck, offsetof(GlowLight, sizeX) == 0x34);
CMR2_LAYOUT_CHECK(GlowLight_sizeY_OffsetCheck, offsetof(GlowLight, sizeY) == 0x38);
CMR2_LAYOUT_CHECK(GlowLight_intensity_OffsetCheck, offsetof(GlowLight, intensity) == 0x3c);
CMR2_LAYOUT_CHECK(GlowLight_projectedSizeScale_OffsetCheck, offsetof(GlowLight, projectedSizeScale) == 0x40);
CMR2_LAYOUT_CHECK(GlowLight_layerIntensity_OffsetCheck, offsetof(GlowLight, layerIntensity) == 0x44);
CMR2_LAYOUT_CHECK(GlowLight_pTexture_OffsetCheck, offsetof(GlowLight, pTexture) == 0x48);
CMR2_LAYOUT_CHECK(GlowLight_pLayerTexture_OffsetCheck, offsetof(GlowLight, pLayerTexture) == 0x4c);
CMR2_LAYOUT_CHECK(GlowLight_enabled_OffsetCheck, offsetof(GlowLight, enabled) == 0x50);
CMR2_LAYOUT_CHECK(GlowLight_projectedBrightness_OffsetCheck, offsetof(GlowLight, projectedBrightness) == 0x51);
CMR2_LAYOUT_CHECK(GlowLight_field_0x52_OffsetCheck, offsetof(GlowLight, field_0x52) == 0x52);
CMR2_LAYOUT_CHECK(GlowLight_pNode_OffsetCheck, offsetof(GlowLight, pNode) == 0x54);
CMR2_LAYOUT_CHECK(GlowLight_field_0x58_OffsetCheck, offsetof(GlowLight, field_0x58) == 0x58);
CMR2_LAYOUT_CHECK(g_carExhaustPoints_CapacityCheck, sizeof(g_carExhaustPoints) == 64);
CMR2_LAYOUT_CHECK(g_carExhaustGlows_CapacityCheck, sizeof(g_carExhaustGlows) == 64);
CMR2_LAYOUT_CHECK(g_carExhaustWorldPositions_CapacityCheck, sizeof(g_carExhaustWorldPositions) == 96);
CMR2_LAYOUT_CHECK(g_carExhaustBurstFrames_CapacityCheck, sizeof(g_carExhaustBurstFrames) == 8);

// Car contact accesses: original Win32 offsets, runtime-only car storage.
CMR2_LAYOUT_CHECK(CarContact_halfExtents_OffsetCheck, offsetof(Car, halfExtents) == 0x204);
CMR2_LAYOUT_CHECK(CarContact_position_OffsetCheck, offsetof(Car, position) == 0x2d0);
CMR2_LAYOUT_CHECK(CarContact_positionPrev_OffsetCheck, offsetof(Car, positionPrev) == 0x2e8);
CMR2_LAYOUT_CHECK(CarContact_right_OffsetCheck, offsetof(Car, right) == 0x360);
CMR2_LAYOUT_CHECK(CarContact_up_OffsetCheck, offsetof(Car, up) == 0x36c);
CMR2_LAYOUT_CHECK(CarContact_forward_OffsetCheck, offsetof(Car, forward) == 0x378);
CMR2_LAYOUT_CHECK(CarContact_velocity_OffsetCheck, offsetof(Car, velocity) == 0x408);
CMR2_LAYOUT_CHECK(CarContact_angularVelocity_OffsetCheck, offsetof(Car, angularVelocity) == 0x420);
CMR2_LAYOUT_CHECK(CarContact_field_0x5c4_OffsetCheck, offsetof(Car, field_0x5c4) == 0x5c4);
CMR2_LAYOUT_CHECK(CarContact_field_0x5d0_OffsetCheck, offsetof(Car, field_0x5d0) == 0x5d0);
CMR2_LAYOUT_CHECK(CarContact_field_0x5dc_OffsetCheck, offsetof(Car, field_0x5dc) == 0x5dc);
CMR2_LAYOUT_CHECK(CarContact_pWorld_OffsetCheck, offsetof(Car, pWorld) == 0x750);
CMR2_LAYOUT_CHECK(CarContact_mass_OffsetCheck, offsetof(Car, mass) == 0x75c);
CMR2_LAYOUT_CHECK(CarContact_field_0x96c_OffsetCheck, offsetof(Car, field_0x96c) == 0x96c);
CMR2_LAYOUT_CHECK(CarContact_field_0xad6_OffsetCheck, offsetof(Car, field_0xad6) == 0xad6);
CMR2_LAYOUT_CHECK(CarContact_field_0xb35_OffsetCheck, offsetof(Car, field_0xb35) == 0xb35);
CMR2_LAYOUT_CHECK(CarContact_field_0xb64_OffsetCheck, offsetof(Car, field_0xb64) == 0xb64);
CMR2_LAYOUT_CHECK(CarContact_field_0xb70_OffsetCheck, offsetof(Car, field_0xb70) == 0xb70);
CMR2_LAYOUT_CHECK(CarContact_useUpperCollisionCorners_OffsetCheck, offsetof(Car, useUpperCollisionCorners) == 0xc00);
CMR2_LAYOUT_CHECK(CarContact_field_0xc04_OffsetCheck, offsetof(Car, field_0xc04) == 0xc04);
CMR2_LAYOUT_CHECK(CarContact_corners_OffsetCheck, offsetof(Car, corners) == 0x270);

// Disk-backed placement prefix read through the static-contact pointer view.
CMR2_LAYOUT_CHECK(StageObjectDiskSizeCheck, sizeof(StageObject) == 0xa0);
CMR2_LAYOUT_CHECK(StageObjectMeshOffsetCheck, offsetof(StageObject, pMesh) == 0xc);
CMR2_LAYOUT_CHECK(StageObjectFlagsPrefixCheck, offsetof(StageObject, field_0x10) == 0x10);
CMR2_LAYOUT_CHECK(StageObjectNextOffsetCheck, offsetof(StageObject, pNext) == 0x98);

// Runtime Texture fields used by option-menu sprites; original Win32 offsets.
CMR2_LAYOUT_CHECK(TextureRuntimeSizeCheck, sizeof(Texture) == 0x130);
CMR2_LAYOUT_CHECK(TextureSurfaceOffsetCheck, offsetof(Texture, pSurface) == 0x114);
CMR2_LAYOUT_CHECK(TextureSpriteOriginOffsetCheck, offsetof(Texture, field_0x11c) == 0x11c);
CMR2_LAYOUT_CHECK(TextureSpriteWidthOffsetCheck, offsetof(Texture, width) == 0x120);
CMR2_LAYOUT_CHECK(TextureSpriteHeightOffsetCheck, offsetof(Texture, height) == 0x122);
CMR2_LAYOUT_CHECK(TextureArchiveOffsetCheck, offsetof(Texture, pArchive) == 0x12c);

#include "BestTimeRecords.h"
CMR2_LAYOUT_CHECK(BestTimeRallyTailSizeCheck, sizeof(BestTimeRallyTail) == 8);
CMR2_LAYOUT_CHECK(BestTimeRallyTailPrefixCheck, offsetof(BestTimeRallyTail, field_0x0) == 0);
CMR2_LAYOUT_CHECK(BestTimeRallyTimeOffsetCheck, offsetof(BestTimeRallyTail, centiseconds) == 4);
CMR2_LAYOUT_CHECK(BestTimeCursorSizeCheck, sizeof(BestTimeCursor) == 4);
CMR2_LAYOUT_CHECK(BestTimeCursorIndexOffsetCheck, offsetof(BestTimeCursor, index) == 0);
CMR2_LAYOUT_CHECK(BestTimeCursorPointerOffsetCheck, offsetof(BestTimeCursor, bytes) == 0);
CMR2_LAYOUT_CHECK(BestTimeCursorWordOffsetCheck, offsetof(BestTimeCursor, word) == 0);
CMR2_LAYOUT_CHECK(BestTimeCursorRallyOffsetCheck, offsetof(BestTimeCursor, rally) == 0);

#include "Graphics.h"
CMR2_LAYOUT_CHECK(GraphicsSizeCheck, sizeof(Graphics) == 0x3cc);
CMR2_LAYOUT_CHECK(GraphicsRectContextCheck, offsetof(Graphics, field309_0x150) == 0x150);
CMR2_LAYOUT_CHECK(GraphicsRectWidthCheck, offsetof(Graphics, resX) == 0);
CMR2_LAYOUT_CHECK(GraphicsRectHeightCheck, offsetof(Graphics, resY) == 4);

// Car runtime basis overlays and start/reset fields (original Win32 offsets).
CMR2_LAYOUT_CHECK(CarState_bodyAxes_Check, offsetof(Car, bodyAxes) == 0x360);
CMR2_LAYOUT_CHECK(CarState_right_Check, offsetof(Car, right) == 0x360);
CMR2_LAYOUT_CHECK(CarState_up_Check, offsetof(Car, up) == 0x36c);
CMR2_LAYOUT_CHECK(CarState_forward_Check, offsetof(Car, forward) == 0x378);
CMR2_LAYOUT_CHECK(CarState_targetAxes_Check, offsetof(Car, targetAxes) == 0x384);
CMR2_LAYOUT_CHECK(CarState_targetRight_Check, offsetof(Car, targetRight) == 0x384);
CMR2_LAYOUT_CHECK(CarState_targetUp_Check, offsetof(Car, targetUp) == 0x390);
CMR2_LAYOUT_CHECK(CarState_targetForward_Check, offsetof(Car, targetForward) == 0x39c);
CMR2_LAYOUT_CHECK(CarState_corners_Check, offsetof(Car, corners) == 0x270);
CMR2_LAYOUT_CHECK(CarState_cornerPrev_Check, offsetof(Car, cornerPrev) == 0x300);
CMR2_LAYOUT_CHECK(CarState_cornerPrev2_Check, offsetof(Car, cornerPrev2) == 0x330);
CMR2_LAYOUT_CHECK(CarState_cornerAxis_Check, offsetof(Car, cornerAxis) == 0x4a4);
CMR2_LAYOUT_CHECK(CarState_cornerNormal_Check, offsetof(Car, cornerNormal) == 0x504);
CMR2_LAYOUT_CHECK(CarState_steepTime_Check, offsetof(Car, steepTime) == 0xa9c);
CMR2_LAYOUT_CHECK(CarState_cornerTriangle_Check, offsetof(Car, cornerTriangle) == 0xa9e);
CMR2_LAYOUT_CHECK(CarState_tipAngle_Check, offsetof(Car, tipAngle) == 0xb18);
CMR2_LAYOUT_CHECK(CarState_field_0xb45_Check, offsetof(Car, field_0xb45) == 0xb45);
CMR2_LAYOUT_CHECK(CarState_field_0xb28_Check, offsetof(Car, field_0xb28) == 0xb28);
CMR2_LAYOUT_CHECK(CarState_wheelSteeringAngle_Check, offsetof(Car, wheelSteeringAngle) == 0xb10);
CMR2_LAYOUT_CHECK(CarState_targetSteeringAngle_Check, offsetof(Car, targetSteeringAngle) == 0xb12);
CMR2_LAYOUT_CHECK(CarState_gear_Check, offsetof(Car, gear) == 0xb1e);
CMR2_LAYOUT_CHECK(CarState_field_0xa74_Check, offsetof(Car, field_0xa74) == 0xa74);
CMR2_LAYOUT_CHECK(CarState_field_0xa78_Check, offsetof(Car, field_0xa78) == 0xa78);
CMR2_LAYOUT_CHECK(CarBodyAxesSizeCheck, sizeof(((Car *)0)->bodyAxes) == 0x24);
CMR2_LAYOUT_CHECK(CarTargetAxesSizeCheck, sizeof(((Car *)0)->targetAxes) == 0x24);
CMR2_LAYOUT_CHECK(CarNoiseTargetWidthCheck, sizeof(((Car *)0)->field_0xa78) == 4);
